### ISSUE TITLE
更新 paddlepaddle 0.11.0 出错 CUDA error: invalid device function

### ISSUE THREAD

**Issue by ggaaooppeenngg** [PaddlePaddle/Paddle#10062]
paddlepaddle 0.11 依赖的 cudnn 和 cuda 的版本是多少?
更新 `pip2 install paddlepaddle-gpu=0.11.0` 以后出现 `CUDA error: invalid device function` 的错误。

!cat /usr/local/cuda/version.txt
!cat /usr/local/cudnn/include/cudnn.h | grep CUDNN_MAJOR -A 2
```
CUDA Version 8.0.61
#define CUDNN_MAJOR      6
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
```
```
Thu Apr 19 12:21:41 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 0000:00:06.0     Off |                  N/A |
| 23%   36C    P8    18W / 250W |    245MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
我有什么办法排查这种问题吗?

**Comment by jacquesqiao** [comment]
可以到这里下载一个对应版本的paddle安装  http://paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/pip_install_cn.html

**Comment by ggaaooppeenngg** [comment]
@jacquesqiao  下不了，走的 guest 访问，快下完了就这样。
![image](https://user-images.githubusercontent.com/4769989/39028037-59f10252-4487-11e8-9f95-8fda1b5b8e47.png)
能不能上传到国内的 CDN。

**Comment by ggaaooppeenngg** [comment]
更新 cudnn 出现
```
I0420 03:39:15.105870 15 Util.cpp:166] commandline: --use_gpu=True --trainer_count=1

F0420 03:39:15.679824 15 hl_cuda_cudnn.cc:171] Check failed: (cudnn_cuh_major < 4 && cudnn_dso_major < 4) || (cudnn_cuh_major == cudnn_dso_major) [cudnn init] libcudnn v7 with header v5 unmatched!

PaddlePaddle Requirement: (header v[2-3] with libcudnn v[2-3]) Or (header v4 with libcudnn v4) Or (header v5 with libcudnn v5) Or(header v6 with libcudnn v6).
```

**Comment by ggaaooppeenngg** [comment]
`pip2 install paddlepaddle_gpu-0.11.0-cp27-cp27m-linux_x86_64.whl` 出现
`paddlepaddle_gpu-0.11.0-cp27-cp27m-linux_x86_64.whl is not a supported wheel on this platform.`

**Comment by ggaaooppeenngg** [comment]
换回 cudnn5 还是出现
```
Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function
```

**Comment by ggaaooppeenngg** [comment]
cudnn6 也不行，看来默认装的依赖是 cudnn5

**Comment by ggaaooppeenngg** [comment]
退回到 `paddlepaddle_gpu-0.10.1-cp27-cp27mu-manylinux1_x86_64.whl` 是可以的。

**Comment by ggaaooppeenngg** [comment]
安装 https://github.com/intel/mkl-dnn 以后，运行 cifar 出错。

```
AttributeErrorTraceback (most recent call last)
<ipython-input-20-5f8b23807af3> in <module>()
----> 1 reader=paddle.batch(paddle.reader.shuffle(paddle.dataset.cifar.train10(), buf_size=50000), batch_size=128)

AttributeError: 'module' object has no attribute 'batch'
```

**Comment by ggaaooppeenngg** [comment]
使用默认的 `paddlepaddle-gpu==0.11.0`，用 BCE 的集成镜像，CUDA8+cudnn5.1
执行 `deviceQuery` 成功
```
/usr/local/cuda/samples/1_Utilities/deviceQuery/deviceQuery
/usr/local/cuda/samples/1_Utilities/deviceQuery/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "TITAN X (Pascal)"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 12189 MBytes (12781551616 bytes)
  (28) Multiprocessors, (128) CUDA Cores/MP:     3584 CUDA Cores
  GPU Max Clock rate:                            1531 MHz (1.53 GHz)
  Memory Clock rate:                             5005 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 0 / 6
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = TITAN X (Pascal)
Result = PASS
```
执行 `mnistCUDNN` 成功
```
/usr/src/cudnn_samples_v5/mnistCUDNN# ./mnistCUDNN
cudnnGetVersion() : 5110 , CUDNN_VERSION from cudnn.h : 5110 (5.1.10)
Host compiler version : GCC 5.4.0
There are 1 CUDA capable devices on your machine :
device 0 : sms 28  Capabilities 6.1, SmClock 1531.0 Mhz, MemSize (Mb) 12189, MemClock 5005.0 Mhz, Ecc=0, boardGroupID=0
Using device 0

Testing single precision
Loading image data/one_28x28.pgm
Performing forward propagation ...
Testing cudnnGetConvolutionForwardAlgorithm ...
Fastest algorithm is Algo 1
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.031648 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.056320 time requiring 57600 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.079616 time requiring 19508 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 0.128000 time requiring 2057744 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.129024 time requiring 205008 memory
Resulting weights from Softmax:
0.0000000 0.9999399 0.0000000 0.0000000 0.0000561 0.0000000 0.0000012 0.0000017 0.0000010 0.0000000
Loading image data/three_28x28.pgm
Performing forward propagation ...
Resulting weights from Softmax:
0.0000000 0.0000000 0.0000000 0.9999288 0.0000000 0.0000711 0.0000000 0.0000000 0.0000000 0.0000000
Loading image data/five_28x28.pgm
Performing forward propagation ...
Resulting weights from Softmax:
0.0000000 0.0000008 0.0000000 0.0000002 0.0000000 0.9999820 0.0000154 0.0000000 0.0000012 0.0000006

Result of classification: 1 3 5

Test passed!

Testing half precision (math in single precision)
Loading image data/one_28x28.pgm
Performing forward propagation ...
Testing cudnnGetConvolutionForwardAlgorithm ...
Fastest algorithm is Algo 1
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.032544 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.063360 time requiring 28800 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.068608 time requiring 19508 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 0.087040 time requiring 2057744 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.141248 time requiring 205008 memory
Resulting weights from Softmax:
0.0000001 1.0000000 0.0000001 0.0000000 0.0000563 0.0000001 0.0000012 0.0000017 0.0000010 0.0000001
Loading image data/three_28x28.pgm
Performing forward propagation ...
Resulting weights from Softmax:
0.0000000 0.0000000 0.0000000 1.0000000 0.0000000 0.0000720 0.0000000 0.0000000 0.0000000 0.0000000
Loading image data/five_28x28.pgm
Performing forward propagation ...
Resulting weights from Softmax:
0.0000000 0.0000008 0.0000000 0.0000002 0.0000000 1.0000000 0.0000154 0.0000000 0.0000012 0.0000006

Result of classification: 1 3 5

Test passed!
```

**Comment by ggaaooppeenngg** [comment]
@jacquesqiao 能否帮忙看一下，我觉得我的 CUDA8 和 cudnn5.1 应该是对的了，现在，安装 0.11.0 还是不能运行，出现 `CUDA error: invalid device function`，我翻了一下 Dockerfile，默认 pip 装的应该是用 CUDA8 和 cudnn5.1 的，能不能帮忙看看还要检查什么？

**Comment by ggaaooppeenngg** [comment]
总算搞定了，首先重新起了使用 BCE 集成 paddlepaddle 0.11 的没问题，保证驱动一切正常，cudnn，CUDA8 都是对的，在宿主机上可以执行例子。

然后我自己用官网的 `whl` 有 break change，看到这个我还以为是包没装好，原来就是 break change。

![image](https://user-images.githubusercontent.com/4769989/39082353-4e3afdc0-4584-11e8-9098-db4d8f4761e9.png)

查了我三天三夜，心态炸了。

**Comment by ggaaooppeenngg** [comment]
之前 `CUDA error: invalid device function` 找到错误了，是 pip 装的 gpu CUDA 版本是 7.5 的，实际环境的 CUDA 版本是 8 导致的。

**Comment by estathop** [comment]
I have some of the problems you mention but because the whole conversation is in chinese I don't understand anything. 

paddle train
I0517 12:51:39.589844 30522 Util.cpp:166] commandline: /home/estathop/.local/bin/paddle_trainer 
F0517 12:51:39.788321 30522 hl_cuda_cudnn.cc:171] Check failed: (cudnn_cuh_major < 4 && cudnn_dso_major < 4) || (cudnn_cuh_major == cudnn_dso_major) [cudnn init] libcudnn v7 with header v5 unmatched!
PaddlePaddle Requirement: (header v[2-3] with libcudnn v[2-3]) Or (header v4 with libcudnn v4) Or (header v5 with libcudnn v5) Or(header v6 with libcudnn v6).
*** Check failure stack trace: ***
    @           0x669e9d  google::LogMessage::Fail()
    @           0x66d94c  google::LogMessage::SendToLog()
    @           0x6699c3  google::LogMessage::Flush()
    @           0x66ee5e  google::LogMessageFatal::~LogMessageFatal()
    @           0xab9e99  hl_cudnn_init()
    @           0xac275e  hl_create_global_resources()
    @           0xac2e59  hl_specify_devices_start()
    @           0xac327d  hl_start()
    @           0xa2beaa  paddle::initMain()
    @           0x64aa9f  main
    @     0x7f0ff8ff1830  __libc_start_main
    @           0x6677b1  (unknown)
/home/estathop/.local/bin/paddle: line 146: 30522 Aborted                 (core dumped) ${DEBUGGER} $PADDLE_BIN_PATH/paddle_trainer ${@:2}

**Comment by ggaaooppeenngg** [comment]
@estathop  It means your libcudnn version doesn't match your paddlepaddle libcudnn dependencies.
