### ISSUE TITLE
docker.paddlepaddlehub.com/paddle:latest-dev官方docker里cuda和driver版本不匹配

### ISSUE THREAD

**Issue by wuyan08** [PaddlePaddle/Paddle#10416]
docker image是从官方下载的，宿主机的驱动版本是：NVIDIA-SMI 384.66，显卡型号：Nvidia Tesla K40m.
用nvidia-docker启动docker之后，cuda自带的sample跑不起来，提示cuda版本和driver版本不一致。

**Comment by Superjomn** [comment]
比较难的问题，之前在调sys机器时也遇到多次，host 和image很容易driver不一致。 

我们是否有一些指导性的解决方案。

**Comment by Superjomn** [comment]
错：Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version

**Comment by Superjomn** [comment]
@chengduoZH 有一些建议么

**Comment by chengduoZH** [comment]
@wuyan08 你帖一下容器里面的显示的cuda驱动版本是多少

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/39629189-e94b39c0-4fdd-11e8-859a-b63ad610c179.png)

**Comment by chengduoZH** [comment]
这个不是paddle的问题，而是环境配置问题 请参考：https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch

**Comment by wuyan08** [comment]
从nvidia官网下载cuda8.0和cudnn7.0，重装一下问题解决了。谢谢~
