### ISSUE TITLE
Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function

### ISSUE THREAD

**Issue by likeqinqin** [PaddlePaddle/Paddle#10909]
基础环境：C++动态链接库、p4卡、cuda8.0、driver384.81、cudnn7.0
具体报错信息如下：
F0524 16:04:56.877745   625 hl_gpu_matrix_kernel.cuh:181] Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function
*** Check failure stack trace: ***
    @     0x7f5011eefd3d  google::LogMessage::Fail()
    @     0x7f5011ef37ec  google::LogMessage::SendToLog()
    @     0x7f5011eef863  google::LogMessage::Flush()
    @     0x7f5011ef4cfe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f50121bf3bb  hl_gpu_apply_unary_op<>()
    @     0x7f50121bf72d  paddle::BaseMatrixT<>::applyUnary<>()
    @     0x7f50121bf973  paddle::BaseMatrixT<>::zero()
    @     0x7f5012096d18  _ZNSt17_Function_handlerIFviPN6paddle9ParameterEEZNS0_15GradientMachine6createERKNS0_11ModelConfigEiRKSt6vectorINS0_19enumeration_wrapper13ParameterTypeESaISA_EEEUliS2_E_E9_M_invokeERKSt9_Any_dataiS2_
    @     0x7f501206e3a6  paddle::NeuralNetwork::init()
    @     0x7f5012096f9f  paddle::GradientMachine::create()
    @     0x7f5011eeb4e5  paddle_gradient_machine_create_for_inference

**Comment by seiriosPlus** [comment]
cuda8配cudnn5, cuda9配cudnn7. 看能否调整一下机器的配置

**Comment by likeqinqin** [comment]
cuda8配了cudnn5，还是会报错，怀疑是不和这个版本有关nvcc --version？请帮忙看下
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44

**Comment by likeqinqin** [comment]
已解决，把paddle capi更新到了cuda8.0-cudnn5对应的版本，相关so文件也都加载进去。

**Comment by jchua127** [comment]
> 已解决，把paddle capi更新到了cuda8.0-cudnn5对应的版本，相关so文件也都加载进去。

你好，问一下，是怎么更新的Paddle capi？哪个so文件？
