### ISSUE TITLE
切换data_provider2之后，提交GPU任务出现Check failed: cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by qubingxin** [PaddlePaddle/Paddle#1097]
切换到define_py_data_sources2之后，更新receiver，跑GPU任务出现：
Check failed: cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encountered
任务链接：http://yq01-sys-hic-k4005.yq01.baidu.com:8880/output/list/4721
看之前有标记为bug，现在该如何解决？？

**Comment by qingqing01** [comment]
我记得之前fix过一次`groups>1`的bug，不确定是使用的receiver是否已经更新，你或许可以把配置里的groups改成1，这个改动不会降低精度。

**Comment by qubingxin** [comment]
@qingqing01  最后切换回旧的receiver解决了。后续尝试一下这个办法，多谢
