### ISSUE TITLE
Check failed: (cudnn_cuh_major < 4 && cudnn_dso_major < 4) || (cudnn_cuh_major == cudnn_dso_major) [cudnn init] libcudnn v5 with header v7 unmatched! PaddlePaddle Requirement: (header v[2-3] with libcudnn v[2-3]) Or (header v4 with libcudnn v4) Or (header v5 with libcudnn v5) Or(header v6 with libcudnn v6).

### ISSUE THREAD

**Issue by liuliyalei** [PaddlePaddle/Paddle#11678]
ubuntu 16.04
pip安装的GPU版本

tk@tk-Server:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.v2 as paddle
>>> paddle.init(use_gpu=True,trainer_count=1)
I0625 09:15:45.173822 20997 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
F0625 09:15:46.000280 20997 hl_cuda_cudnn.cc:171] Check failed: (cudnn_cuh_major < 4 && cudnn_dso_major < 4) || (cudnn_cuh_major == cudnn_dso_major) [cudnn init] libcudnn v5 with header v7 unmatched!
PaddlePaddle Requirement: (header v[2-3] with libcudnn v[2-3]) Or (header v4 with libcudnn v4) Or (header v5 with libcudnn v5) Or(header v6 with libcudnn v6).
*** Check failure stack trace: ***
    @     0x7f9bd89abf8d  google::LogMessage::Fail()
    @     0x7f9bd89afa3c  google::LogMessage::SendToLog()
    @     0x7f9bd89abab3  google::LogMessage::Flush()
    @     0x7f9bd89b0f4e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f9bd8961eaf  hl_cudnn_init()
    @     0x7f9bd8969ed5  hl_create_global_resources()
    @     0x7f9bd896a681  hl_specify_devices_start()
    @     0x7f9bd896aa3d  hl_start()
    @     0x7f9bd88f4406  paddle::initMain()
    @     0x7f9bd8993ac1  initPaddle()
    @     0x7f9bd85401f9  _wrap_initPaddle
    @           0x4c30ce  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4d54b9  (unknown)
    @           0x4a577e  PyObject_Call
    @           0x4bed3d  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4eb30f  (unknown)
    @           0x44a7a2  PyRun_InteractiveOneFlags
    @           0x44a56d  PyRun_InteractiveLoopFlags
    @           0x43092e  (unknown)
    @           0x493ae2  Py_Main
    @     0x7f9c19548830  __libc_start_main
    @           0x4933e9  _start
    @              (nil)  (unknown)

**Comment by ktlichkid** [comment]
应该是您编译的cudnn版本和cudnn库不匹配导致的。请问您编译的是哪个whl包呢？

**Comment by liuliyalei** [comment]
安装的版本如下：
PaddlePaddle 0.13.0 
查看发现系统的cuda和cudnn版本：
CUDA Version 8.0.61
cudnn 5.110

我在想是不是我的paddle安装版本选择出了错
@ktlichkid

**Comment by liuliyalei** [comment]
我将paddle 0.13.0卸载之后
重装0.12.0
whl包为paddlepaddle_gpu-0.12.0-cp27-cp27mu-manylinux1_x86_64.whl
然后解决了该问题

但是新的问题又出现了：
tk@tk-Server:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.v2 as paddle
>>> paddle.init(use_gpu=True,trainer_count=1)
I0625 10:59:19.737781 21538 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
W0625 10:59:20.750013 21538 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON

我试图 CMAKE .. -DWITH_AVX=ON，报错：
tk@tk-Server:/usr/bin$ cmake .. -DWITH_AVX=ON
CMake Error: The source directory "/usr" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
@ktlichkid 

感谢你的回复

**Comment by ktlichkid** [comment]
这应该是说找不到 CMakeLists.txt 这个文件，请问这个文件的路径您确定是在/usr下面吗？

**Comment by liuliyalei** [comment]
tk@tk-Server:/$ locate CMakeLists.txt
...
/usr/share/cmake-3.5/Modules/FortranCInterface/CMakeLists.txt
/usr/share/cmake-3.5/Modules/FortranCInterface/Verify/CMakeLists.txt
/usr/share/cmake-3.5/Modules/IntelVSImplicitPath/CMakeLists.txt

我应该cd到哪个文件夹下面执行呢？
@ktlichkid

**Comment by liuliyalei** [comment]
locate CMakeLists.txt 结果如下：

@tk-Server:/$ locate CMakeLists.txt
/home/tk/.local/lib/python2.7/site-packages/external/eigen_archive/unsupported/Eigen/CXX11/CMakeLists.txt
/home/tk/.local/lib/python2.7/site-packages/tensorflow/include/external/eigen_archive/unsupported/Eigen/CXX11/CMakeLists.txt
/home/tk/.local/lib/python2.7/site-packages/tensorflow/include/unsupported/Eigen/CXX11/CMakeLists.txt
/home/tk/.local/lib/python3.5/site-packages/external/eigen_archive/unsupported/Eigen/CXX11/CMakeLists.txt
/home/tk/.local/lib/python3.5/site-packages/tensorflow/include/external/eigen_archive/unsupported/Eigen/CXX11/CMakeLists.txt
/home/tk/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/android/cmake/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/patches/cub/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/patches/farmhash/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/patches/fft2d/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/patches/gemmlowp/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/patches/gif/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/patches/highwayhash/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/patches/jpeg/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/patches/lmdb/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/patches/nsync/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/contrib/cmake/patches/sqlite/CMakeLists.txt
/home/tk/test/tensorflow/tensorflow-master/tensorflow/examples/android/jni/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/carotene/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/carotene/hal/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/cpufeatures/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/ippicv/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/ittnotify/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/libjasper/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/libjpeg/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/libpng/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/libtiff/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/libwebp/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/openexr/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/openvx/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/openvx/hal/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/protobuf/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/tbb/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/3rdparty/zlib/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/apps/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/apps/annotation/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/apps/createsamples/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/apps/interactive-calibration/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/apps/traincascade/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/apps/version/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/apps/visualisation/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/build/3rdparty/ippicv/ippiw_lnx/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/data/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/doc/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/include/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/calib3d/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/core/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudaarithm/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudabgsegm/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudacodec/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudafeatures2d/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudafilters/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudaimgproc/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudalegacy/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudaobjdetect/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudaoptflow/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudastereo/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudawarping/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudev/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/cudev/test/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/dnn/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/features2d/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/flann/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/highgui/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/imgcodecs/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/imgproc/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/java/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/java/android_test/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/java/pure_test/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/js/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/ml/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/objdetect/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/photo/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/python/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/python/python2/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/python/python3/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/shape/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/stitching/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/superres/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/ts/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/video/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/videoio/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/videostab/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/viz/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/modules/world/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/platforms/android/service/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/platforms/android/service/engine/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/15-puzzle/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/camera-calibration/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/color-blob-detection/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/face-detection/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/hello-android/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/image-manipulations/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/mobilenet-objdetect/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/tutorial-1-camerapreview/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/tutorial-2-mixedprocessing/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/tutorial-3-cameracontrol/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/android/tutorial-4-opencl/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/cpp/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/cpp/example_cmake/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/cpp/tutorial_code/gpu/gpu-thrust-interop/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/directx/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/dnn/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/gpu/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/gpu/performance/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/hal/c_hal/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/hal/slow_hal/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/java/tutorial_code/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/opencl/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/opengl/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/openvx/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/python/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/tapi/CMakeLists.txt
/home/tk/tools/peizhi/opencv-3.3.1/samples/va_intel/CMakeLists.txt
/home/tk/work/caffe/CMakeLists.txt
/home/tk/work/caffe/docs/CMakeLists.txt
/home/tk/work/caffe/examples/CMakeLists.txt
/home/tk/work/caffe/matlab/CMakeLists.txt
/home/tk/work/caffe/python/CMakeLists.txt
/home/tk/work/caffe/src/caffe/CMakeLists.txt
/home/tk/work/caffe/src/caffe/test/CMakeLists.txt
/home/tk/work/caffe/src/gtest/CMakeLists.txt
/home/tk/work/caffe/tools/CMakeLists.txt
/lib/firmware/carl9170fw/CMakeLists.txt
/lib/firmware/carl9170fw/carlfw/CMakeLists.txt
/lib/firmware/carl9170fw/config/CMakeLists.txt
/lib/firmware/carl9170fw/minifw/CMakeLists.txt
/lib/firmware/carl9170fw/tools/CMakeLists.txt
/lib/firmware/carl9170fw/tools/carlu/CMakeLists.txt
/lib/firmware/carl9170fw/tools/lib/CMakeLists.txt
/lib/firmware/carl9170fw/tools/src/CMakeLists.txt
/usr/local/cuda-8.0/nvvm/libnvvm-samples/CMakeLists.txt
/usr/local/cuda-8.0/nvvm/libnvvm-samples/cuda-c-linking/CMakeLists.txt
/usr/local/cuda-8.0/nvvm/libnvvm-samples/ptxgen/CMakeLists.txt
/usr/local/cuda-8.0/nvvm/libnvvm-samples/simple/CMakeLists.txt
/usr/share/cmake-3.5/Modules/FortranCInterface/CMakeLists.txt
/usr/share/cmake-3.5/Modules/FortranCInterface/Verify/CMakeLists.txt
/usr/share/cmake-3.5/Modules/IntelVSImplicitPath/CMakeLists.txt

**Comment by luotao1** [comment]
请问 https://github.com/PaddlePaddle/Paddle/issues/11678#issuecomment-399818481 错误影响你继续往下执行么？
另外，如果要cmake编译的话，请参考 http://paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/build_from_source_cn.html

**Comment by liuliyalei** [comment]
之前我准备在jupyter notebook里面训练模型，结果总是kernel died
然后我回头在python下面检查paddle，发现
import paddle.v2 as paddle
paddle.init(use_gpu=True,trainer_count=1)
I0625 10:59:19.737781 21538 Util.cpp:166] commandline: --use_gpu=True --trainer_count=1
W0625 10:59:20.750013 21538 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON

所以我一直想要解决这个问题 
@luotao1 
如果你可以帮我解决kernel died的问题，感激不尽

**Comment by ktlichkid** [comment]
AVX那个ON必须要从源码编译才能改，所以您用whl包安装应该是改不了的~
如果实在要改建议用cmake从源码编译。
但理论上讲这个AVX不用应该也是可以运行的才对。
您可以先试试判断下kernel died的具体原因，比如把完整代码从.ipynb里面拷到.py文件里，看看还有没有报其他错误。

**Comment by luotao1** [comment]
> F0625 09:15:46.000280 20997 hl_cuda_cudnn.cc:171] Check failed: (cudnn_cuh_major < 4 && cudnn_dso_major < 4) || (cudnn_cuh_major == cudnn_dso_major) [cudnn init] libcudnn v5 with header v7 unmatched!

从这个错误看，cudnn版本不符合。

**Comment by liuliyalei** [comment]
tk@tk-Server:~/paddle/object_detection/code$ python train.py
I0625 17:17:59.623597 26336 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=2 
W0625 17:18:00.306799 26336 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
[INFO 2018-06-25 17:18:00,312 layers.py:2716] output for conv1_1: c = 64, h = 300, w = 300, size = 5760000
[INFO 2018-06-25 17:18:00,313 layers.py:2716] output for conv1_2: c = 64, h = 300, w = 300, size = 5760000
[INFO 2018-06-25 17:18:00,314 layers.py:2858] output for pool1: c = 64, h = 150, w = 150, size = 1440000
[INFO 2018-06-25 17:18:00,314 layers.py:2716] output for conv2_1: c = 128, h = 150, w = 150, size = 2880000
[INFO 2018-06-25 17:18:00,316 layers.py:2716] output for conv2_2: c = 128, h = 150, w = 150, size = 2880000
[INFO 2018-06-25 17:18:00,317 layers.py:2858] output for pool2: c = 128, h = 75, w = 75, size = 720000
[INFO 2018-06-25 17:18:00,318 layers.py:2716] output for conv3_1: c = 256, h = 75, w = 75, size = 1440000
[INFO 2018-06-25 17:18:00,319 layers.py:2716] output for conv3_2: c = 256, h = 75, w = 75, size = 1440000
[INFO 2018-06-25 17:18:00,319 layers.py:2716] output for conv3_3: c = 256, h = 75, w = 75, size = 1440000
[INFO 2018-06-25 17:18:00,320 layers.py:2858] output for __pool_0__: c = 256, h = 38, w = 38, size = 369664
[INFO 2018-06-25 17:18:00,321 layers.py:2716] output for conv4_1: c = 512, h = 38, w = 38, size = 739328
[INFO 2018-06-25 17:18:00,321 layers.py:2716] output for conv4_2: c = 512, h = 38, w = 38, size = 739328
[INFO 2018-06-25 17:18:00,322 layers.py:2716] output for conv4_3: c = 512, h = 38, w = 38, size = 739328
[INFO 2018-06-25 17:18:00,323 layers.py:2858] output for __pool_1__: c = 512, h = 19, w = 19, size = 184832
[INFO 2018-06-25 17:18:00,324 layers.py:2716] output for conv4_3_norm_mbox_loc: c = 12, h = 38, w = 38, size = 17328
[INFO 2018-06-25 17:18:00,325 layers.py:2716] output for conv4_3_norm_mbox_conf: c = 63, h = 38, w = 38, size = 90972
[INFO 2018-06-25 17:18:00,326 layers.py:2716] output for conv5_1: c = 512, h = 19, w = 19, size = 184832
[INFO 2018-06-25 17:18:00,327 layers.py:2716] output for conv5_2: c = 512, h = 19, w = 19, size = 184832
[INFO 2018-06-25 17:18:00,328 layers.py:2716] output for conv5_3: c = 512, h = 19, w = 19, size = 184832
[INFO 2018-06-25 17:18:00,328 layers.py:2858] output for __pool_2__: c = 512, h = 19, w = 19, size = 184832
[INFO 2018-06-25 17:18:00,329 layers.py:2716] output for fc6: c = 1024, h = 19, w = 19, size = 369664
[INFO 2018-06-25 17:18:00,330 layers.py:2716] output for fc7: c = 1024, h = 19, w = 19, size = 369664
[INFO 2018-06-25 17:18:00,331 layers.py:2716] output for fc7_mbox_loc: c = 24, h = 19, w = 19, size = 8664
[INFO 2018-06-25 17:18:00,331 layers.py:2716] output for fc7_mbox_conf: c = 126, h = 19, w = 19, size = 45486
[INFO 2018-06-25 17:18:00,333 layers.py:2716] output for conv6_1: c = 256, h = 19, w = 19, size = 92416
[INFO 2018-06-25 17:18:00,333 layers.py:2716] output for conv6_2: c = 512, h = 10, w = 10, size = 51200
[INFO 2018-06-25 17:18:00,334 layers.py:2716] output for conv6_2_mbox_loc: c = 24, h = 10, w = 10, size = 2400
[INFO 2018-06-25 17:18:00,335 layers.py:2716] output for conv6_2_mbox_conf: c = 126, h = 10, w = 10, size = 12600
[INFO 2018-06-25 17:18:00,336 layers.py:2716] output for conv7_1: c = 128, h = 10, w = 10, size = 12800
[INFO 2018-06-25 17:18:00,337 layers.py:2716] output for conv7_2: c = 256, h = 5, w = 5, size = 6400
[INFO 2018-06-25 17:18:00,337 layers.py:2716] output for conv7_2_mbox_loc: c = 24, h = 5, w = 5, size = 600
[INFO 2018-06-25 17:18:00,338 layers.py:2716] output for conv7_2_mbox_conf: c = 126, h = 5, w = 5, size = 3150
[INFO 2018-06-25 17:18:00,340 layers.py:2716] output for conv8_1: c = 128, h = 5, w = 5, size = 3200
[INFO 2018-06-25 17:18:00,341 layers.py:2716] output for conv8_2: c = 256, h = 3, w = 3, size = 2304
[INFO 2018-06-25 17:18:00,341 layers.py:2716] output for conv8_2_mbox_loc: c = 24, h = 3, w = 3, size = 216
[INFO 2018-06-25 17:18:00,342 layers.py:2716] output for conv8_2_mbox_conf: c = 126, h = 3, w = 3, size = 1134
[INFO 2018-06-25 17:18:00,343 layers.py:2858] output for pool6: c = 256, h = 1, w = 1, size = 256
[INFO 2018-06-25 17:18:00,344 layers.py:2716] output for pool6_mbox_loc: c = 24, h = 1, w = 1, size = 24
[INFO 2018-06-25 17:18:00,344 layers.py:2716] output for pool6_mbox_conf: c = 126, h = 1, w = 1, size = 126
I0625 17:18:02.690415 26336 MultiGradientMachine.cpp:99] numLogicalDevices=1 numThreads=2 numDevices=1
F0625 17:18:02.690459 26336 MultiGradientMachine.cpp:104] trainer_count * num_devices_in_model (2*1)=2 exceeds number of GPU devices(1)
*** Check failure stack trace: ***
    @     0x7ff7bc51506d  google::LogMessage::Fail()
    @     0x7ff7bc518b1c  google::LogMessage::SendToLog()
    @     0x7ff7bc514b93  google::LogMessage::Flush()
    @     0x7ff7bc51a02e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff7bc1317c5  paddle::MultiGradientMachine::MultiGradientMachine()
    @     0x7ff7bc129d1f  paddle::GradientMachine::create()
    @     0x7ff7bc4f1f03  GradientMachine::createFromPaddleModelPtr()
    @     0x7ff7bc4f20df  GradientMachine::createByConfigProtoStr()
    @     0x7ff7bc0cc62d  _wrap_GradientMachine_createByConfigProtoStr
    @           0x4c30ce  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4d55f3  (unknown)
    @           0x4eebee  (unknown)
    @           0x4ee7f6  (unknown)
    @           0x4aa9ab  (unknown)
    @           0x4c15bf  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4eb30f  (unknown)
    @           0x4e5422  PyRun_FileExFlags
    @           0x4e3cd6  PyRun_SimpleFileExFlags
    @           0x493ae2  Py_Main
    @     0x7ff7fc9d1830  __libc_start_main
    @           0x4933e9  _start
    @              (nil)  (unknown)
已放弃 (核心已转储)

@ktlichkid 
麻烦帮忙看看是什么原因，我把原来的代码文件从.ipynb原封不动保存为.py格式，并且用python运行，结果如上

**Comment by luotao1** [comment]
> F0625 17:18:02.690459 26336 MultiGradientMachine.cpp:104] trainer_count * num_devices_in_model (2*1)=2 exceeds number of GPU devices(1)

请问你机器上有几块GPU卡呢

**Comment by liuliyalei** [comment]
嗯那个问题我已经解决了，把原来的0.13.0版本卸载，安装了适合我本身系统的现在的0.12.0版本，现在就剩kernel died的问题了 @luotao1

**Comment by liuliyalei** [comment]
![qq 20180625172509](https://user-images.githubusercontent.com/40382579/41842260-e0fa715e-789c-11e8-8bbf-c3b4dc5bbbe0.png)
@luotao1 
我查看了GPU信息不知道有没有用

**Comment by liuliyalei** [comment]
补充一下我的环境
CUDA Version 8.0.61

cudnn 5.1

PaddlePaddle 0.12.0
paddlepaddle_gpu-0.12.0-cp27-cp27mu-manylinux1_x86_64.whl

@ktlichkid @luotao1

**Comment by ktlichkid** [comment]
疑似是GPU卡数的问题。试试把--trainer_count=2 改成--trainer_count=1看看？

**Comment by liuliyalei** [comment]
已解决非常感谢 @ktlichkid @luotao1
