### ISSUE TITLE
PyramidBox预测需要很大的显存吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16071]
# 环境
 - PaddlePaddle 1.3 GPU
 - Ubuntu 16.04
 - 显卡 2070  8G
 - 模型 PyramidBox

# 问题
我在执行PyramidBox的模型预测时，显存不足。我的系统基本上没有使用到卡，PyramidBox预测需要很大的显存吗？

```
-----------  Configuration Arguments -----------
confs_threshold: 0.15
image_path: images/000001.jpg
infer: True
model_dir: model/
use_gpu: True
use_pyramidbox: True
------------------------------------------------
W0306 10:42:24.907287  8577 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 75, Driver Version: 10.0, Runtime Version: 10.0
W0306 10:42:24.907317  8577 device_context.cc:210] device: 0, cuDNN Version: 7.0.
W0306 10:42:25.336884  8577 system_allocator.cc:122] Cannot malloc 3776.16 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use environment variable to a lower value. Current value is 0.5
W0306 10:42:25.337054  8577 legacy_allocator.cc:161] Cannot allocate 275.468750MB in GPU 0, available 3.254028GB
W0306 10:42:25.337059  8577 legacy_allocator.cc:164] total 8335982592
W0306 10:42:25.337064  8577 legacy_allocator.cc:165] GpuMinChunkSize 256.000000B
W0306 10:42:25.337067  8577 legacy_allocator.cc:168] GpuMaxChunkSize 3.687657GB
W0306 10:42:25.337072  8577 legacy_allocator.cc:171] GPU memory used: 3.561373GB
Traceback (most recent call last):
  File "widerface_eval.py", line 266, in <module>
    infer(args)
  File "widerface_eval.py", line 43, in infer
    [det2, det3] = multi_scale_test(image, max_shrink)
  File "widerface_eval.py", line 155, in multi_scale_test
    det_b = detect_face(image, bt)
  File "widerface_eval.py", line 73, in detect_face
    return_numpy=False)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: CUDNN_STATUS_BAD_PARAM at [/home/test/Downloads/Paddle/paddle/fluid/operators/batch_norm_op.cu.cc:143]
PaddlePaddle Call Stacks: 
0       0x7f59fe46da27p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7f59fe830a02p paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1922
2       0x7f59fe83238fp std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 47
3       0x7f59ffe696e2p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 658
4       0x7f59ffe635a0p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 544
5       0x7f59fe564778p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 248
6       0x7f59fe56644ap paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 154
7       0x7f59fe44b56ap
8       0x7f59fe49c16dp
9             0x4ea137p PyCFunction_Call + 119
10            0x53c176p PyEval_EvalFrameEx + 23030
11            0x53fc97p
12            0x53b83fp PyEval_EvalFrameEx + 20671
13            0x53b294p PyEval_EvalFrameEx + 19220
14            0x53b294p PyEval_EvalFrameEx + 19220
15            0x53b294p PyEval_EvalFrameEx + 19220
16            0x53fc97p
17            0x5409bfp PyEval_EvalCode + 31
18            0x60cb42p
19            0x60efeap PyRun_FileExFlags + 154
20            0x60f7dcp PyRun_SimpleFileExFlags + 444
21            0x640256p Py_Main + 1110
22            0x4d0001p main + 225
23      0x7f5a4c83d830p __libc_start_main + 240
24            0x5d6999p _start + 41

*** Aborted at 1551840145 (unix time) try "date -d @1551840145" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x10) received by PID 8577 (TID 0x7f5a4d003700) from PID 16; stack trace: ***
    @     0x7f5a4cbf8390 (unknown)
    @     0x7f59fff507dc paddle::memory::detail::MetadataCache::load()
    @     0x7f59fff4fea3 paddle::memory::detail::MemoryBlock::type()
    @     0x7f59fff4f183 paddle::memory::detail::BuddyAllocator::Free()
    @     0x7f59fff4ba05 paddle::memory::allocation::LegacyAllocator::Free()
    @     0x7f59fe46f19a paddle::framework::Variable::PlaceholderImpl<>::~PlaceholderImpl()
    @     0x7f59ffec86bb paddle::framework::Scope::~Scope()
    @     0x7f59ffec85e1 paddle::framework::Scope::DropKids()
    @     0x7f59ffec8677 paddle::framework::Scope::~Scope()
    @     0x7f59fe466f39 _ZN8pybind116class_IN6paddle9framework5ScopeEJEE7deallocERNS_6detail16value_and_holderE
    @     0x7f59fe49df3b pybind11::detail::clear_instance()
    @     0x7f59fe49e78f pybind11_object_dealloc
    @           0x59ba66 PyDict_Clear
    @           0x59be09 (unknown)
    @           0x51852d (unknown)
    @           0x60b317 _PyGC_CollectNoFail
    @           0x52363f PyImport_Cleanup
    @           0x60e2de Py_Finalize
    @           0x640446 Py_Main
    @           0x4d0001 main
    @     0x7f5a4c83d830 __libc_start_main
    @           0x5d6999 _start
    @                0x0 (unknown)
段错误 (核心已转储)
```

**Comment by qingqing01** [comment]
@yeyupiaoling 8G的显存是能跑起来的，你机器多大显存？以及你输入图片多大？

```python
    infer(args)
  File "widerface_eval.py", line 43, in infer
    [det2, det3] = multi_scale_test(image, max_shrink)
  File "widerface_eval.py", line 155, in multi_scale_test
    det_b = detect_face(image, bt)
  File "widerface_eval.py", line 73, in detect_face
```

从你的log来看，你使用了多尺度测试，你可以只使用其中一个测试，将输入图片Resize小点，作为输入测试，看下可否跑起来。

比如这里的改动： https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/face_detection/widerface_eval.py#L53

**Comment by AmitRozner** [comment]
Is there a way to use less GPU memory and still use the multi scale test? Does fluid have an environment variable which can limit the GPU memory used (probably will run slower) like tensorflow's per_process_gpu_memory_fraction?

**Comment by yeyupiaoling** [comment]
@qingqing01 我的是8G的显存，因为使用的是GPU进行预测，所以它使用多尺度测试。我按照你的解决办法先试试。

**Comment by yeyupiaoling** [comment]
@AmitRozner Hi, Paddle Paddle can also be set up like this.

**Comment by AmitRozner** [comment]
@yeyupiaoling Using less tests (i.e. without multi scale) will result in performance degradation. Can I choose to run the full test on 8GB GPU even if it runs slower? I can run it on CPU as well but I want to take advantage of the 8GB GPU capability.

**Comment by yeyupiaoling** [comment]
@qingqing01 青青姐，我将输入图片Resize小点也不行的。
最后我是使用这一行代码预测的：https://github.com/PaddlePaddle/models/blob/4dc42a621ec5b2f9c369dc8f6b6e9da18bf932e6/fluid/PaddleCV/face_detection/widerface_eval.py#L55

看注释是说CPU跑这行代码，但是CPU根本机跑不了的，一启动内存就炸了，我的是8G内存，另外还有11G交换。都不行。

只有使用GPU来跑这个：https://github.com/PaddlePaddle/models/blob/4dc42a621ec5b2f9c369dc8f6b6e9da18bf932e6/fluid/PaddleCV/face_detection/widerface_eval.py#L55
才能执行预测。这个模型应该很消耗显存和内存吧？预测一张图片需要600多ms，我的是8G的2070显卡。

**Comment by yeyupiaoling** [comment]
@AmitRozner 
I can use 8G GPU to run it. But I can't use CPU to run it. You must use [this code](https://github.com/PaddlePaddle/models/blob/4dc42a621ec5b2f9c369dc8f6b6e9da18bf932e6/fluid/PaddleCV/face_detection/widerface_eval.py#L55)  run use GPU.

**Comment by yeyupiaoling** [comment]
@qingqing01 我发现我把模型保存为预测模型之后，再使用预测模型预测，这时候无论是使用GPU还是CPU都可以正常预测了。如下代码：
```python
import argparse
import functools
import os
import time
import numpy as np
import paddle.fluid as fluid
from PIL import Image

import reader
from utility import add_arguments, print_arguments
from visualize import draw_bboxes

use_gpu = True
# 创建执行器
place = fluid.CUDAPlace(0) if use_gpu else fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())

# 保存预测模型路径
save_path = 'pyramidbox_model/'
# 从模型中获取预测程序、输入数据名称列表、分类器
[infer_program, feeded_var_names, target_var] = fluid.io.load_inference_model(dirname=save_path, 
                                                                              executor=exe,
                                                                              model_filename='model',
                                                                              params_filename='params')

def infer(image_path, confs_threshold):

    if True:
        image = Image.open(image_path)
        if image.mode == 'L':
            image = image.convert('RGB')
        shrink, max_shrink = get_shrink(image.size[1], image.size[0])

        start = time.time()
        det0 = detect_face(image, shrink)

        dets = det0
        end = time.time()
        print("infer time: %f" % (end - start))

        keep_index = np.where(dets[:, 4] >= confs_threshold)[0]
        dets = dets[keep_index, :]
        draw_bboxes(image_path, dets[:, 0:4])


def detect_face(image, shrink):
    image_shape = [3, image.size[1], image.size[0]]
    if shrink != 1:
        h, w = int(image_shape[1] * shrink), int(image_shape[2] * shrink)
        image = image.resize((w, h), Image.ANTIALIAS)
        image_shape = [3, h, w]

    img = np.array(image)
    img = reader.to_chw_bgr(img)
    mean = [104., 117., 123.]
    scale = 0.007843
    img = img.astype('float32')
    img -= np.array(mean)[:, np.newaxis, np.newaxis].astype('float32')
    img = img * scale
    img = [img]
    img = np.array(img)

    detection, = exe.run(infer_program,
                         feed={feeded_var_names[0]: img},
                         fetch_list=target_var,
                         return_numpy=False)
    detection = np.array(detection)
    # layout: xmin, ymin, xmax. ymax, score
    if np.prod(detection.shape) == 1:
        print("No face detected")
        return np.array([[0, 0, 0, 0, 0]])
    det_conf = detection[:, 1]
    det_xmin = image_shape[2] * detection[:, 2] / shrink
    det_ymin = image_shape[1] * detection[:, 3] / shrink
    det_xmax = image_shape[2] * detection[:, 4] / shrink
    det_ymax = image_shape[1] * detection[:, 5] / shrink

    det = np.column_stack((det_xmin, det_ymin, det_xmax, det_ymax, det_conf))
    return det



def get_shrink(height, width):
    """
    Args:
        height (int): image height.
        width (int): image width.
    """
    # avoid out of memory
    max_shrink_v1 = (0x7fffffff / 577.0 / (height * width)) ** 0.5
    max_shrink_v2 = ((678 * 1024 * 2.0 * 2.0) / (height * width)) ** 0.5

    def get_round(x, loc):
        str_x = str(x)
        if '.' in str_x:
            str_before, str_after = str_x.split('.')
            len_after = len(str_after)
            if len_after >= 3:
                str_final = str_before + '.' + str_after[0:loc]
                return float(str_final)
            else:
                return x

    max_shrink = get_round(min(max_shrink_v1, max_shrink_v2), 2) - 0.3
    if max_shrink >= 1.5 and max_shrink < 2:
        max_shrink = max_shrink - 0.1
    elif max_shrink >= 2 and max_shrink < 3:
        max_shrink = max_shrink - 0.2
    elif max_shrink >= 3 and max_shrink < 4:
        max_shrink = max_shrink - 0.3
    elif max_shrink >= 4 and max_shrink < 5:
        max_shrink = max_shrink - 0.4
    elif max_shrink >= 5:
        max_shrink = max_shrink - 0.5

    shrink = max_shrink if max_shrink < 1 else 1
    return shrink, max_shrink

if __name__ == '__main__':
    confs_threshold = 0.15
    image_path = 'images/000001.jpg'
    infer(image_path, confs_threshold)
```

**Comment by yeyupiaoling** [comment]
@AmitRozner I try success. When I use [this code](https://github.com/PaddlePaddle/models/blob/4dc42a621ec5b2f9c369dc8f6b6e9da18bf932e6/fluid/PaddleCV/face_detection/widerface_eval.py#L317-L319)  to save model. Then use the code to infer image .  You use GPU or CPU to run it.
```python
import argparse
import functools
import os
import time
import numpy as np
import paddle.fluid as fluid
from PIL import Image

import reader
from utility import add_arguments, print_arguments
from visualize import draw_bboxes

use_gpu = True
# 创建执行器
place = fluid.CUDAPlace(0) if use_gpu else fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())

# 保存预测模型路径
save_path = 'pyramidbox_model/'
# 从模型中获取预测程序、输入数据名称列表、分类器
[infer_program, feeded_var_names, target_var] = fluid.io.load_inference_model(dirname=save_path, 
                                                                              executor=exe,
                                                                              model_filename='model',
                                                                              params_filename='params')

def infer(image_path, confs_threshold):

    if True:
        image = Image.open(image_path)
        if image.mode == 'L':
            image = image.convert('RGB')
        shrink, max_shrink = get_shrink(image.size[1], image.size[0])

        start = time.time()
        det0 = detect_face(image, shrink)

        dets = det0
        end = time.time()
        print("infer time: %f" % (end - start))

        keep_index = np.where(dets[:, 4] >= confs_threshold)[0]
        dets = dets[keep_index, :]
        draw_bboxes(image_path, dets[:, 0:4])


def detect_face(image, shrink):
    image_shape = [3, image.size[1], image.size[0]]
    if shrink != 1:
        h, w = int(image_shape[1] * shrink), int(image_shape[2] * shrink)
        image = image.resize((w, h), Image.ANTIALIAS)
        image_shape = [3, h, w]

    img = np.array(image)
    img = reader.to_chw_bgr(img)
    mean = [104., 117., 123.]
    scale = 0.007843
    img = img.astype('float32')
    img -= np.array(mean)[:, np.newaxis, np.newaxis].astype('float32')
    img = img * scale
    img = [img]
    img = np.array(img)

    detection, = exe.run(infer_program,
                         feed={feeded_var_names[0]: img},
                         fetch_list=target_var,
                         return_numpy=False)
    detection = np.array(detection)
    # layout: xmin, ymin, xmax. ymax, score
    if np.prod(detection.shape) == 1:
        print("No face detected")
        return np.array([[0, 0, 0, 0, 0]])
    det_conf = detection[:, 1]
    det_xmin = image_shape[2] * detection[:, 2] / shrink
    det_ymin = image_shape[1] * detection[:, 3] / shrink
    det_xmax = image_shape[2] * detection[:, 4] / shrink
    det_ymax = image_shape[1] * detection[:, 5] / shrink

    det = np.column_stack((det_xmin, det_ymin, det_xmax, det_ymax, det_conf))
    return det



def get_shrink(height, width):
    """
    Args:
        height (int): image height.
        width (int): image width.
    """
    # avoid out of memory
    max_shrink_v1 = (0x7fffffff / 577.0 / (height * width)) ** 0.5
    max_shrink_v2 = ((678 * 1024 * 2.0 * 2.0) / (height * width)) ** 0.5

    def get_round(x, loc):
        str_x = str(x)
        if '.' in str_x:
            str_before, str_after = str_x.split('.')
            len_after = len(str_after)
            if len_after >= 3:
                str_final = str_before + '.' + str_after[0:loc]
                return float(str_final)
            else:
                return x

    max_shrink = get_round(min(max_shrink_v1, max_shrink_v2), 2) - 0.3
    if max_shrink >= 1.5 and max_shrink < 2:
        max_shrink = max_shrink - 0.1
    elif max_shrink >= 2 and max_shrink < 3:
        max_shrink = max_shrink - 0.2
    elif max_shrink >= 3 and max_shrink < 4:
        max_shrink = max_shrink - 0.3
    elif max_shrink >= 4 and max_shrink < 5:
        max_shrink = max_shrink - 0.4
    elif max_shrink >= 5:
        max_shrink = max_shrink - 0.5

    shrink = max_shrink if max_shrink < 1 else 1
    return shrink, max_shrink

if __name__ == '__main__':
    confs_threshold = 0.15
    image_path = 'images/000001.jpg'
    infer(image_path, confs_threshold)
```

**Comment by yeyupiaoling** [comment]
@qingqing01 青青姐，我突然想到一个问题，这些代码的区别是什么：https://github.com/PaddlePaddle/models/blob/4dc42a621ec5b2f9c369dc8f6b6e9da18bf932e6/fluid/PaddleCV/face_detection/widerface_eval.py#L48-L52

**Comment by yeyupiaoling** [comment]
@qingqing01 青青姐，能解释以下if和else的不同点吗?然后我好解决这个问题，最后close

**Comment by scorpinxia** [comment]
@yeyupiaoling  为什么用官方的demo cpu预测时间就几百毫秒 用你的自定义函数保存模型预测cpu需要21秒   这是什么原因
