### ISSUE TITLE
您好，关于CUDNN_STATUS_INTERNAL_ERROR at [/paddle/paddle/fluid/platform/device_context.cc:217]

### ISSUE THREAD

**Issue by yangninghua** [PaddlePaddle/Paddle#18885]
您好，paddle1.4.1  python3.6  cuda9.0  cudnn7.5.1可以，
paddle1.5.1  python2.7  cuda9.0 cuddn7.5就不行了
```
W0730 14:55:33.858399 10216 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0
W0730 14:55:33.860632 10216 device_context.cc:267] device: 0, cuDNN Version: 7.5.
Traceback (most recent call last):
  File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 367, in <module>
    main(use_cuda=use_cuda, nn_type=predict)
  File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 343, in main
    params_filename=params_filename)
  File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 212, in train
    fetch_list=[avg_loss, acc])
  File "/home/spple/anaconda3/envs/paddle1_5_1--py2_7--cuda9_0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "/home/spple/anaconda3/envs/paddle1_5_1--py2_7--cuda9_0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator conv2d error.
Python Callstacks: 
  File "/home/spple/anacona3/envs/paddle1_5_1--py2_7--cuda9_0/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/spple/anaconda3/envs/paddle1_5_1--py2_7--cuda9_0/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/spple/anaconda3/envs/paddle1_5_1--py2_7--cuda9_0/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2181, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "/home/spple/paddle/paddle_backbone/paddlecv/models/shufflenet_v2.py", line 115, in conv_bn_layer
    bias_attr=False)
  File "/home/spple/paddle/paddle_backbone/paddlecv/models/shufflenet_v2.py", line 68, in net
    conv1 = self.conv_bn_layer(input=input, filter_size=3, num_filters=input_channel, padding=1, stride=2,name='stage1_conv')
  File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 76, in pre_train_10class
    prediction = paddlecv.get_model("shufflenetv2").net(input=img, class_dim=10)
  File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 159, in train
    prediction, avg_loss, acc = net_conf(img, label)
  File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 343, in main
    params_filename=params_filename)
  File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 367, in <module>
    main(use_cuda=use_cuda, nn_type=predict)
C++ Callstacks: 
CUDNN_STATUS_INTERNAL_ERROR at [/paddle/paddle/fluid/platform/device_context.cc:217]
PaddlePaddle Call Stacks: 
0       0x7fc37d794ad0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fc37d794e49p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fc37f773204p paddle::platform::CudnnHolder::CudnnHolder(CUstream_st* const*, paddle::platform::CUDAPlace const&) + 996
3       0x7fc37f7734d0p
4       0x7fc3da4b4a99p
5       0x7fc37f77274bp paddle::platform::CUDADeviceContext::cudnn_holder() const + 91
6       0x7fc37f772779p paddle::platform::CUDADeviceContext::cudnn_handle() const + 9
7       0x7fc37dbaffdcp paddle::platform::CanCUDNNBeUsed(paddle::framework::ExecutionContext const&) + 204
8       0x7fc37dbabf5bp paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 219
9       0x7fc37f6fb02bp paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 235
10      0x7fc37f6fd198p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 728
11      0x7fc37f6fd411p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
12      0x7fc37f6faa0cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
13      0x7fc37d92146ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
14      0x7fc37d92450fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
15      0x7fc37d785f8dp
16      0x7fc37d7c7936p
17      0x7fc3da80f187p PyEval_EvalFrameEx + 28695
18      0x7fc3da8116a9p PyEval_EvalCodeEx + 2025
19      0x7fc3da80eb78p PyEval_EvalFrameEx + 27144
20      0x7fc3da8116a9p PyEval_EvalCodeEx + 2025
21      0x7fc3da80eb78p PyEval_EvalFrameEx + 27144
22      0x7fc3da8116a9p PyEval_EvalCodeEx + 2025
23      0x7fc3da80eb78p PyEval_EvalFrameEx + 27144
24      0x7fc3da8116a9p PyEval_EvalCodeEx + 2025
25      0x7fc3da80eb78p PyEval_EvalFrameEx + 27144
26      0x7fc3da8116a9p PyEval_EvalCodeEx + 2025
27      0x7fc3da8118cap PyEval_EvalCode + 26
28      0x7fc3da82aa3dp
29      0x7fc3da82bbb8p PyRun_FileExFlags + 120
30      0x7fc3da82cdd8p PyRun_SimpleFileExFlags + 232
31      0x7fc3da83efecp Py_Main + 2972
32      0x7fc3d99ec830p __libc_start_main + 240
33      0x56523a2ef07fp


Process finished with exit code 1

```

**Comment by heavengate** [comment]
您好，请问报什么错呢，方便把错误信息张贴一下么

**Comment by heavengate** [comment]
错误原因是 CUDNN_STATUS_INTERNAL_ERROR
请尝试
```
sudo rm -rf ~/.nv
export CUDA_VISIBLE_DEVICES=0
```

https://blog.csdn.net/u014176855/article/details/80994991

**Comment by yangninghua** [comment]
恩恩，解决了，是按照你说的意思，
export CUDA_VISIBLE_DEVICES=0
或者
CUDA_VISIBLE_DEVICES=0 python test.py

**Comment by ResearchingDexter** [comment]
> 您好，paddle1.4.1 python3.6 cuda9.0 cudnn7.5.1可以，
> paddle1.5.1 python2.7 cuda9.0 cuddn7.5就不行了
> 
> ```
> W0730 14:55:33.858399 10216 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0
> W0730 14:55:33.860632 10216 device_context.cc:267] device: 0, cuDNN Version: 7.5.
> Traceback (most recent call last):
>   File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 367, in <module>
>     main(use_cuda=use_cuda, nn_type=predict)
>   File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 343, in main
>     params_filename=params_filename)
>   File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 212, in train
>     fetch_list=[avg_loss, acc])
>   File "/home/spple/anaconda3/envs/paddle1_5_1--py2_7--cuda9_0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 651, in run
>     use_program_cache=use_program_cache)
>   File "/home/spple/anaconda3/envs/paddle1_5_1--py2_7--cuda9_0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 749, in _run
>     exe.run(program.desc, scope, 0, True, True, fetch_var_name)
> paddle.fluid.core_avx.EnforceNotMet: Invoke operator conv2d error.
> Python Callstacks: 
>   File "/home/spple/anacona3/envs/paddle1_5_1--py2_7--cuda9_0/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1771, in append_op
>     attrs=kwargs.get("attrs", None))
>   File "/home/spple/anaconda3/envs/paddle1_5_1--py2_7--cuda9_0/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
>     return self.main_program.current_block().append_op(*args, **kwargs)
>   File "/home/spple/anaconda3/envs/paddle1_5_1--py2_7--cuda9_0/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2181, in conv2d
>     'fuse_relu_before_depthwise_conv': False
>   File "/home/spple/paddle/paddle_backbone/paddlecv/models/shufflenet_v2.py", line 115, in conv_bn_layer
>     bias_attr=False)
>   File "/home/spple/paddle/paddle_backbone/paddlecv/models/shufflenet_v2.py", line 68, in net
>     conv1 = self.conv_bn_layer(input=input, filter_size=3, num_filters=input_channel, padding=1, stride=2,name='stage1_conv')
>   File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 76, in pre_train_10class
>     prediction = paddlecv.get_model("shufflenetv2").net(input=img, class_dim=10)
>   File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 159, in train
>     prediction, avg_loss, acc = net_conf(img, label)
>   File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 343, in main
>     params_filename=params_filename)
>   File "/home/spple/paddle/paddle_backbone/paddle_demo3.py", line 367, in <module>
>     main(use_cuda=use_cuda, nn_type=predict)
> C++ Callstacks: 
> CUDNN_STATUS_INTERNAL_ERROR at [/paddle/paddle/fluid/platform/device_context.cc:217]
> PaddlePaddle Call Stacks: 
> 0       0x7fc37d794ad0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
> 1       0x7fc37d794e49p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
> 2       0x7fc37f773204p paddle::platform::CudnnHolder::CudnnHolder(CUstream_st* const*, paddle::platform::CUDAPlace const&) + 996
> 3       0x7fc37f7734d0p
> 4       0x7fc3da4b4a99p
> 5       0x7fc37f77274bp paddle::platform::CUDADeviceContext::cudnn_holder() const + 91
> 6       0x7fc37f772779p paddle::platform::CUDADeviceContext::cudnn_handle() const + 9
> 7       0x7fc37dbaffdcp paddle::platform::CanCUDNNBeUsed(paddle::framework::ExecutionContext const&) + 204
> 8       0x7fc37dbabf5bp paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 219
> 9       0x7fc37f6fb02bp paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 235
> 10      0x7fc37f6fd198p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 728
> 11      0x7fc37f6fd411p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
> 12      0x7fc37f6faa0cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
> 13      0x7fc37d92146ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
> 14      0x7fc37d92450fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
> 15      0x7fc37d785f8dp
> 16      0x7fc37d7c7936p
> 17      0x7fc3da80f187p PyEval_EvalFrameEx + 28695
> 18      0x7fc3da8116a9p PyEval_EvalCodeEx + 2025
> 19      0x7fc3da80eb78p PyEval_EvalFrameEx + 27144
> 20      0x7fc3da8116a9p PyEval_EvalCodeEx + 2025
> 21      0x7fc3da80eb78p PyEval_EvalFrameEx + 27144
> 22      0x7fc3da8116a9p PyEval_EvalCodeEx + 2025
> 23      0x7fc3da80eb78p PyEval_EvalFrameEx + 27144
> 24      0x7fc3da8116a9p PyEval_EvalCodeEx + 2025
> 25      0x7fc3da80eb78p PyEval_EvalFrameEx + 27144
> 26      0x7fc3da8116a9p PyEval_EvalCodeEx + 2025
> 27      0x7fc3da8118cap PyEval_EvalCode + 26
> 28      0x7fc3da82aa3dp
> 29      0x7fc3da82bbb8p PyRun_FileExFlags + 120
> 30      0x7fc3da82cdd8p PyRun_SimpleFileExFlags + 232
> 31      0x7fc3da83efecp Py_Main + 2972
> 32      0x7fc3d99ec830p __libc_start_main + 240
> 33      0x56523a2ef07fp
> 
> 
> Process finished with exit code 1
> ```



> 错误原因是 CUDNN_STATUS_INTERNAL_ERROR
> 请尝试
> 
> ```
> sudo rm -rf ~/.nv
> export CUDA_VISIBLE_DEVICES=0
> ```
> 
> https://blog.csdn.net/u014176855/article/details/80994991

我也是报一样的错误，不过我是单卡1060，然后尝试了这种方法，并不管用啊
