### ISSUE TITLE
在T4卡上预测出现CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by dancingpipi** [PaddlePaddle/Paddle#19134]
问题描述：我有一个fluid1.4的c++预测镜像，在P4上能够正常运行，迁移到T4机器上报CUDNN_STATUS_EXECUTION_FAILED错误
![image](https://user-images.githubusercontent.com/20511825/62848312-add2ab00-bd0d-11e9-81b5-57431e985c14.png)

fluid1.4编译信息：
  
![image](https://user-images.githubusercontent.com/20511825/62848369-f25e4680-bd0d-11e9-9ec2-0f0cdfa3a4f3.png)

P4机器信息：
  显卡：P4
  宿主机驱动：410
  宿主机CUDA：10.0
  
![image](https://user-images.githubusercontent.com/20511825/62848423-381b0f00-bd0e-11e9-8eba-49956229db12.png)

T4机器信息：
  显卡：T4
  宿主机驱动：418
  宿主机CUDA：10.1
  
![image](https://user-images.githubusercontent.com/20511825/62848413-25a0d580-bd0e-11e9-9dfd-8ff2da31ffaa.png)

**Comment by NHZlX** [comment]
![image](https://user-images.githubusercontent.com/5595332/62848622-0ce4ef80-bd0f-11e9-91b5-7f3f0059150c.png)
1.4的lib cuda 的版本是9.0么

**Comment by dancingpipi** [comment]
> ![image](https://user-images.githubusercontent.com/5595332/62848622-0ce4ef80-bd0f-11e9-91b5-7f3f0059150c.png)
> 1.4的lib cuda 的版本是9.0么

是的

**Comment by NHZlX** [comment]
需要在p4下编译cuda10版本的paddle lib， 然后放到t4下运行即可

**Comment by dancingpipi** [comment]
> 需要在p4下编译cuda10版本的paddle lib， 然后放到t4下运行即可

@NHZlX 
在P4下重新编译了cuda10版本的paddle lib，在T4上运行依旧报这个错误
![image](https://user-images.githubusercontent.com/20511825/66389476-087d4000-e9fb-11e9-84ab-5b93ba2ae6be.png)

于是想到在T4上编译cuda10版本，发现编译的时候报这个错误：
![image](https://user-images.githubusercontent.com/20511825/66389514-2c408600-e9fb-11e9-8f3d-6666e5342bae.png)

请问下如何正常的在T4上运行paddle c++呢

**Comment by dancingpipi** [comment]
> > 需要在p4下编译cuda10版本的paddle lib， 然后放到t4下运行即可
> 
> @NHZlX
> 在P4下重新编译了cuda10版本的paddle lib，在T4上运行依旧报这个错误
> ![image](https://user-images.githubusercontent.com/20511825/66389476-087d4000-e9fb-11e9-84ab-5b93ba2ae6be.png)
> 
> 于是想到在T4上编译cuda10版本，发现编译的时候报这个错误：
> ![image](https://user-images.githubusercontent.com/20511825/66389514-2c408600-e9fb-11e9-8f3d-6666e5342bae.png)
> 
> 请问下如何正常的在T4上运行paddle c++呢

解决了，可能是我编译的时候没有设置好LD_LIBRARY_PATH的路径，重新编译就好了
