### ISSUE TITLE
[安装错误]paddle按照文档步骤安装，自检报错cudnn无法初始化

### ISSUE THREAD

**Issue by suntxy** [PaddlePaddle/Paddle#21917]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.2 GPU版本
    2）CPU：intel E5, 未使用CPU版本，没有其它库
    3）GPU：RTX2080ti，CUDA10.0和CUDNN7.6
    4）系统环境：Centos7.4, Python 3.6.3
- 补充:
CUDA_HOME: 环境变量为空
LD_LIBRARY_PATH: 环境变量为空
LIBRARY_PATH: 
/usr/lib/oracle/12.2/client64/lib:/usr/lib/oracle/12.2/client64/lib::/usr/local/cuda/lib64

- nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+================|
|   0  GeForce RTX 208...  Off  | 00000000:0B:00.0 Off |                  N/A |
| 36%   38C    P0     1W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=====================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

-nvcc -V
/usr/local/cuda/bin/nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

- 安装方式信息：
pip安装
- 复现信息：如为报错，请给出复现环境、复现步骤
使用 python3 进入python解释器，输入import paddle.fluid ，再输入 paddle.fluid.install_check.run_check()
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
paddle自检失败，显示cudnn无法初始化
```
Running Verify Fluid Program ... 
W1224 17:17:04.056841  2006 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.0, Runtime API Version: 10.0
W1224 17:17:04.063815  2006 device_context.cc:244] device: 0, cuDNN Version: 7.6.
/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 123, in run_check
    test_simple_exe()
  File "/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 119, in test_simple_exe
    exe0.run(startup_prog)
  File "/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 822, in _run_impl
    use_program_cache=use_program_cache)
  File "/root/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 899, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
3   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::alloc
text> > (), std::reference_wrapper<std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platfo
rm::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   std::__future_base::_Deferred_state<std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
7   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
8   paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
9   paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool)

----------------------
Error Message Summary:
----------------------
Error: Failed to create Cudnn handle in DeviceContext
  [CUDNN_STATUS_NOT_INITIALIZED] at (/paddle/paddle/fluid/platform/device_context.cc:282)

```

**Comment by yaoxuefeng6** [comment]
@JepsonWong

**Comment by JepsonWong** [comment]
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:LD_LIBRARY_PATH
试着设置一下环境变量试试

**Comment by suntxy** [comment]
> export LD_LIBRARY_PATH=/usr/local/cuda/lib64:LD_LIBRARY_PATH
> 试着设置一下环境变量试试

not working for me. 
the error message is: failed to create cudnn handle in deviceContext.
跟环境变量应该没有关系, tensorflow-gpu 和pytorch-gpu 都正常，只有paddle不行。

**Comment by hustwzq-nlp** [comment]
我也面临相同的问题：

Error: Failed to create Cudnn handle in DeviceContext
  [Hint: CUDNN_STATUS_NOT_INITIALIZED] at (/paddle/paddle/fluid/platform/device_context.cc:283)

tensorflow-gpu 和pytorch-gpu 都正常，只有paddle不行。

**Comment by JepsonWong** [comment]
> 我也面临相同的问题：
> 
> Error: Failed to create Cudnn handle in DeviceContext
> [Hint: CUDNN_STATUS_NOT_INITIALIZED] at (/paddle/paddle/fluid/platform/device_context.cc:283)
> 
> tensorflow-gpu 和pytorch-gpu 都正常，只有paddle不行。

可能是cuda/cudnn的环境变量没有设好，CUDA_HOME、LD_LIBRARY_PATH、LIBRARY_PATH 、PATH环境变量输出来看看。

**Comment by hustwzq-nlp** [comment]
> > 我也面临相同的问题：
> > Error: Failed to create Cudnn handle in DeviceContext
> > [Hint: CUDNN_STATUS_NOT_INITIALIZED] at (/paddle/paddle/fluid/platform/device_context.cc:283)
> > tensorflow-gpu 和pytorch-gpu 都正常，只有paddle不行。
> 
> 可能是cuda/cudnn的环境变量没有设好，CUDA_HOME、LD_LIBRARY_PATH、LIBRARY_PATH 、PATH环境变量输出来看看。

重装cudnn就解决了，可能tensorflow和paddle调用cudnn的方式不同，个人猜测tensorflow是通过python包使用cudnn

**Comment by ucas010** [comment]
have the same problem
卸载重装根本不行。
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```
cudnn
`libcudnn7-dev_7.6.5.32-1+cuda10.0_amd64.deb`

py3.7
tf，torch都没有问题

**Comment by hustwzq-nlp** [comment]
按Nvidia官方文档的方式重装cudnn试试

**Comment by hustwzq-nlp** [comment]
> have the same problem
> 卸载重装根本不行。
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2018 NVIDIA Corporation
> Built on Sat_Aug_25_21:08:01_CDT_2018
> Cuda compilation tools, release 10.0, V10.0.130
> ```
> 
> cudnn
> `libcudnn7-dev_7.6.5.32-1+cuda10.0_amd64.deb`
> 
> py3.7
> tf，torch都没有问题

按Nvidia官方文档的方式重装cudnn试试

**Comment by suntxy** [comment]
BUG Resolved.
Nvidia官方文档安装cudnn的方式有多种，一种是下载安装包解压到指定目录，路径写入环境变量，这种方法安装的驱动paddle无法调用。
另一种是rpm/deb包的安装方式，不用手动指定安装路径环境变量，通过此方式安装能够解决该问题。
不太清楚paddle调用cudnn的具体方式，相比之下paddle的健壮性可能还比不上tf和pytorch，希望国产框架的细节能再完善一些。

**Comment by tianshuo78520a** [comment]
非常感谢您的提问，我们已经复现并提[PR25175](https://github.com/PaddlePaddle/Paddle/pull/25175)解决该问题。

请问您在执行检测的时候有提示这句么？
![image](https://user-images.githubusercontent.com/29832297/85487865-f29ec200-b5ff-11ea-9c3c-e1607c810f57.png)

**Comment by tianshuo78520a** [comment]
目前已经解决该问题，如果您还有其他问题可以再打开issues.

**Comment by zhhezhhe** [comment]
还是有这个问题，怎么解决呢？cudnn环境pytorch没问题
