### ISSUE TITLE
centos7 cuda10. 0环境下安装paddlepaddle-gpu成功后调用出现异常

### ISSUE THREAD

**Issue by gekie** [PaddlePaddle/Paddle#24289]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu 1.7.2.post107 
    2）CPU：Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    3）GPU：GeForce GTX 1070 Ti
    4）系统环境：CentOS Linux release 7.6.1810 (Core)、Python 3.7.7
- 安装方式信息：
1）conda install paddlepaddle-gpu cudatoolkit=10.0

- 复现信息：
使用python进入python解释器，
输入import paddle.fluid，
再输入 paddle.fluid.install_check.run_check()
异常：
`>>> paddle.fluid.install_check.run_check()
Running Verify Paddle Program ... 
/data/projects/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/executor.py:789: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/projects/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/data/projects/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 120, in test_simple_exe
    exe0.run(startup_prog)
  File "/data/projects/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 790, in run
    six.reraise(*sys.exc_info())
  File "/data/projects/anaconda3/envs/paddle_env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/data/projects/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 785, in run
    use_program_cache=use_program_cache)
  File "/data/projects/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 838, in _run_impl
    use_program_cache=use_program_cache)
  File "/data/projects/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 912, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::CublasHandleHolder::CublasHandleHolder(CUstream_st*, cublasMath_t)
3   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
4   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
5   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
6   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
7   std::__future_base::_Deferred_state<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
8   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
9   paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
10  paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
11  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
12  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

----------------------
Error Message Summary:
----------------------
ExternalError: The cuBLAS library was not initialized. This is usually caused by an error in the CUDA Runtime API called by the cuBLAS routine, or an error in the hardware setup.
To correct: check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed.
  [Hint: CUBLAS_STATUS_NOT_INITIALIZED] at (/paddle/paddle/fluid/platform/cuda_helper.h:39)

>>> 
`

**Comment by DannyIsFunny** [comment]
你好，错误提示显示，是cuBLAS 库没有安装成功，请检查GPU CUDA环境是否安装正常

**Comment by gekie** [comment]
正常的，我一直用TF.gpu

**Comment by JepsonWong** [comment]
nvcc -V输出看看？
PATH、LD_LIBRARY_PATH环境变量输出来看看

**Comment by gekie** [comment]
> nvcc -V输出看看？
> PATH、LD_LIBRARY_PATH环境变量输出来看看

[root@localhost ~]# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
[root@localhost ~]# ^C
[root@localhost ~]# echo $PATH
/root/local/bin:/root/local/bin:/data/projects/anaconda3/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/cuda/bin:/usr/local/phantomjs/bin:/tools/tools/bazel/output/:/usr/local/nginx/sbin/:/root/bin
[root@localhost ~]# 
[root@localhost ~]# echo $LD_LIBRARY_PATH
/usr/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/lib64:/tools/tools/rtmpdump/librtmp
[root@localhost ~]#

**Comment by JepsonWong** [comment]
麻烦nvidia-smi看看显卡驱动版本。

我给您提供一个测试程序，看看您那边执行会有什么问题呢？

```
//Example 1. Application Using C and CUBLAS: 1-based indexing
//-----------------------------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <cuda_runtime.h>
#include "cublas_v2.h"
#define M 6
#define N 5
#define IDX2F(i,j,ld) ((((j)-1)*(ld))+((i)-1))

static __inline__ void modify (cublasHandle_t handle, float *m, int ldm, int n, int p, int q, float alpha, float beta){
    cublasSscal (handle, n-q+1, &alpha, &m[IDX2F(p,q,ldm)], ldm);
    cublasSscal (handle, ldm-p+1, &beta, &m[IDX2F(p,q,ldm)], 1);
}

int main (void){
    cudaError_t cudaStat;    
    cublasStatus_t stat;
    cublasHandle_t handle;
    int i, j;
    float* devPtrA;
    float* a = 0;
    a = (float *)malloc (M * N * sizeof (*a));
    if (!a) {
        printf ("host memory allocation failed");
        return EXIT_FAILURE;
    }
    for (j = 1; j <= N; j++) {
        for (i = 1; i <= M; i++) {
            a[IDX2F(i,j,M)] = (float)((i-1) * M + j);
        }
    }
    cudaStat = cudaMalloc ((void**)&devPtrA, M*N*sizeof(*a));
    if (cudaStat != cudaSuccess) {
        printf ("device memory allocation failed");
        return EXIT_FAILURE;
    }
    stat = cublasCreate(&handle);
    if (stat != CUBLAS_STATUS_SUCCESS) {
        printf ("CUBLAS initialization failed\n");
        return EXIT_FAILURE;
    }
    stat = cublasSetMatrix (M, N, sizeof(*a), a, M, devPtrA, M);
    if (stat != CUBLAS_STATUS_SUCCESS) {
        printf ("data download failed");
        cudaFree (devPtrA);
        cublasDestroy(handle);
        return EXIT_FAILURE;
    }
    modify (handle, devPtrA, M, N, 2, 3, 16.0f, 12.0f);
    stat = cublasGetMatrix (M, N, sizeof(*a), devPtrA, M, a, M);
    if (stat != CUBLAS_STATUS_SUCCESS) {
        printf ("data upload failed");
        cudaFree (devPtrA);
        cublasDestroy(handle);        
        return EXIT_FAILURE;
    }    
    cudaFree (devPtrA);
    cublasDestroy(handle);
    for (j = 1; j <= N; j++) {
        for (i = 1; i <= M; i++) {
            printf ("%7.0f", a[IDX2F(i,j,M)]);
        }
        printf ("\n");
    }
    free(a);
    return EXIT_SUCCESS;
}
```

1. 程序保存为test.cu文件
2. 编译: nvcc test.cu -o test -lcublas -std=c++11
3. 执行: ./test

**Comment by gjwei** [comment]
你好 请问这个问题你解决了吗？我也遇到了相同的问题，试过pip和conda安装，都会报相同问题

**Comment by tianshuo78520a** [comment]
安装下paddle最新版本1.8.1看看能否解决问题

**Comment by threefoldo** [comment]
I got the same error, solved it by using cuda-9.2. Not sure how to solve it with cuda-10.1, maybe upgrading the nvidia driver, which is version 418, latest version is 450.

**Comment by beizhengren** [comment]
@JepsonWong 

您好,我出现了同样的问题
我用的是cuda10.0

nvidia-smi结果如下:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|

```

用您提供的例子得到了输出:
```
      1      7     13     19     25     31
      2      8     14     20     26     32
      3   1728    180    252    324    396
      4    160     16     22     28     34
      5    176     17     23     29     35

```

**Comment by JepsonWong** [comment]
> @JepsonWong
> 
> 您好,我出现了同样的问题
> 我用的是cuda10.0
> 
> nvidia-smi结果如下:
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> ```
> 
> 用您提供的例子得到了输出:
> 
> ```
>       1      7     13     19     25     31
>       2      8     14     20     26     32
>       3   1728    180    252    324    396
>       4    160     16     22     28     34
>       5    176     17     23     29     35
> ```

您好，麻烦新开个issue吧，会有专人解决。

**Comment by w-sugar** [comment]
> 2\. nvcc test.cu -o test -lcublas -std=c++11

你好，我的输出是 device memory allocation failed，请问怎么解决？

**Comment by w-sugar** [comment]
@JepsonWong 
你好，我的输出是 device memory allocation failed，请问怎么解决？

**Comment by JepsonWong** [comment]
> @JepsonWong
> 你好，我的输出是 device memory allocation failed，请问怎么解决？

您好，麻烦新开个issue吧，会有专人解决。

**Comment by henuliulei** [comment]
同样的错误
