### ISSUE TITLE
paddle安装后验证报错

### ISSUE THREAD

**Issue by leo038** [PaddlePaddle/Paddle#24805]
报错信息：
Running Verify Fluid Program ...
W0529 03:50:54.755647 56933 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.0
W0529 03:50:54.756062 56933 dynamic_loader.cc:120] Can not find library: libcudnn.so. The process maybe hang. Please try to add the lib path to LD_LIBRARY_PATH.
W0529 03:50:54.756090 56933 dynamic_loader.cc:179] Failed to find dynamic library: libcudnn.so ( libcudnn.so: cannot open shared object file: No such file or directory )
 Please specify its path correctly using following ways:
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS.
 For instance, issue command: export LD_LIBRARY_PATH=...
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled.

安装信息： 
paddlepaddle-gpu==1.8.1.post107
CUDA版本：10.1
cudnn版本：7.6.5
Unbuntu  18.04   64位系统
环境变量LD_LIBRARY_PATH已设置，且设置的路径下有libcudnn.so文件

**Comment by wanghaoshuang** [comment]
方便贴下执行`env`后的结果么？

**Comment by leo038** [comment]
LD_LIBRARY_PATH=/usr/lcoal/cuda-10.1/lib64:
PATH=/home/xxx/.local/bin:/usr/local/cuda-10.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by leo038** [comment]
请问这是什么问题呢？

**Comment by wanghaoshuang** [comment]
`/usr/lcoal/cuda-10.1/lib64:`
lcoal -> local

**Comment by leo038** [comment]
谢谢， 已解决。
