### ISSUE TITLE
paddle在jetson nano上使用c++进行gpu推理时报错

### ISSUE THREAD

**Issue by wumeng2** [PaddlePaddle/Paddle#26099]
PaddlePaddle版本：**develop分支  commitID: 0dc485e6fe32248179a86db203d3a06c8f4d528c**       是你们仓库8月7号最后一次上传的代码
硬件信息： **jetson nano**   使用**jetpack 4.4 dp**包刷机，里面时**cuda10.2 cudnn8.0**
使用如下cmake命令可以成功编译，
cmake 命令：cmake .. \
  -DWITH_CONTRIB=OFF \
  -DWITH_MKL=OFF  \
  -DWITH_MKLDNN=OFF \
  -DWITH_TESTING=OFF \
  -DCMAKE_BUILD_TYPE=Release \
  -DON_INFER=ON \
  -DWITH_PYTHON=OFF \
  -DWITH_XBYAK=OFF  \
  -DWITH_GPU=ON  \
  -DWITH_NV_JETSON=ON

**但是在使用paddleocr时在gpu预测出现如下错误**
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

  Compile Traceback (most recent call last):
    File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))

    File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)

    File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1405, in conv2d
    "data_format": data_format,

    File "/paddle/PaddlePaddle/PaddleOCR/ppocr/modeling/backbones/rec_resnet_vd.py", line 156, in conv_bn_layer
    bias_attr=False)

    File "/paddle/PaddlePaddle/PaddleOCR/ppocr/modeling/backbones/rec_resnet_vd.py", line 258, in basic_block
    name=name + "_branch2a")

    File "/paddle/PaddlePaddle/PaddleOCR/ppocr/modeling/backbones/rec_resnet_vd.py", line 128, in __call__
    name=conv_name)

    File "/paddle/PaddlePaddle/PaddleOCR/ppocr/modeling/architectures/rec_model.py", line 99, in __call__
    conv_feas = self.backbone(inputs)

    File "/paddle/PaddlePaddle/PaddleOCR/tools/program.py", line 193, in build_export
    image, outputs = model(mode='export')

    File "tools/export_model.py", line 67, in main
    config, eval_program, startup_prog)

    File "tools/export_model.py", line 93, in <module>
    main()

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvFusionOpKernel<float>, paddle::operators::CUDNNConvFusionOpKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::CUDNNConvFusionOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
7   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
8   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
9   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  at (/home/py/Downloads/Paddle-develop/paddle/fluid/operators/fused/conv_fusion_op.cu:305)
  [operator < conv2d_fusion > error]
Aborted (core dumped)
谢谢！

**Comment by cryoco** [comment]
您好，cudnn8的支持还在内部测试阶段，尚未发布。可以用jetpack4.3刷机，或降级cudnn到7.6试一下。

**Comment by wumeng2** [comment]
> 您好，cudnn8的支持还在内部测试阶段，尚未发布。可以用jetpack4.3刷机，或降级cudnn到7.6试一下。

好的，我已经用jetpack4.3刷机了，请问有没有针对jetpack4.3编译好的paddle库，我这边编译太慢了，上次在jetpack4.4编译花了10多个小时，谢谢您！

**Comment by wumeng2** [comment]
> 您好，cudnn8的支持还在内部测试阶段，尚未发布。可以用jetpack4.3刷机，或降级cudnn到7.6试一下。

在jetpack4.3上编译时，出现error: base class ‘class nvinfer1::IPluginFactory’ has accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class PluginFactoryTensorRT : public nvinfer1::IPluginFactory,
但是在NvInfer.h头文件里没有看到class IPluginFactory这个类，改怎么解决，谢谢

**Comment by cryoco** [comment]
TRT的一些头文件中缺少虚析构函数，需要手动添加；如果不在NvInfer.h中，可能在NvInferRuntime.h中。
参考[这里](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/inference_improving/paddle_tensorrt_infer.html#paddle-tensorrt)的方式在对应的类中添加虚析构函数：
![image](https://user-images.githubusercontent.com/12407750/90075888-10032900-dd31-11ea-9288-9bae5963c0c1.png)

**Comment by lleesg** [comment]
同样的错误，更新到inference2.0rc也存在，请问问题解决了么？谢谢

**Comment by QQ39272490** [comment]
我也是这样错误
