### ISSUE TITLE
按照官方链接文档，无法正常检测通过，提示 **error code is libnvinfer.so: cannot open shared object file: No such file or directory**

### ISSUE THREAD

**Issue by houming818** [PaddlePaddle/Paddle#27783]
- 标题：按照官方链接文档，无法正常检测通过，提示 **error code is libnvinfer.so: cannot open shared object file: No such file or directory**。
- 版本、环境信息：
    1）PaddlePaddle版本：
![image](https://user-images.githubusercontent.com/5498826/95562081-3f42c780-0a4e-11eb-81a0-c101f70fe61f.png)

    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
![image](https://user-images.githubusercontent.com/5498826/95562159-5bdeff80-0a4e-11eb-8ad3-fed8693e616b.png)

    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
![image](https://user-images.githubusercontent.com/5498826/95563448-f7bd3b00-0a4f-11eb-80cf-a2cdb2e336c0.png)

    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
   系统：**Linux zn 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux**
   python3: **Python 3.8.5**
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
![image](https://user-images.githubusercontent.com/5498826/95563993-b711f180-0a50-11eb-8210-66474aeedb4c.png)

- 安装方式信息：
1）pip安装
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

**Comment by houming818** [comment]
已解决。
解决方案： 安装 **nvidia-tensorrt**
参考链接： https://developer.nvidia.com/nvidia-tensorrt-7x-download

**Comment by MRXLT** [comment]
你好，请问是在执行哪一篇文档的时候遇到问题的呢，如果需要的话我们会补充文档内容
