### ISSUE TITLE
Cublas error, CUBLAS_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by merlinarer** [PaddlePaddle/Paddle#28746]
标题：Ubuntu16下运行paddle报错：Cublas error, CUBLAS_STATUS_NOT_INITIALIZED
工程在实验室服务器上是正常运行的，但是搬运到云端服务器就报错了
报错详细如下：

`
W1119 15:24:59.834878 31914 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W1119 15:24:59.838302 31914 device_context.cc:260] device: 0, cuDNN Version: 7.6.
/root/anaconda3/lib/python3.8/site-packages/paddle/fluid/executor.py:1069: UserWarning: The following exception is not an EOF exception.
  warnings.warn(
Traceback (most recent call last):
  File "pdseg/train.py", line 499, in <module>
    main(args)
  File "pdseg/train.py", line 485, in main
    train(cfg)
  File "pdseg/train.py", line 245, in train
    exe.run(startup_prog)
  File "/root/anaconda3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/anaconda3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1056, in run
    return self._run_impl(
  File "/root/anaconda3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1146, in _run_impl
    return self._run_program(
  File "/root/anaconda3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1228, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
paddle.fluid.core_avx.EnforceNotMet: 
`

----------------------
C++ Call Stacks (More useful to developers):
----------------------

`
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::CublasHandleHolder::CublasHandleHolder(CUstream_st*, cublasMath_t)
3   paddle::platform::CUDAContext::CUDAContext(paddle::platform::CUDAPlace const&, paddle::platform::stream::Priority const&)
4   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
5   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
6   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
7   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
8   std::__future_base::_Deferred_state<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
9   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
10  paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
11  paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
12  paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
13  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
14  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)
`
----------------------
Error Message Summary:
----------------------
`
ExternalError:  Cublas error, CUBLAS_STATUS_NOT_INITIALIZED  at (/paddle/paddle/fluid/platform/cuda_helper.h:81)
`

服务器版本、环境信息：
   1）PaddlePaddle版本：paddlepaddle_gpu-1.8.5.post107-cp38
   2）GPU：CUDA和cudnn信息：NVIDIA-SMI 418.165.02   Driver Version: 418.165.02   CUDA Version: 10.1  cudnn 7.6.5.32
PATH\LD_LIBRARY_PATH\LD_LIBRARY_PATH如下
`
(base) root@hwcloud:~/code_dirs/merlin/datafountain_remote_sensing_seg/PaddleSeg# echo $PATH
/usr/local/cuda-10.1/bin:/root/anaconda3/bin:/root/anaconda3/bin:/root/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
(base) root@hwcloud:~/code_dirs/merlin/datafountain_remote_sensing_seg/PaddleSeg# echo $LD_LIBRARY_PATH
:/usr/local/cuda-10.1/lib64
(base) root@hwcloud:~/code_dirs/merlin/datafountain_remote_sensing_seg/PaddleSeg# echo $LD_LIBRARY_PATH
(base) root@hwcloud:~/code_dirs/merlin/datafountain_remote_sensing_seg/PaddleSeg# 
`
查看了以前的issue解决办法cuda是升级到10.1，但是环境原本就是10.1，请问我应该怎么去解决呢？

**Comment by merlinarer** [comment]
按照这个[博客](https://blog.csdn.net/qq451882471/article/details/106967942)给的方法，前面那个错误没有了，但是出现了另一个问题：

`
W1119 16:15:50.915439  4527 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W1119 16:15:50.918889  4527 device_context.cc:260] device: 0, cuDNN Version: 7.6.
W1119 16:15:51.981369  4527 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1119 16:15:51.981395  4527 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1119 16:15:51.981400  4527 init.cc:231] The detail failure signal is:

W1119 16:15:51.981403  4527 init.cc:234] *** Aborted at 1605773751 (unix time) try "date -d @1605773751" if you are using GNU date ***
W1119 16:15:51.982908  4527 init.cc:234] PC: @                0x0 (unknown)
W1119 16:15:51.983001  4527 init.cc:234] *** SIGSEGV (@0x0) received by PID 4527 (TID 0x7f16199b5700) from PID 0; stack trace: ***
W1119 16:15:51.984321  4527 init.cc:234]     @     0x7f161959b390 (unknown)
W1119 16:15:51.985603  4527 init.cc:234]     @                0x0 (unknown)
Segmentation fault (core dumped)
`

这个给的信息很少，是什么原因呢？

**Comment by zhwesky2010** [comment]
@merlinarer 您好，你本机环境是CUDA10.1，Paddle装的是CUDA10.0的，能否把云端服务器上的10.1换成10.0。或者可以试试2.0的新发布的10.1的Paddle版本，``` python -m pip install paddlepaddle-gpu==2.0.0rc0.post101 -f https://paddlepaddle.org.cn/whl/stable.html```

**Comment by zhwesky2010** [comment]
@merlinarer 麻烦用nvcc --version，看下本机CUDA版本

**Comment by merlinarer** [comment]
> @merlinarer 麻烦用nvcc --version，看下本机CUDA版本

cuda已经降到10.0了
`
(base) root@hwcloud:/usr/local# cat /usr/local/cuda/version.txt 
CUDA Version 10.0.130
`
但是依然报错，错误是一样的

另外
`
fluid.install_check.run_check()
`
的时候会一直卡在多GPU测试阶段
![image](https://user-images.githubusercontent.com/71754029/99763118-00b42880-2b35-11eb-927d-bcfae6c4f745.png)
测试说明单GPU是OK的，但是只用单卡跑依然报错，错误一致

**Comment by merlinarer** [comment]
具体原因不清楚，最后通过安装docker,用docker的cuda环境解决了，谢谢

**Comment by renoyuan** [comment]
[Hint: 'CUBLAS_STATUS_NOT_INITIALIZED'.  The cuBLAS library was not initialized. This is usually caused by the lack of a prior cublasCreate() call, an error in the CUDA Runtime API called by the cuBLAS routine, or an error in the hardware setup.  To correct: call cublasCreate() prior to the function call; and check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed.  ] (at /paddle/paddle/fluid/platform/cuda_helper.h:98 遇到了一樣的問題兒

**Comment by AIg-Lid** [comment]
> [Hint: 'CUBLAS_STATUS_NOT_INITIALIZED'. The cuBLAS library was not initialized. This is usually caused by the lack of a prior cublasCreate() call, an error in the CUDA Runtime API called by the cuBLAS routine, or an error in the hardware setup. To correct: call cublasCreate() prior to the function call; and check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed. ] (at /paddle/paddle/fluid/platform/cuda_helper.h:98 遇到了一樣的問題兒

+1
