### ISSUE TITLE
WARNING:root:You are using GPU version Paddle Fluid, But Your CUDA Device is not set properly

### ISSUE THREAD

**Issue by shinianzhihou** [PaddlePaddle/Paddle#29353]
nvidia-smi：

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  TITAN RTX           Off  | 00000000:1A:00.0 Off |                  N/A |
| 41%   28C    P8    16W / 280W |      0MiB / 24220MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  TITAN RTX           Off  | 00000000:1B:00.0 Off |                  N/A |
| 41%   26C    P8    16W / 280W |      0MiB / 24220MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  TITAN RTX           Off  | 00000000:3D:00.0 Off |                  N/A |
| 40%   25C    P8    17W / 280W |      0MiB / 24220MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  TITAN RTX           Off  | 00000000:3E:00.0 Off |                  N/A |

```

nvcc -V

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

```
cat /usr/local/cuda/version.txt
CUDA Version 10.0.130

```

```
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
```
paddle安装
pip install paddlepaddle-gpu==1.8.5.post107 -i https://mirror.baidu.com/pypi/simple

报错信息：

```
WARNING:root:You are using GPU version Paddle Fluid, But Your CUDA Device is not set properly
 Original Error is 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GetCUDADeviceCount()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(30), unknown error.
  [Advise: This indicates that an unknown internal error has occurred. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:65)

0
```
望解答

**Comment by qingqing01** [comment]
@shinianzhihou 看样子是CUDA环境有点问题，你跑其他CUDA示例感觉也会不正确。设置下 CUDA_VISIBLE_DEVICES 试下呢。

**Comment by shinianzhihou** [comment]
![image](https://user-images.githubusercontent.com/29772895/101126024-92439000-3635-11eb-8ef3-c0caa5d5082e.png)
![image](https://user-images.githubusercontent.com/29772895/101126210-fa927180-3635-11eb-8875-a2d2d45877ad.png)
您好，这样都不行

**Comment by shinianzhihou** [comment]
> @shinianzhihou 看样子是CUDA环境有点问题，你跑其他CUDA示例感觉也会不正确。设置下 CUDA_VISIBLE_DEVICES 试下呢。

你好，我用其他程序搜集到的环境信息如下：

Collecting environment information...
PyTorch version: 1.2.0
Is debug build: False
CUDA used to build PyTorch: 10.0.130
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: TITAN RTX
GPU 1: TITAN RTX
GPU 2: TITAN RTX
GPU 3: TITAN RTX
GPU 4: TITAN RTX
GPU 5: TITAN RTX
GPU 6: TITAN RTX
GPU 7: TITAN RTX

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0a0
[conda] _pytorch_select           0.2                       gpu_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
[conda] cudatoolkit               10.0.130                      0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2020.2                      256    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.3.0            py36he904b0f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.19.4           py36h8732dcd_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] pytorch                   1.2.0           cuda100py36h938c94c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] torchvision               0.4.0           cuda100py36hecfc37a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by qingqing01** [comment]
@shinianzhihou 

能否先测试下CUDA环境是否正确:

test_cuda.cpp

```c++
#include <iostream>
#include <cuda_runtime_api.h>

bool InitCUDA() {
    int count;
    cudaGetDeviceCount(&count);//获得cuda设备的数量
    if(count == 0) {
        std::cout<<"There is no device.\n" ;
        return false;
    }
    int i;
    for(i = 0; i < count; i++) {
        cudaDeviceProp prop;//cuda设备属性对象
        if(cudaGetDeviceProperties(&prop, i) == cudaSuccess) {
            std::cout<<"设备名称："<<prop.name<<"\n" ;
            std::cout<<"计算能力的主代号："<<prop.major<<"\t"<<"计算能力的次代号："<<prop.minor<<"\n" ;
            std::cout<<"时钟频率："<<prop.clockRate<<"\n" ;
            std::cout<<"设备上多处理器的数量："<<prop.multiProcessorCount<<"\n" ;
            std::cout<<"GPU是否支持同时执行多个核心程序:"<<prop.concurrentKernels<<"\n" ;
        }
    }
    cudaSetDevice(i);//启动设备
    return true;
}

int main() {
    if(!InitCUDA()){
        return 0;
    }
    std::cout<<"cuda配置成功！\n" ;
    return 0;
}
```

编译:

```
nvcc -o test_cuda test_cuda.cpp
```

运行看下是否有输出信息:

```
./test_cuda
```

**Comment by majintao1994** [comment]
你好，我也遇到类似问题，但是cuda正常，测试代码也通过了
![微信图片_20201208110202](https://user-images.githubusercontent.com/38645277/101441028-1a39da80-3953-11eb-90c9-6b897d6eb741.png)
![微信图片_20201208110221](https://user-images.githubusercontent.com/38645277/101441034-202fbb80-3953-11eb-8d4f-43f126e84acd.png)
![cw](https://user-images.githubusercontent.com/38645277/101441045-26259c80-3953-11eb-860b-5f8c0f86c16e.png)

**Comment by xxxpsyduck** [comment]
@majintao1994 Can you uninstall current paddle-gpu version and try again with 2.0-rc1 version?

**Comment by jey07** [comment]
I am getting similar issue while running through google collab. Google collab has cuda version -10.1  but  for some reason it is not working

![image](https://user-images.githubusercontent.com/13083382/107022908-f1578980-67cb-11eb-8be8-bfb776890765.png)

![image](https://user-images.githubusercontent.com/13083382/107023118-2fed4400-67cc-11eb-92dd-18f9cc6fc3d2.png)

Error while running inference model.

W0205 10:28:42.728031   528 init.cc:136] Compiled with WITH_GPU, but no GPU found in runtime.
/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py:298: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 187, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 144, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/content/gdrive/My Drive/Paddle_OCR/PaddleOCR/tools/infer/predict_det.py", line 98, in __init__
    args, 'det', logger)  # paddle.jit.load(args.det_model_dir)
  File "/content/gdrive/My Drive/Paddle_OCR/PaddleOCR/tools/infer/utility.py", line 135, in create_predictor
    predictor = inference.create_predictor(config)
OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:78)

**Comment by shinianzhihou** [comment]
重启电脑or服务器解决了我的问题～

**Comment by Mrfuhang** [comment]
> 

安装c++环境
