### ISSUE TITLE
The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly.

### ISSUE THREAD

**Issue by EvilCalf** [PaddlePaddle/Paddle#29428]
python 3.8.3
paddle 2.0.0rc0
cuda10.2 cudnn 7.6.5 已经复制进去
但依然说没有cudnn

**Comment by guoshengCS** [comment]
Windows环境是否有试过`set PATH=XXX;%PATH%`呢

**Comment by EvilCalf** [comment]
还没有set PATH是加入什么

**Comment by EvilCalf** [comment]
> Windows环境是否有试过`set PATH=XXX;%PATH%`呢

还没有，set PATH是加入什么进去

**Comment by EvilCalf** [comment]
> Windows环境是否有试过`set PATH=XXX;%PATH%`呢

我把cuda bin lib等都SET PATH进去了，依然不行

**Comment by jianxieb** [comment]
你好，我遇到了同样的问题，请问你解决了吗？

**Comment by severous** [comment]
cuda10.1 cudnn8.x(具体版本忘了)paddle2.0.2.post101也有这个问题，不知道大家解决了吗

**Comment by yuhao910716** [comment]
我也有相同的bug 环境都配了。就是不好用。百度太坑了

**Comment by geoexploring** [comment]
环境都配置好后，重启就可以解决了。

**Comment by burakpols** [comment]
ı had cudnn64_7.dll error. ı found cudnn64_8.dll on my cuda directory then renamed  it cudnn64_7.dll and fixed. Also  if you try it backup cudnn64_8.dll file.

**Comment by sjhsbhqf** [comment]
我估计是因为我的Cuda版本和当初安装的paddle有冲突。
所以我打算重装Paddle。



-------------------------------------


我已经解决了这个问题。

因为官方说由于我的显卡不支持安倍架构，建议我安装cuda10.2，因为计算更快。

所以我安装了这个版本。

但是，问题在于我之前在英伟达官网安装的cuda是11.1，所以并没办法兼容这个10.2。

最后，我给大家的建议是，要么重装paddle来适配已安装的cuda，要么再装一个cuda10.2来适配paddle。

温馨小提示：在通过pip指令安装paddle2.2的时候，并不会像torch一样，帮你把cudatoolkit安装完了。你需要自己去英伟达官网手动安装。

**Comment by xunyinzhe** [comment]
我也遇到同样的问题，把 'C:\Program Files\NVIDIA\CUDNN\v8.3\bin' 添加到环境变量PATH后，问题解决。

**Comment by Jiahuan-Long** [comment]
> ### **[burakpols](/burakpols) ** commented [on 10 Nov 2021](#issuecomment-964806100) •

you are right!

**Comment by cjsal95** [comment]
> ı had cudnn64_7.dll error. ı found cudnn64_8.dll on my cuda directory then renamed it cudnn64_7.dll and fixed. Also if you try it backup cudnn64_8.dll file.

you helped me! 😀

**Comment by GuanRainy** [comment]
> ı had cudnn64_7.dll error. ı found cudnn64_8.dll on my cuda directory then renamed it cudnn64_7.dll and fixed. Also if you try it backup cudnn64_8.dll file.

thanks
