### ISSUE TITLE
GPU使用时，内存、显存足够，但是会报内存不足的错误。

### ISSUE THREAD

**Issue by lyj0123** [PaddlePaddle/Paddle#29811]
环境：AiStudio 的 Notebook 运行模型。32G 显存，GPU环境。
报错如下：
Out of memory error on GPU 0. Cannot allocate 541.500244MB memory on GPU 0, available memory is only 8.625000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
. (at /paddle/paddle/fluid/imperative/tracer.cc:98)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

个人理解：环境为GPU环境，自己使用时将 batchsize 设置为 64 ，之前有成功运行，但是也遇到过相同的错误，当时解决方法是停止再重新启动 GPU。虽然可能还会遇到错误，但是一直试的话还是会成功执行。

疑问：GPU 环境的显存、内存命名显示是足够使用的，为什么有时候会报这种错误，命名有32GB的内存和显存，它为什么会报 “ available memory is only 8.625000MB. ” 这个错误？这个错误的意思个人理解是显存能够使用的只有 8.625MB 这明显与 32GB 的GPU环境不相符吧？

**Comment by lijianshe02** [comment]
可能是之前的任务虽然停止了，但是显存没有释放，导致任务再次运行的时候，显存不够的情况

**Comment by lyj0123** [comment]
> 
> 
> 可能是之前的任务虽然停止了，但是显存没有释放，导致任务再次运行的时候，显存不够的情况

但我是刚启动一个环境，之前并没有执行任务，我也尝试了Notebook中的中断任务再重启任务按钮，还是会报同样的错误。

这种现象是偶然性的发生，那我是不是可以理解成，上一个人使用这个GPU进行训练，它退出了，我在启动GPU环境的时候被分配到了这块GPU，但是我点击中断任务的时候并没有权利中断之前那个人的任务，导致了我运行的时候显存不足。如果是这种情况，我应该怎么处理才能去正常使用。比如在中断中输入什么命令，让所有任务终止，然后我在正常的去使用GPU。

**Comment by lmw0320** [comment]
@lyj0123 请问下，你的问题解决了没？我在使用模型进行预测的时候，也遇到了相同的问题。。

**Comment by lyj0123** [comment]
> 
> 
> @lyj0123 请问下，你的问题解决了没？我在使用模型进行预测的时候，也遇到了相同的问题。。

没有彻底性解决，个人理解：这是一个偶然性的问题。退出 GPU 使用，再尝试启动GPU（不是指notebook中的重启按钮，目的是换其他的GPU）。（PS：说白了就是看运气，你看我之前的那个回复，提了我的疑问，但是暂时还没有大佬给答疑，所以现在我也不知道是怎么彻底的解决），出现这个问题，并不是自己程序的问题，因为同样的程序，没有任何改动之前是可以成功运行的。

**Comment by lmw0320** [comment]
> > @lyj0123 请问下，你的问题解决了没？我在使用模型进行预测的时候，也遇到了相同的问题。。
> 
> 没有彻底性解决，个人理解：这是一个偶然性的问题。退出 GPU 使用，再尝试启动GPU（不是指notebook中的重启按钮，目的是换其他的GPU）。（PS：说白了就是看运气，你看我之前的那个回复，提了我的疑问，但是暂时还没有大佬给答疑，所以现在我也不知道是怎么彻底的解决），出现这个问题，并不是自己程序的问题，因为同样的程序，没有任何改动之前是可以成功运行的。

谢谢答复～～我昨天也是自己尝试了下，发现是一张图片引起的。。很是不懂。。我删除了该图片之后，就可以正常批量预测。。---而之前我使用1.8.5版本的飞桨时候，这张图片是可以正常检测的。。就是升级了飞桨版本之后，遇到了这个报错。。。

**Comment by 95579580** [comment]
这个问题我也遇到了，仔细查找，我找出了原因：确实是因为显存不够用了。
你应该调试的过程中去查看显存剩余容量，因为内存分配是动态变化的、逐渐增长的，当程序停止后就会释放掉。它说你只剩8MB，是应为已经分配出去了，不够下一次的分配了。如果你改变一下数据的处理量可能会看见不是8而是别的数值，下面是我调试一个程序时 通过  >nvidia-smi查看过的   
刚开始 395MiB /  4096MiB，
然后1305MiB /  4096MiB，
出错前 3317MiB /  4096MiB，
      ->>>>Out of memory error on GPU 0. Cannot allocate 196.000244MB memory on GPU 0, available memory is only 185.275001MB.
停止后 132MiB /  4096MiB。

so当程序停止后再去查看GPU ，确实不容易发现问题。
