### ISSUE TITLE
新版本2.0rc1安装cuda11.0出现兼容性问题

### ISSUE THREAD

**Issue by smartfridgeIoT** [PaddlePaddle/Paddle#29976]
新版本2.0rc1安装cuda11.0出现兼容性问题，
成功安装
python -m pip install paddlepaddle-gpu==2.0.0rc1.post110 -f https://paddlepaddle.org.cn/whl/stable.html      
显示如下，（显然没有正确找到cudnn64_8.dll,多次确认cuda和cudnn正确安装。pytorch安装正常。
>>> import paddle                                                                                                                                                                
>>> paddle.utils.run_check()                                                                                                                                                     Running verify PaddlePaddle program ...                                                                                                                                          W1229 10:38:07.253587  6852 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 3.0, Driver API Version: 11.0, Runtime API Version: 11.0                      W1229 10:38:07.253587  6852 dynamic_loader.cc:207] Note: [Recommend] copy cudnn into CUDA installation directory.                                                                 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,                                                                                   then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA/v10.0                                                                                         You should do this according to your CUDA installation directory and CUDNN version.                                                                                              Traceback (most recent call last):                                                                                                                                                 File "<stdin>", line 1, in <module>                                                                                                                                              File "D:\Development\DesignParks\py387\lib\site-packages\paddle\utils\install_check.py", line 164, in run_check                                                                    _run_static_single(use_cuda)                                                                                                                                                   File "D:\Development\DesignParks\py387\lib\site-packages\paddle\utils\install_check.py", line 96, in _run_static_single                                                            exe.run(startup_prog)                                                                                                                                                          File "D:\Development\DesignParks\py387\lib\site-packages\paddle\fluid\executor.py", line 1108, in run                                                                              six.reraise(*sys.exc_info())                                                                                                                                                   File "D:\Development\DesignParks\py387\lib\site-packages\six.py", line 703, in reraise                                                                                             raise value                                                                                                                                                                    File "D:\Development\DesignParks\py387\lib\site-packages\paddle\fluid\executor.py", line 1096, in run                                                                              return self._run_impl(                                                                                                                                                         File "D:\Development\DesignParks\py387\lib\site-packages\paddle\fluid\executor.py", line 1228, in _run_impl                                                                        return self._run_program(                                                                                                                                                      File "D:\Development\DesignParks\py387\lib\site-packages\paddle\fluid\executor.py", line 1325, in _run_program                                                                     self._default_executor.run(program.desc, scope, 0, True, True,                                                                                                               RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)                        
 Suggestions:                                                                                                                                                                     
1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.                               
2.  2. Configure third-party dynamic library environment variables as follows:                                                                                                       - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`                                                                                                                     - Windows: set PATH by `set PATH=XXX; (at D:\2.0.0rc1\paddle\paddle\fluid\platform\dynload\dynamic_loader.cc:234)

**Comment by zhwesky2010** [comment]
@smartfridgeIoT 您好，请问cudnn拷贝到了CUDA的安装路径了吗？比如C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0中，还有CUDA的安装路径已经设置在环境变量了吗？这个问题应该是安装了 但是系统没有找到正确的路径加载成功

**Comment by zhwesky2010** [comment]
@smartfridgeIoT 可以把cudnn64_8.dll直接拷出来看下

**Comment by smartfridgeIoT** [comment]
显然是rc1版在瘟都死系统下的兼容问题。
1、使用cuda10.2+cuDNN7.6.5 for Cuda10.2, 没有问题。贪新版本就换了cuda11.0+cuDNN8.0 就搞成这呀子了。没试验在linux下的状况，应该阔以的。
2. 同样的环境，tensorflow-gpu 2.4.0 OK，我的算力3.0，老牛了，所以tensorflow不启动，他要3.5，那么我不用就好。
3. 使用pytorch，
>>> import torch
>>> torch.cuda.is_available()
True
4.   C:\Users\north>nvidia-smi
+-----------------------------------------------------------------------------+                                        
 | NVIDIA-SMI 451.48       Driver Version: 451.48       CUDA Version: 11.0     |                                         
|-------------------------------+----------------------+----------------------+ 
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |                                         
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |                                         |===============================+======================+======================|                                         |   0  GeForce GT 630     WDDM  | 00000000:01:00.0 N/A |                  N/A |                                         
| 25%   39C    P8    N/A /  N/A |    271MiB /  2048MiB |     N/A      Default |                                         
+-------------------------------+----------------------+----------------------+                                                                                                                                                                 +-----------------------------------------------------------------------------+                                         
| Processes:                                                                  |                                         
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |                                        
|        ID   ID                                                   Usage      |                                         |=============================================================================|                                         |  No running processes found                                                 |                                         
+-----------------------------------------------------------------------------+

**Comment by zhwesky2010** [comment]
@smartfridgeIoT 您好，报错是这句 The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly，找不到 ``cudnn64_8.dll`` ，测试过是可以正常加载的，建议在终端看下环境变量 ``echo %PATH%`` 内容

**Comment by smartfridgeIoT** [comment]
问题已经诊断出来的，是硬件问题。 1.新显卡nvidia1650，算力7.5，cuda11.0+cudnn按照手册顺利pass。 2.老显卡gt630用455驱动，算力3.0，刚够paddlepaddle要求 ，不足tensorflow3.5的要求，显示如上问题。cuda11.0+cudnn8.0.4就找不到cudnn64_8.dll。换cuda10.1+cudnn7.6.5就可以完成paddle-gpu安装。 分析，cudnn从8.0开始就结构变了，老显卡驱动还会去加载老框架，未必是path设置不对找不到文件，而是加载文件失败，确定找不到文件了。使用cudnn7.6.5的就可以。 结论，老显卡优先采用cudnn7.6.5，因此cuda最高10.2，最佳10.1，这样可以同时支持tensorflow2.3.0，不支持tf2.4.0。在windows和ubuntu都测试过，结论相同。 用傻子安装，卸载，安装，卸载大法。paddlepaddle没问题。 谢谢。 hackphi 发自 网易邮箱大师 在2021年01月04日 22:13，Zhou Wei 写道： @smartfridgeIoT 您好，报错是这句 The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly，找不到 cudnn64_8.dll ，测试过是可以正常加载的，建议在终端看下环境变量 echo %PATH% 内容 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
