### ISSUE TITLE
【论文复现】OSError: (External)  Cuda error(9), invalid configuration argument.

### ISSUE THREAD

**Issue by lyl120117** [PaddlePaddle/Paddle#30947]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==2.0.0.post101

**复现StarGAN-v2加入FAN网络后训练报错，请帮忙看一下，谢谢**

**报错日志如下：**
Traceback (most recent call last):
  File "test_fan.py", line 444, in <module>
    loss_real = adv_loss(out, 1)
  File "test_fan.py", line 356, in adv_loss
    loss = F.binary_cross_entropy_with_logits(logits, targets)
  File "/home/ps/anaconda3/envs/paddle2.0_py37/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 286, in binary_cross_entropy_with_logits
    return core.ops.mean(out)
OSError: (External)  Cuda error(9), invalid configuration argument.
  [Advise: This indicates that a kernel launch is requesting resources that can never be satisfied by the current device. Requestingmore shared memory per block than the device supports will trigger this error, as will requesting too many threads or blocks.See cudaDeviceProp for more device limitations.] (at /paddle/paddle/fluid/operators/mean_op.cu:69)
  [operator < mean > error]

**代码见附件：**
[test_fan.py.zip](https://github.com/PaddlePaddle/Paddle/files/5938619/test_fan.py.zip)

**Comment by ZHUI** [comment]
您好，从报错信息来看，似乎是 mean op的问题，问题跟进中，有进展会马上反馈给您。

**Comment by lyl120117** [comment]
这个异常很奇怪，去掉masks = fan.get_heatmap(x_real)这行代码就可以正常运行，这行代码跟下面的代码没啥关联。

**Comment by ZHUI** [comment]
> 这个异常很奇怪，去掉masks = fan.get_heatmap(x_real)这行代码就可以正常运行，这行代码跟下面的代码没啥关联。

cuda kernel执行顺序不定，应该是之前发生了错误，mean op刚好catch到了这个错误，实际错误可能不在mean op。
可使用memcheck工具排查此类错误  `cuda-memcheck python test_fan.py` 。

目前对问题已经初步定位，已安排相应同学跟进。

**Comment by lyl120117** [comment]
@ZHUI @wangjiawei04 非常感谢提供cuda-memcheck方法定位问题，通过查找[NVIDIA官方文档](https://docs.nvidia.com/cuda/cuda-memcheck/#about-cuda-memcheck)，以及在代码中增加Debug日志，定位到了这个异常属于CUDA API errors，具体错误类型是cudaErrorInvalidConfiguration (error 9)，引起异常的代码在get_heatmap -> preprocess -> shift，shift函数有两个参数，当参数N为0时，如果用paddle提供的API操作就会出现上述异常，我把shift中的操作都换成numpy就可以正常运行了。上述是我分析的结果，希望对你们有帮助，再次感谢你们提供的支持。

**Comment by lyl120117** [comment]
经过更具体的定位，出现上述错误的原因是，paddle.arange这个API当传的参数为0会引起CUDA API errors，例如这样调用：paddle.arange(0)，同样的方法torch.arange(0)，不会引起CUDA API errors。

**Comment by ZHUI** [comment]
> 经过更具体的定位，出现上述错误的原因是，paddle.arange这个API当传的参数为0会引起CUDA API errors，例如这样调用：paddle.arange(0)，同样的方法torch.arange(0)，不会引起CUDA API errors。

嗯嗯，辛苦了，之前我定位的也是 CUDARangeKernel 的错误，感谢您提供了更详细的反馈。 @wangjiawei04 同学可以依据这个反馈跟进、定位更具体的问题。

**Comment by lyl120117** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/6166692/108796907-d905ae00-75c4-11eb-8a5e-5983416020e5.png">
如上图所示，当paddle.arange(0)这样调用时grid=0，grid作为CUDA核函数参数如果为0就会出现CUDA API errors，range_op.cu的实现中由于没有像cudaGetLastError这样catch异常，程序不会在异常点立即停止执行，直到下一个mean op有catch操作发现到了异常导致程序停止运行，上述修改可以解决paddle.arange(0)调用导致CUDA API errors问题。
@ZHUI 如果您觉得上述修改有用的话我可以帮忙提一个PR，谢谢！

**Comment by bjjwwang** [comment]
感谢 我马上调研一下啊torch和tensorflow 关于这块的用法。 我到时候也参考下您的代码。

**Comment by lyl120117** [comment]
Paddle的代码这几天大致分析了一下，有两个大的问题，一个是核函数的第一个参数block，block最小值是1，最大值我看torch中的定义是65535，Paddle所有调用核函数的地方都没把block这个参数约束到一个合法的范围。另一个是异常处理机制的问题，核函数是委托给CUDA执行的，这部分是外部逻辑是有风险的，从程序设计的角度来讲，每一个核函数调用完后都应该调用cudaGetLastError这样的CUDA API来catch是否有异常，有异常应该立即停止程序，这样定位问题会更直观。

**Comment by ZHUI** [comment]
> Paddle的代码这几天大致分析了一下，有两个大的问题，一个是核函数的第一个参数block，block最小值是1，最大值我看torch中的定义是65535，Paddle所有调用核函数的地方都没把block这个参数约束到一个合法的范围。另一个是异常处理机制的问题，核函数是委托给CUDA执行的，这部分是外部逻辑是有风险的，从程序设计的角度来讲，每一个核函数调用完后都应该调用cudaGetLastError这样的CUDA API来catch是否有异常，有异常应该立即停止程序，这样定位问题会更直观。

嗯嗯，部分OP的CUDA调用不规范，这个确实是历史遗留问题。但因为涉及到的OP可能较多，统一修改的工作量大，可能后期需要专项工作来推动解决问题。非常感谢您的建议。

**Comment by zhangpu1211** [comment]
> > Paddle的代码这几天大致分析了一下，有两个大的问题，一个是核函数的第一个参数block，block最小值是1，最大值我看torch中的定义是65535，Paddle所有调用核函数的地方都没把block这个参数约束到一个合法的范围。另一个是异常处理机制的问题，核函数是委托给CUDA执行的，这部分是外部逻辑是有风险的，从程序设计的角度来讲，每一个核函数调用完后都应该调用cudaGetLastError这样的CUDA API来catch是否有异常，有异常应该立即停止程序，这样定位问题会更直观。
> 
> 嗯嗯，部分OP的CUDA调用不规范，这个确实是历史遗留问题。但因为涉及到的OP可能较多，统一修改的工作量大，可能后期需要专项工作来推动解决问题。非常感谢您的建议。

我也遇到了这个问题，但是不知道怎么改，https://github.com/PaddlePaddle/Paddle/issues/34561，请问什么时候可以修复呢

**Comment by Li-fAngyU** [comment]
我也遇到了这个问题，想问一下目前这个问题解决了吗？

**Comment by zhangpu1211** [comment]
您好，邮件已收到，我尽快给您回复。

**Comment by Li-fAngyU** [comment]
我出现这个问题是出现在执行下面这个代码片段的时候。
model.train()
for i in range(epoch):
      ''' 
      train_pred = model(train_data)
      '''
      model.eval()
      '''
      test_pred = model(test_data)
      '''
      model.train()

当我train_data 采用小batch的形式，test_data直接全部喂进去的时候就会出现这个问题。

我将test_data 也用dataloader的方式去作为模型的输入的时候就不会报这个错误。
希望能对解决这个问题有一点帮助。
