### ISSUE TITLE
Dataloader预处理将数据转成Tensor，num_workers大于0报错

### ISSUE THREAD

**Issue by lyl120117** [PaddlePaddle/Paddle#31371]
- PaddlePaddle 2.0.0
- Ubuntu 18.04
- Python 3.7

**Dataloader预处理将数据转成Tensor，num_workers大于0报错，num_workers==0不报错。**

```
2021-03-01 14:07:02,535 - ERROR - DataLoader reader thread raised an exception! 12952
Traceback (most recent call last):
  File "test_datasets.py", line 93, in <module>
    for i in loader():
  File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 791, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 633, in _thread_loop
    six.reraise(type(batch), batch)
  File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:274)

```

```
import numpy as np
from paddle.io import DataLoader, Dataset
import paddle


class DefaultDataset(Dataset):
    def __init__(self):
        self.samples = np.arange(1).astype('float32')

    def __getitem__(self, index):
        fname = self.samples[index]
        return paddle.to_tensor(fname)

    def __len__(self):
        return len(self.samples)


if __name__ == '__main__':
    dataset = DefaultDataset()
    loader = DataLoader(dataset, batch_size=1, collate_fn=None, num_workers=1, shuffle=False)
    for i in loader():
        print(i)
```

**Comment by zhiqiu** [comment]
谢谢反馈，已在https://github.com/PaddlePaddle/Paddle/pull/31177 中修复，计划将在2.1版本发布。

**Comment by lyl120117** [comment]
> 谢谢反馈，已在#31177 中修复，计划将在2.1版本发布。

您好，我这边用包含#31177这条PR的develop编译版本测试还是一样的报错，您可以用我上面的代码测试一下，谢谢！
```
========= Program hit cudaErrorInitializationError (error 3) due to "initialization error" on CUDA API call to cudaGetDevice. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x3c43a3]
=========     Host Frame:/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core_avx.so [0x745e070]
=========     Host Frame:/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core_avx.so (_ZN6paddle8platform18GetCurrentDeviceIdEv + 0x1b) [0x726bacb]
=========     Host Frame:/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core_avx.so [0x2581437]
=========     Host Frame:/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core_avx.so [0x2598099]
=========     Host Frame:/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core_avx.so [0x27481c3]
=========     Host Frame:/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core_avx.so [0x277d6fe]
=========     Host Frame:/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/core_avx.so [0x24723b7]
=========     Host Frame:python (_PyMethodDef_RawFastCallDict + 0x267) [0x13abe7]
=========     Host Frame:python (_PyCFunction_FastCallDict + 0x21) [0x13ad31]
=========     Host Frame:python (_PyObject_Call_Prepend + 0x63) [0x12ca03]
=========     Host Frame:python (PyObject_Call + 0x62) [0x1218d2]
=========     Host Frame:python [0x16fb0a]
=========     Host Frame:python (_PyObject_FastCallKeywords + 0x128) [0x178298]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x56e9) [0x1d4a79]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x115059]
=========     Host Frame:python (_PyFunction_FastCallDict + 0x1d4) [0x116134]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x1e1b) [0x1d11ab]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x5da) [0x11533a]
=========     Host Frame:python (_PyFunction_FastCallDict + 0x1d4) [0x116134]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x1e1b) [0x1d11ab]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x5da) [0x11533a]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0x387) [0x177307]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x6d6) [0x1cfa66]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x115059]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0x325) [0x1772a5]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x4ade) [0x1d3e6e]
=========     Host Frame:python (_PyFunction_FastCallDict + 0x10b) [0x11606b]
=========     Host Frame:python (_PyObject_FastCall_Prepend + 0x64) [0x12c964]
=========     Host Frame:python [0x16fc65]
=========     Host Frame:python (PyObject_GetItem + 0x49) [0x166779]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0xbef) [0x1cff7f]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x5da) [0x11533a]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0x387) [0x177307]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x6d6) [0x1cfa66]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0xbb9) [0x115919]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0x387) [0x177307]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x520) [0x1cf8b0]
=========     Host Frame:python (_PyFunction_FastCallDict + 0x10b) [0x11606b]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x1e1b) [0x1d11ab]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0xfb) [0x17707b]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x520) [0x1cf8b0]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0xfb) [0x17707b]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x520) [0x1cf8b0]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0xfb) [0x17707b]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x520) [0x1cf8b0]
=========     Host Frame:python (_PyFunction_FastCallDict + 0x10b) [0x11606b]
=========     Host Frame:python (_PyObject_Call_Prepend + 0x63) [0x12ca03]
=========     Host Frame:python [0x16faaa]
=========     Host Frame:python (_PyObject_FastCallKeywords + 0x128) [0x178298]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x4bc6) [0x1d3f56]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0xfb) [0x17707b]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x4ade) [0x1d3e6e]
=========     Host Frame:python (_PyFunction_FastCallKeywords + 0xfb) [0x17707b]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x4ade) [0x1d3e6e]
=========
2021-03-02 21:20:45,962 - ERROR - DataLoader reader thread raised an exception! 4276
Traceback (most recent call last):
  File "test_datasets.py", line 97, in <module>
    for i in loader():
  File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 798, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 640, in _thread_loop
    six.reraise(type(batch), batch)
  File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:274)
```

**Comment by lyl120117** [comment]
@zhiqiu 这个问题我已经分析好几天了，目前还没定位到root case，从现象上看，比较明确的是多进程导致CUDA异常，但是为啥多进程会出现Cuda error(3), initialization error这个异常还有待分析，我这边的系统是Ubuntu，Python默认多进程的创建方式是[fork](https://docs.python.org/zh-cn/3.7/library/multiprocessing.html)，我将多进程创建方式设置为spawn，代码也可以正常运行。
```
import numpy as np
from paddle.io import DataLoader, Dataset
import paddle
import multiprocessing


class DefaultDataset(Dataset):
    def __init__(self):
        self.samples = np.arange(1).astype('float32')

    def __getitem__(self, index):
        fname = self.samples[index]
        return paddle.to_tensor(fname)

    def __len__(self):
        return len(self.samples)


if __name__ == '__main__':
    multiprocessing.set_start_method('spawn')
    dataset = DefaultDataset()
    loader = DataLoader(dataset, batch_size=1, collate_fn=None, num_workers=1, shuffle=False)
    for i in loader():
        print(i)
```

**Comment by lyl120117** [comment]
https://github.com/pytorch/pytorch/issues/33754#issuecomment-590970751
https://github.com/PaddlePaddle/Paddle/issues/31259#issue-817144773

**Comment by zhiqiu** [comment]
> @zhiqiu 这个问题我已经分析好几天了，目前还没定位到root case，从现象上看，比较明确的是多进程导致CUDA异常，但是为啥多进程会出现Cuda error(3), initialization error这个异常还有待分析，我这边的系统是Ubuntu，Python默认多进程的创建方式是[fork](https://docs.python.org/zh-cn/3.7/library/multiprocessing.html)，我将多进程创建方式设置为spawn，代码也可以正常运行。
> 
> ```
> import numpy as np
> from paddle.io import DataLoader, Dataset
> import paddle
> import multiprocessing
> 
> 
> class DefaultDataset(Dataset):
>     def __init__(self):
>         self.samples = np.arange(1).astype('float32')
> 
>     def __getitem__(self, index):
>         fname = self.samples[index]
>         return paddle.to_tensor(fname)
> 
>     def __len__(self):
>         return len(self.samples)
> 
> 
> if __name__ == '__main__':
>     multiprocessing.set_start_method('spawn')
>     dataset = DefaultDataset()
>     loader = DataLoader(dataset, batch_size=1, collate_fn=None, num_workers=1, shuffle=False)
>     for i in loader():
>         print(i)
> ```

dataloader中子进程是fork出来的，子进程不会继承父进程的cuda runtime，所以你在子进程中不能用cuda的操作。你可以试下在#31177 的基础上，加上 with paddle.fluid.dygraph.guard(paddle.CPUPlace())中使用paddle的操作（这样跑的是cpu的op）。

**Comment by lyl120117** [comment]
@zhiqiu cuda runtime这个概念出自哪里？

**Comment by zhiqiu** [comment]
> @zhiqiu cuda runtime这个概念出自哪里？

![image](https://user-images.githubusercontent.com/6888866/109776452-8cae1400-7c3d-11eb-8a00-83e5235532bc.png)

https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038

和你上面的pytorch issue中说的cuda context的意思差不多。

**Comment by lyl120117** [comment]
```
上下文和启动方法
根据不同的平台， multiprocessing 支持三种启动进程的方法。这些 启动方法 有

spawn
父进程启动一个新的Python解释器进程。子进程只会继承那些运行进程对象的 run() 方法所需的资源。特别是父进程中非必须的文件描述符和句柄不会被继承。相对于使用 fork 或者 forkserver，使用这个方法启动进程相当慢。

可在Unix和Windows上使用。 Windows上的默认设置。

fork
父进程使用 os.fork() 来产生 Python 解释器分叉。子进程在开始时实际上与父进程相同。父进程的所有资源都由子进程继承。请注意，安全分叉多线程进程是棘手的。

只存在于Unix。Unix中的默认值。

forkserver
程序启动并选择* forkserver * 启动方法时，将启动服务器进程。从那时起，每当需要一个新进程时，父进程就会连接到服务器并请求它分叉一个新进程。分叉服务器进程是单线程的，因此使用 os.fork() 是安全的。没有不必要的资源被继承。

可在Unix平台上使用，支持通过Unix管道传递文件描述符。
```
这是[Python官方文档](https://docs.python.org/zh-cn/3.7/library/multiprocessing.html#contexts-and-start-methods)的解释，您说的fork出来的子进程不会继承父进程的cuda runtime，我的理解应该是父进程还没初始化cuda runtime就fork子进程了，那么我们是不是应该找到到底应该怎么初始化cuda runtime，spawn方式启动的进程到底跟fork在代码上哪里不一样，这个可能是我们需要搞清楚的吧！

**Comment by lyl120117** [comment]
@zhiqiu 您好，通过查看[CUDA Runtime API](https://docs.nvidia.com/cuda/archive/10.2/cuda-runtime-api/driver-vs-runtime-api.html#driver-vs-runtime-api)文档，在主进程中只要调用了CUDA Runtime API就会初始化cuda runtime，也就是Context，这个Context会跟当前进程绑定，Context在线程中可以共享，但是不能在进程中共享。Python采用fork的方式创建进程会拷贝父进程的所有资源，包括父进程中的Context，但是这个Context子进程是用不了的，子进程由于持有了Context，调用CUDA Runtime API就会直接使用已有的父进程继承过来的Context访问GPU，从而导致Cuda error(3), initialization error这个异常。spawn方式创建进程不会继承父进程的Context，子进程调用任意CUDA Runtime API会初始化cuda runtime，所以spawn方式创建的子进程可以正常运行。

**Comment by lyl120117** [comment]
@zhiqiu 在框架中可以判断当前进程创建的方式是fork还是spawn，如果是fork，需要提示用户不能在子进程也就是Dataloader预处理中调用CUDA相关的API比如paddle.to_tensor，或者提示用户使用spawn方式创建进程才可以调用CUDA相关API。

**Comment by zhiqiu** [comment]
> @zhiqiu 您好，通过查看[CUDA Runtime API](https://docs.nvidia.com/cuda/archive/10.2/cuda-runtime-api/driver-vs-runtime-api.html#driver-vs-runtime-api)文档，在主进程中只要调用了CUDA Runtime API就会初始化cuda runtime，也就是Context，这个Context会跟当前进程绑定，Context在线程中可以共享，但是不能在进程中共享。Python采用fork的方式创建进程会拷贝父进程的所有资源，包括父进程中的Context，但是这个Context子进程是用不了的，子进程由于持有了Context，调用CUDA Runtime API就会直接使用已有的父进程继承过来的Context访问GPU，从而导致Cuda error(3), initialization error这个异常。spawn方式创建进程不会继承父进程的Context，子进程调用任意CUDA Runtime API会初始化cuda runtime，所以spawn方式创建的子进程可以正常运行。

是的，现在父进程cuda的runtime不能被子进程“完美”的地复用，如果要在子进程中用cuda，目前的方式是需要用spawn起子进程。

**Comment by zhiqiu** [comment]
> @zhiqiu 在框架中可以判断当前进程创建的方式是fork还是spawn，如果是fork，需要提示用户不能在子进程也就是Dataloader预处理中调用CUDA相关的API比如paddle.to_tensor，或者提示用户使用spawn方式创建进程才可以调用CUDA相关API。

好的，感谢您的建议，我找相关同学看下如何添加合适的提示信息。
