### ISSUE TITLE
jetson nano上batch=4推理崩溃

### ISSUE THREAD

**Issue by gp1322719830** [PaddlePaddle/Paddle#31418]
paddle版本：1.6
错误信息：
W0303 23:24:53.351265 28635 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 53, Driver API Version: 10.0, Runtime API Version: 10.0
W0303 23:24:53.360337 28635 device_context.cc:245] device: 0, cuDNN Version: 7.5.
Segmentation fault (core dumped)

**Comment by GaoWei8** [comment]
是指在Nvdia jetson nano型号上运行哪个模型产生问题呢？

**Comment by gp1322719830** [comment]
> 是指在Nvdia jetson nano型号上运行哪个模型产生问题呢？
不是开源模型，是内部针对具体业务优化训练过的检测模型，在x86上不存在这个问题

**Comment by GaoWei8** [comment]
batch4小于4的时候是否可以正常运行。可以查看是不是显存不足了。

**Comment by gp1322719830** [comment]
> batch4小于4的时候是否可以正常运行。可以查看是不是显存不足了。

batch1、batch2、batch3都是可以的，batch4就崩溃，显存还剩400M崩溃的。
模型大小如下：
-rw-rw-r-- 1 585K 1月  14 20:55 detection.pdl_model
-rw-rw-r-- 1 235M 1月  14 20:55 detection.pdl_param
