### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#31737]
Platform: AIStudio
Version: 2.0.1

由于权重是float32类型，输入数据是float64，因此我使用`paddle.cast()`进行转换，但获得以下错误
```
File "train_v2.py", line 170, in <module>
    main()
  File "train_v2.py", line 93, in main
    data[0] = paddle.cast(data[0], 'float32')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 230, in cast
    out = core.ops.cast(x, 'in_dtype', x.dtype, 'out_dtype', dtype)
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:301)
  [operator < cast > error]
```

**Comment by Aurelius84** [comment]
请问可否提供一下`paddle.cast`的上下文代码，这里的 data 是一个tensor，还是一个list[Tensor]?  另外，其他API 可以在GPU上正常执行么？

**Comment by GuoQuanhao** [comment]
> 请问可否提供一下`paddle.cast`的上下文代码，这里的 data 是一个tensor，还是一个list[Tensor]? 另外，其他API 可以在GPU上正常执行么？
已解决

**Comment by SalvoPisciotta** [comment]
@GuoQuanhao how did you solve the problem?
