### ISSUE TITLE
RuntimeError: (PreconditionNotMet) Tensor holds no memory. Call Tensor::mutable_data firstly.

### ISSUE THREAD

**Issue by gaolexx** [PaddlePaddle/Paddle#31905]
单机多卡` loss.backward() `时发生` RuntimeError: (PreconditionNotMet) Tensor holds no memory. Call Tensor::mutable_data firstly.`

同程序单卡运行是没问题的。

报错信息：
```
Traceback (most recent call last):
  File "/home/du/anaconda3/envs/py370/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 204, in _func_wrapper
    result = func(*args)
  File "/home/du/gaolei20/oie/SR-wiki/run.py", line 226, in run
    loss.backward()
  File "<decorator-gen-114>", line 2, in backward
  File "/home/du/anaconda3/envs/py370/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/du/anaconda3/envs/py370/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/home/du/anaconda3/envs/py370/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 175, in backward
    retain_graph)
RuntimeError: (PreconditionNotMet) Tensor holds no memory. Call Tensor::mutable_data firstly.
  [Hint: holder_ should not be null.] (at /paddle/paddle/fluid/framework/tensor.cc:31)
```

环境信息：
```
****************************************
Paddle version: 2.0.1
Paddle With CUDA: True
GPU型号是Tesla K40m
OS: CentOS 6.3
Python version: 3.7.0
CUDA version: 9.0.176
cuDNN version: 7.6.5
Nvidia driver version: 396.26
****************************************
```

- 训练信息
    1）单机单卡一切正常，单机多卡会报如上的错
    2）显存信息：运行时` batch_size `设置的十分地小，在` loss.backward() `之前设置断点验证后可断定没有爆显存
    3）报错前的` loss `为` shape `为` [1] `的值，一切看着很正常

我实验了一下，目前找不到最小复现代码。请帮我分析一下这可能是什么问题？若需要代码才能分析 如流 联系 gaolei20

**Comment by gaolexx** [comment]
在代码中注释掉` loss.backward() `后可以单卡和多卡都可以正常运行，说明应该是` loss.backward() `的问题？

**Comment by gaolexx** [comment]
换成paddlepaddle 2.0.0后出现了新的错误：
```
Traceback (most recent call last):
  File "/home/du/anaconda3/envs/py370/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 204, in _func_wrapper
    result = func(*args)
  File "/home/du/gaolei20/oie/SR-wiki/run.py", line 203, in run
    encode_only=True)
  File "/home/du/anaconda3/envs/py370/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/du/anaconda3/envs/py370/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 492, in forward
    list(self._find_varbase(outputs)))
RuntimeError: (PreconditionNotMet) Please note that all ``forward`` outputs derived from the module parameters must participate in the calculation of losses and subsequent gradient calculations. If not, the wrapper will hang, waiting for autograd to generate gradients for these parameters. you can use detach or stop_gradient to make the unused parameters detached from the autograd graph.
  [Hint: Expected all_group_ready_ == false, but received all_group_ready_:1 != false:0.] (at /paddle/paddle/fluid/imperative/reducer.cc:312)
```

**Comment by gaolexx** [comment]
刚刚误操作了，issue继续保持打开，问题仍未解决。

对于换成paddlepaddle 2.0.0后的新问题，想问forward返回的必须是计算出来的tensor嘛，返回None, None, Tensor可以吗？

换成paddlepaddle 2.0.0后，单卡还是没问题，多卡报错

**Comment by gaolexx** [comment]
paddlecloud job: `job-0bb606161c010bd5`

**Comment by zhwesky2010** [comment]
> 刚刚误操作了，issue继续保持打开，问题仍未解决。
> 
> 对于换成paddlepaddle 2.0.0后的新问题，想问forward返回的必须是计算出来的tensor嘛，返回None, None, Tensor可以吗？
> 
> 换成paddlepaddle 2.0.0后，单卡还是没问题，多卡报错

这个也是可以的，只需要把返回的output正确处理好就可以

**Comment by gaolexx** [comment]
> > 刚刚误操作了，issue继续保持打开，问题仍未解决。
> > 对于换成paddlepaddle 2.0.0后的新问题，想问forward返回的必须是计算出来的tensor嘛，返回None, None, Tensor可以吗？
> > 换成paddlepaddle 2.0.0后，单卡还是没问题，多卡报错
> 
> 这个也是可以的，只需要把返回的output正确处理好就可以

那请您看看job-0bb606161c010bd5，它是因为什么而不能多卡运行？2.0.0会在前向的时候就报错，2.0.1在loss.backward()的时候会报错。而且2.0.0和2.0.1报错都不一样。如果2.0.1注释掉 loss.backward() 那么它就可以正常运行。

**Comment by zhwesky2010** [comment]
@gao-lex 这个看起来是代码写的有问题，backward时的反向计算中，与一个空Tensor做了ShareDataWith
![image](https://user-images.githubusercontent.com/52485244/112803080-7f9e0c80-90a5-11eb-88b7-cd8d955f8c36.png)

**Comment by zhwesky2010** [comment]
> > > 刚刚误操作了，issue继续保持打开，问题仍未解决。
> > > 对于换成paddlepaddle 2.0.0后的新问题，想问forward返回的必须是计算出来的tensor嘛，返回None, None, Tensor可以吗？
> > > 换成paddlepaddle 2.0.0后，单卡还是没问题，多卡报错
> > 
> > 
> > 这个也是可以的，只需要把返回的output正确处理好就可以
> 
> 那请您看看job-0bb606161c010bd5，它是因为什么而不能多卡运行？2.0.0会在前向的时候就报错，2.0.1在loss.backward()的时候会报错。而且2.0.0和2.0.1报错都不一样。如果2.0.1注释掉 loss.backward() 那么它就可以正常运行。

这个只是触发了不同地方的报错自检查位置，没其他问题。

前向就报错说明组网不对，组网计算过程中产生了空的Tensor。

**Comment by gaolexx** [comment]
@zhouwei25 那请问什么叫空的Tensor呢？shape为[0]这样的tensor嘛？在python中，怎么针对这种情况进行debug呢？

**Comment by zhwesky2010** [comment]
> @zhouwei25 那请问什么叫空的Tensor呢？shape为[0]这样的tensor嘛？在python中，怎么针对这种情况进行debug呢？

是指没有分配显存的，动态图中可以打印每个地方生成的Tensor就能看到，如果是没有分配显存，print时就会报错。

**Comment by gaolexx** [comment]
@zhouwei25 我的输入tensor全都能打印出来，模型本身是ernie-gen，我没改过模型内部。有没有其他的可能原因呢？

**Comment by zhwesky2010** [comment]
@gao-lex 2.0.0会在前向的时候就报错，这一句是哪一句报的错，是loss.backward()报错的吗？2.0.0应该和2.0.1的问题是一致的，只是自检的地方不同

**Comment by gaolexx** [comment]
2.0.0报错在
![image](https://user-images.githubusercontent.com/16011052/112830168-c0f1e480-90c4-11eb-8fa6-f6df3e0e1dd3.png)


初次之外，我还发现了一个新的奇怪的地方：
![image](https://user-images.githubusercontent.com/16011052/112831175-25fa0a00-90c6-11eb-8e88-2ea4cdb7578c.png)


这张图上：
1. setp:- rank:- name:- shape:- place:-是我的dataloader返回的所有的输入
2. step:- rank:- loss:- 是计算的loss
3. step:- rank- loss.backward() runed! 说明第一步的时候loss.backward()之后打印的，说明第一步正向和反向都正常。

然后step1，也就是第二步的时候就会报错。
```
----------------------------------------------
Process 1 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "/home/du/anaconda3/envs/py370/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 204, in _func_wrapper
    result = func(*args)
  File "/home/du/gaolei20/oie/SR-wiki/run.py", line 208, in run
    encode_only=True)
  File "/home/du/anaconda3/envs/py370/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/du/anaconda3/envs/py370/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 492, in forward
    list(self._find_varbase(outputs)))
RuntimeError: (PreconditionNotMet) Please note that all ``forward`` outputs derived from the module parameters must participate in the calculation of losses and subsequent gradient calculations. If not, the wrapper will hang, waiting for autograd to generate gradients for these parameters. you can use detach or stop_gradient to make the unused parameters detached from the autograd graph.
  [Hint: Expected all_group_ready_ == false, but received all_group_ready_:1 != false:0.] (at /paddle/paddle/fluid/imperative/reducer.cc:312)
```

我的代码为：
```
import argparse
import logging
import os
import re
import sys
# from CaRB.carb import Benchmark,Matcher
# from CaRB.carb import Matcher
import numpy as np
import paddle as P
import pandas as pd
from ernie.modeling_ernie import ErnieModel, ErnieModelForPretraining, ErnieModelForGeneration
from ernie.tokenizing_ernie import ErnieTokenizer
from paddle.io import DataLoader
from paddle.nn import functional as F
import paddle.distributed as dist
import subprocess
from decode import beam_search_infilling, post_process
# from model import ErnieModelForGeneration
from utils import padding_batch_sr, get_warmup_and_linear_decay, create_if_not_exists, gen_mask, SR_Dataset_web_and_wiki, SR_Dataset
import spacy
import random
import json

SPECIAL_TOKEN_LIST = ["[ARG1]", "[/ARG1]", "[REL]", "[/REL]", "[ARG2]", "[/ARG2]", "[SPO]", "[SR]", "[OIE]", "-LRB-", "-RRB-"]

def seed_everything(seed):
    random.seed(seed)
    np.random.seed(seed)
    P.seed(seed)

def prepair_output_setting(args):
    if not os.path.isdir(args.predict_output_dir):
        os.mkdir(args.predict_output_dir)
    for handler in logging.root.handlers[:]:
        logging.root.removeHandler(handler)
    logging.basicConfig(
        level=logging.DEBUG,
        filemode='w',
        format='%(asctime)s %(pathname)s %(filename)s %(funcName)s %(lineno)s %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %A %H:%M:%S',
        filename=f'{args.predict_output_dir}/log-debug.txt',
    )


logging.getLogger().setLevel(logging.DEBUG)

tokenizer = ErnieTokenizer.from_pretrained("./", mask_token=None,
                                               special_token_list=SPECIAL_TOKEN_LIST)
rev_dict = {v: k for k, v in tokenizer.vocab.items()}
rev_dict[tokenizer.pad_id] = ''  # replace [PAD]
rev_dict[tokenizer.unk_id] = ''  # replace [PAD]
@np.vectorize
def rev_lookup(i):
    return rev_dict[i]


def format_save_extractions(extraction_lists, predict_output_dir):
    df = pd.DataFrame(extraction_lists)
    df.to_csv(predict_output_dir, header=False, index=False)

def getMultiBleu(predicted_dir,reference_dir):
    # predicted_dir = /home/gaolei/oie/SR/output-debug/eval-step10000 该目录下存在着名称为data_index的预测文件
    # reference_dir = /home/gaolei/init-ckpt_and_dataset/Split-and-Rephrase/evaluation-directories/test
    bleu_scores = []
    tokens_per_sent = []
    simple_sent_amount = 0
    nlp = spacy.load("en_core_web_sm")
    for data_index_file_name in os.listdir(predicted_dir):
        data_index_file_abs_path = f"{predicted_dir}/{data_index_file_name}"
        sub = subprocess.Popen(
            f"perl multi-bleu.perl -lc {reference_dir}/{data_index_file_name}/reference < {data_index_file_abs_path}",
            shell=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        bleu_re = re.match(r'BLEU = ([0-9]*\.?[0-9]*), ', sub.stdout.read().decode('utf-8'))
        if bleu_re:
            bleu_score = float(bleu_re.group(1))
        else:
            bleu_score = 0
        bleu_scores.append(bleu_score)
        with open(data_index_file_abs_path,"r") as f:
            predict_sentence = f.read().strip()
            tokens_per_sent.append(len(predict_sentence.split()))
            simple_sent_amount += len(list(nlp(predict_sentence).sents))
    avg_bleu = sum(bleu_scores) / len(bleu_scores)
    avg_tokens_per_sent = float(sum(tokens_per_sent)) / simple_sent_amount
    avg_simple_sents_per_complex = float(simple_sent_amount) / len(bleu_scores)
    return avg_bleu, avg_tokens_per_sent, avg_simple_sents_per_complex
    # sub = subprocess.Popen("perl multi-bleu.perl -lc ~/init-ckpt_and_dataset/Split-and-Rephrase/evaluation-directories/test/3/reference < tmp.sentence", shell=True, stdout=subprocess.PIPE,stderr=subprocess.DEVNULL)
    # sub.stdout.read().decode('utf-8')
    # "BLEU = 78.43, 79.4/78.8/78.1/77.4 (BP=1.000, ratio=1.000, hyp_len=34, ref_len=34)\n"

def evaluate(model, dataloader, dataset, tokenizer, step, args, mode):
    if (args.use_multi_gpu and dist.get_rank() != 0):
        return
    create_if_not_exists(f"{args.predict_output_dir}/{mode}-pred.step{step}")
    # predict_output_dir = args.predict_output_dir / ('pred.step%d.%d' %
    #                                                 (step, env.dev_id))
    predict_output_dir = f"{args.predict_output_dir}/{mode}-pred.step{step}"
    with P.no_grad():
        with P.amp.auto_cast(enable=False):
            data_index = 0
            for data in dataloader():
                src_ids, src_sids, src_pids, src_indexs = data  # never use target when infer
                output_ids = beam_search_infilling(
                    model,
                    src_ids,
                    src_sids,
                    eos_id=tokenizer.sep_id,
                    sos_id=tokenizer.cls_id,
                    attn_id=tokenizer.vocab[args.attn_token],
                    max_decode_len=args.max_decode_len,
                    max_encode_len=args.max_encode_len,
                    beam_width=args.beam_width,
                    length_penalty=args.length_penalty,
                    tgt_type_id=args.tgt_type_id, )
                output_str = rev_lookup(output_ids.numpy())
                for ostr_index, ostr in zip(src_indexs.numpy().tolist(),output_str.tolist()):
                    if '[SEP]' in ostr:
                        ostr = ostr[:ostr.index('[SEP]')]
                    with open(f"{predict_output_dir}/{ostr_index}","w") as f:
                        f.write(''.join(map(post_process, ostr)))
                    raw_info = dataset._data[data_index]["meta"]
                    # assert raw_info["src_index"] == ostr_index
                    data_index+=1
            avg_bleu, avg_tokens_per_sent, avg_simple_sents_per_complex = getMultiBleu(f"{predict_output_dir}",args.evaluation_dir)
            logging.info(f"Step-{step}\tavg_bleu: {avg_bleu}\tavg_tokens_per_sent: {avg_tokens_per_sent}\tavg_simple_sents_per_complex:{avg_simple_sents_per_complex}")
    model.train()


def run(args):
    # device setting
    if not args.use_multi_gpu:
        if args.use_gpu:
            P.set_device("gpu")
        else:
            P.set_device("cpu")
    else:
        dist.init_parallel_env()
    # dataset & dataloader
    # sr_train_dataset = SR_Dataset_web_and_wiki(args)
    sr_train_dataset = SR_Dataset(args, args.SR_train_dataset_path)
    sr_dev_dataset = SR_Dataset(args, args.SR_dev_dataset_path)
    sr_test_dataset = SR_Dataset(args, args.SR_test_dataset_path)
    if args.use_multi_gpu:
        sample = P.io.DistributedBatchSampler(sr_train_dataset,batch_size=args.bsz,shuffle=True,drop_last=False)
        sr_train_dataloader = DataLoader(sr_train_dataset, batch_sampler=sample,places=P.CUDAPlace(dist.get_rank()),
                                     collate_fn=lambda x: padding_batch_sr(x, args=args, mode="train"),shuffle=False)
    else:
        sr_train_dataloader = DataLoader(sr_train_dataset, collate_fn=lambda x: padding_batch_sr(x, args=args, mode="train"),
                                         shuffle=True)
    # sr_train_dataloader = DataLoader(sr_train_dataset,
    #                                  collate_fn=lambda x: padding_batch_sr(x, args=args, mode="train"),
    #                                  shuffle=True)
    sr_dev_dataloader = DataLoader(sr_dev_dataset, batch_size=args.bsz,
                                   collate_fn=lambda x: padding_batch_sr(x, args=args, mode="val"))
    sr_test_dataloader = DataLoader(sr_test_dataset, batch_size=args.bsz,
                                    collate_fn=lambda x: padding_batch_sr(x, args=args, mode="test"))

    # model & tokenizer
    # config_path = f"{args.from_pretrained}/ernie_config.json"
    # config_file = open(config_path,"r")
    # model_cfg = dict(json.loads(config_file.read()))
    # config_file.close()
    # model = ErnieModelForGeneration(model_cfg)
    model = ErnieModelForGeneration.from_pretrained(args.from_pretrained)
    tokenizer = ErnieTokenizer.from_pretrained(args.vocab, mask_token=None, special_token_list=SPECIAL_TOKEN_LIST)

    vocab_size, _ = model.word_emb.weight.shape
    # 初始化并行环境
    if args.use_multi_gpu:
        model = P.DataParallel(model)
    g_clip = P.nn.ClipGradByGlobalNorm(1.0)
    param_name_to_exclue_from_weight_decay = re.compile(
        r'.*layer_norm_scale|.*layer_norm_bias|.*b_0')
    args.max_steps = args.max_epochs * len(sr_train_dataset) // args.bsz
    args.warmup_steps = args.max_steps // 10
    if (not args.use_multi_gpu) or (args.use_multi_gpu and dist.get_rank() == 0):
        logging.debug(f"max_steps: {args.max_steps}\twarmup_steps:{args.warmup_steps}")
    lr_scheduler = P.optimizer.lr.LambdaDecay(
        args.lr,
        get_warmup_and_linear_decay(
            args.max_steps, args.warmup_steps))

    opt = P.optimizer.AdamW(
        learning_rate=lr_scheduler,
        parameters=model.parameters(),
        weight_decay=args.wd,
        apply_decay_param_fun=lambda n: param_name_to_exclue_from_weight_decay.match(n),
        grad_clip=g_clip)

    scaler = P.amp.GradScaler(enable=args.use_amp)
    attn_id = tokenizer.vocab[args.attn_token]
    create_if_not_exists(args.save_dir)

    with P.amp.auto_cast(enable=args.use_amp):
        step = 0
        for epoch in range(args.max_epochs):
            for batch_index, data in enumerate(sr_train_dataloader):
                src_ids, src_sids, src_pids, tgt_ids, tgt_sids, tgt_pids, attn_ids, mask_src_2_src, mask_tgt_2_srctgt, mask_attn_2_srctgtattn, tgt_labels = data
                t = [src_ids, src_sids, src_pids, tgt_ids, tgt_sids, tgt_pids, attn_ids, mask_src_2_src, mask_tgt_2_srctgt, mask_attn_2_srctgtattn, tgt_labels]
                for i, name in enumerate(['src_ids', 'src_sids', 'src_pids', 'mask_src_2_src']):
                    print(f"step:{step}\trank:{dist.get_rank()}\tname:{name}\tshape:{t[i].shape}\tplace:{t[i].place}")

                src_pooled, src_encoded, src_info = model(
                    src_ids,
                    sent_ids=src_sids,
                    pos_ids=src_pids,
                    attn_bias=mask_src_2_src,
                    encode_only=True)
                cached_k, cached_v = src_info['caches']
                
                tgt_pooled, tgt_encoded, tgt_info = model(
                    tgt_ids,
                    sent_ids=tgt_sids,
                    pos_ids=tgt_pids,
                    attn_bias=mask_tgt_2_srctgt,
                    past_cache=(cached_k, cached_v),
                    encode_only=True)
                cached_k2, cached_v2 = tgt_info['caches']
                past_cache_k = [
                    P.concat([k, k2], 1) for k, k2 in zip(cached_k, cached_k2)
                ]
                past_cache_v = [
                    P.concat([v, v2], 1) for v, v2 in zip(cached_v, cached_v2)
                ]
                tgt_labels_bak = tgt_labels
                tgt_labels = F.one_hot(tgt_labels, vocab_size)
                if args.label_smooth > 0.:
                    tgt_labels = F.label_smooth(
                        tgt_labels, epsilon=args.label_smooth)
                loss, logits_2d, info = model(
                    attn_ids,
                    sent_ids=tgt_sids,
                    pos_ids=tgt_pids,
                    attn_bias=mask_attn_2_srctgtattn,
                    past_cache=(past_cache_k, past_cache_v),
                    tgt_labels=tgt_labels,
                    tgt_pos=P.nonzero(attn_ids == attn_id))

                loss = scaler.scale(loss)
                print(f"step:{step}\trank:{dist.get_rank()}\tloss:{loss}")
                loss.backward()
                print(f"step:{step}\trank:{dist.get_rank()}\tloss.backward() runed!")
                scaler.minimize(opt, loss)
                model.clear_gradients()
                lr_scheduler.step()
                step += 1
                # print(step,args.logging_interval,step % args.logging_interval)

                if ((not args.use_multi_gpu) or (args.use_multi_gpu and dist.get_rank() == 0)) and (step % args.logging_interval == 0):
                    _lr = lr_scheduler.get_lr()
                    token_acc = P.metric.accuracy(logits_2d, P.reshape(tgt_labels_bak, [tgt_labels_bak.shape[0], -1]),
                                                  k=1)
                    if args.use_amp:
                        _l = (loss / scaler._scale).numpy()
                        # msg = '[rank-%d][step-%d] train loss %.5f lr %.3e scaling %.3e' % (
                        #     env.dev_id, step, _l, _lr, scaler._scale.numpy())
                        msg = '[epoch-%d] [step-%d] train loss %.5f lr %.3e scaling %.3e token ACC %.3f' % (
                            epoch, step, _l, _lr, scaler._scale.numpy(), float(token_acc))
                    else:
                        _l = loss.numpy()
                        # msg = '[rank-%d][step-%d] train loss %.5f lr %.3e' % (
                        #     env.dev_id, step, _l, _lr)
                        msg = '[epoch-%d] [step-%d] train loss %.5f lr %.3e token ACC %.3f' % (
                            epoch, step, _l, _lr, float(token_acc))
                    logging.debug(msg)

                # evaluate(model, sr_test_dataloader, sr_test_dataset, tokenizer, step, args, mode="test")

                # if args.predict_output_dir is not None and step > args.skip_eval_steps and step % args.eval_steps == 0:
                #     # log.debug('doing predict on gpu %d...' % env.dev_id)
                #     evaluate(model, sr_dev_dataloader, sr_dev_dataset, tokenizer, step, args, mode="dev")
                #     evaluate(model, sr_test_dataloader, sr_test_dataset, tokenizer, step, args, mode="test")
                if step > args.max_steps:
                    break
            # if args.save_dir is not None :
            #     P.save(model.state_dict(), f"{args.save_dir}/ckpt.bin")
            # evaluate(model, sr_dev_dataloader, sr_dev_dataset, tokenizer, step, args, mode="dev")
            evaluate(model, sr_test_dataloader, sr_test_dataset, tokenizer, step, args, mode="test")
            if step > args.max_steps:
                break

        if args.save_dir is not None:
            P.save(model.state_dict(), f"{args.save_dir}/ckpt.bin")

if __name__ == "__main__":
    # dataset 超参
    parser = argparse.ArgumentParser()
    parser.add_argument('--seed', default=42, type=int)
    parser.add_argument(
        '--use_multi_gpu',
        action="store_true"  # 默认不使用gpu，带参数--use_multi_gpu后使用GPU
    )
    parser.add_argument(
        '--use_gpu',
        action="store_true"  # 默认不使用gpu，带参数--use_gpu后使用GPU
    )
    parser.add_argument(
        '--from_pretrained',
        type=str,
        default="/root/.paddle-ernie-cache/cf1af54c68b451c1684c8c6da6522333",
        help='pretrained model directory or tag')
    parser.add_argument(
        '--vocab',
        type=str,
        default="./",
        help='vocab file dir')
    parser.add_argument('--bsz', type=int, default=8, help='batchsize')
    parser.add_argument('--eval_bsz', type=int, default=20, help='batchsize')
    parser.add_argument(
        '--max_epochs',
        type=int,
        required=True,
        help='max_train_epochs')
    parser.add_argument('--max_encode_len', type=int, default=100)
    parser.add_argument('--max_decode_len', type=int, default=200)
    # parser.add_argument('--warmup_steps', type=int, default=10000)
    parser.add_argument('--tgt_type_id', type=int, default=3)
    # parser.add_argument('--warmup_proportion', type=float, default=0.01)
    parser.add_argument('--beam_width', type=int, default=5)
    parser.add_argument(
        '--noise_prob',
        type=float,
        default=0.7,
        help='probability of token be repalced')
    parser.add_argument(
        '--use_random_noice',
        action='store_true',
        help='if set, replace target tokens with random token from vocabulary, else replace with `[NOISE]`'
    )
    parser.add_argument('--lr', type=float, default=5e-5, help='learning rate')
    parser.add_argument('--label_smooth', type=float, default=0.1)
    parser.add_argument('--length_penalty', type=float, default=1.0)
    parser.add_argument(
        '--predict_output_dir',
        type=str,
        default="./output",
        help='predict file output directory')
    parser.add_argument(
        '--attn_token',
        type=str,
        default='[ATTN]',
        help='if [ATTN] not in vocab, you can specified [MAKK] as attn-token')
    # parser.add_argument(
    #     '--inference_model_dir',
    #     type=str,
    #     default=None,
    #     help='inference model output directory')
    # parser.add_argument(
    #     '--init_checkpoint',
    #     type=str,
    #     default=None,
    #     help='checkpoint to warm start from')
    parser.add_argument(
        '--save_dir', type=str, default="./output", help='model output directory')
    parser.add_argument(
        '--wd',
        type=float,
        default=0.01,
        help='weight decay, aka L2 regularizer')

    parser.add_argument(
        '--use_amp',
        action='store_true',
        help='only activate AMP(auto mixed precision accelatoin) on TensorCore compatible devices'
    )

    parser.add_argument("--SR_train_dataset_path",
                        default="/home/gaolei/init-ckpt_and_dataset/Split-and-Rephrase/baseline-seq2seq/train",
                        type=str)
    parser.add_argument("--SR_dev_dataset_path",
                        default="/home/gaolei/init-ckpt_and_dataset/Split-and-Rephrase/baseline-seq2seq/validation",
                        type=str)
    parser.add_argument("--SR_test_dataset_path",
                        default="/home/gaolei/init-ckpt_and_dataset/Split-and-Rephrase/baseline-seq2seq/test", type=str)
    parser.add_argument("--SR_wiki_train_dataset_path",
                        default="/home/gaolei/init-ckpt_and_dataset/Split-and-Rephrase/wiki-train.tsv",
                        type=str)
    parser.add_argument("--evaluation_dir",
                        default="/home/gaolei/init-ckpt_and_dataset/Split-and-Rephrase/evaluation-directories/test-tokenized", type=str)
    parser.add_argument(
        '--sr_atomic_sampling',
        action="store_true"

    )

    parser.add_argument("--task_name", default="SR", type=str)
    parser.add_argument('--sr_sampling_rate', type=int, default=6)
    parser.add_argument(
        '--padding_value',
        type=int,
        default=0)
    parser.add_argument(
        '--logging_interval',
        type=int,
        default=100)

    args = parser.parse_args()

    seed_everything(args.seed)

    prepair_output_setting(args)

    # rev_dict[tokenizer.cls_id] = ''
    # run(args)
    if args.use_multi_gpu:
        dist.spawn(run, args=(args,), nprocs=2, gpus="0,1")
    else:
        run(args)
```

运行方法为：
```
python3.7 run.py --use_multi_gpu     --from_pretrained /home/du/gaolei20/ernie_model     --SR_train_dataset_path ./baseline-seq2seq/train     --SR_dev_dataset_path ./baseline-seq2seq/validation     --SR_test_dataset_path ./baseline-seq2seq/test     --SR_wiki_train_dataset_path ./wiki-train.tsv     --evaluation_dir ./evaluation-directories/test-tokenized     --task_name SR-wiki     --sr_sampling_rate 1     --bsz 10     --max_encode_len 100     --max_decode_len 130     --max_epochs 100     --logging_interval 1000     --predict_output_dir ./output     --save_dir ./output     --sr_atomic_sampling
```

**Comment by ForFishes** [comment]
第二个step报错是符合预期的。因为当前设计，是在第二个step的时候去检查第一个step的执行情况是否符合预期。所以实际还是第一个step出了问题。

**Comment by gaolexx** [comment]
@ForFishes @zhouwei25 
多谢你们的帮助，的确是
```python
src_pooled, src_encoded, src_info = model(
                    src_ids,
                    sent_ids=src_sids,
                    pos_ids=src_pids,
                    attn_bias=mask_src_2_src,
                    encode_only=True)
                cached_k, cached_v = src_info['caches']
                
                tgt_pooled, tgt_encoded, tgt_info = model(
                    tgt_ids,
                    sent_ids=tgt_sids,
                    pos_ids=tgt_pids,
                    attn_bias=mask_tgt_2_srctgt,
                    past_cache=(cached_k, cached_v),
                    encode_only=True)
                cached_k2, cached_v2 = tgt_info['caches']
                past_cache_k = [
                    P.concat([k, k2], 1) for k, k2 in zip(cached_k, cached_k2)
                ]
                past_cache_v = [
                    P.concat([v, v2], 1) for v, v2 in zip(cached_v, cached_v2)
                ]
                tgt_labels_bak = tgt_labels
                tgt_labels = F.one_hot(tgt_labels, vocab_size)
                if args.label_smooth > 0.:
                    tgt_labels = F.label_smooth(
                        tgt_labels, epsilon=args.label_smooth)
                loss, logits_2d, info = model(
                    attn_ids,
                    sent_ids=tgt_sids,
                    pos_ids=tgt_pids,
                    attn_bias=mask_attn_2_srctgtattn,
                    past_cache=(past_cache_k, past_cache_v),
                    tgt_labels=tgt_labels,
                    tgt_pos=P.nonzero(attn_ids == attn_id))
```
这部分的组网方式不能直接model = P.DataParallel(model)

所以，修改方式为把模型包装成下面的形式：
![image](https://user-images.githubusercontent.com/16011052/112965495-e4c43180-917b-11eb-816e-c3daa52347e5.png)
