### ISSUE TITLE
ImportError: /usr/local/lib/python3.6/site-packages/paddle/fluid/core_noavx.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by mhillebrand** [PaddlePaddle/Paddle#32000]
I've compiled PaddlePaddle `release/1.8` using Docker image `registry.baidubce.com/paddlepaddle/serving:latest-cuda10.1-cudnn7-devel`. My CPU is an AMD Threadripper 3970X that does not support AVX_512, so I've turned off AVX and MKL with my Cmake command:

`$ cmake .. -DPY_VERSION=3.6 -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DCUDA_ARCH_NAME=All -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_AVX=OFF -DWITH_MKL=OFF`

The `make` command succeeds, but after installing the .whl file with pip3 and typing `import paddle`, I get this error message:

```
>>> import paddle
WARNING: Do not have avx core. You may not build with AVX, but AVX is supported on local machine.
 You could build paddle WITH_AVX=ON to get better performance.
The original error is: No module named 'paddle.fluid.core_avx'
Error: Can not import noavx core while this file exists /usr/local/lib/python3.6/site-packages/paddle/fluid/core_noavx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/paddle/__init__.py", line 37, in <module>
    import paddle.complex
  File "/usr/local/lib/python3.6/site-packages/paddle/complex/__init__.py", line 15, in <module>
    from . import tensor
  File "/usr/local/lib/python3.6/site-packages/paddle/complex/tensor/__init__.py", line 15, in <module>
    from . import math
  File "/usr/local/lib/python3.6/site-packages/paddle/complex/tensor/math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "/usr/local/lib/python3.6/site-packages/paddle/common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/core.py", line 322, in <module>
    raise e
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/core.py", line 288, in <module>
    from .core_noavx import *
ImportError: /usr/local/lib/python3.6/site-packages/paddle/fluid/core_noavx.so: undefined symbol: _Py_ZeroStruct
```

Here is the output of my Cmake command:

```
$ cmake .. -DPY_VERSION=3.6 -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DCUDA_ARCH_NAME=All -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_AVX=OFF -DWITH_MKL=OFF
-- Found Paddle host system: ubuntu, version: 16.04.7
-- Found Paddle host system's CPU: 64 cores
-- CXX compiler: /usr/local/gcc-8.2/bin/c++, version: GNU 8.2.0
-- C compiler: /usr/local/gcc-8.2/bin/gcc, version: GNU 8.2.0
-- AR tools: /usr/bin/ar
-- Current cuDNN header is /usr/include/cudnn.h. Current cuDNN version is v7.6.
-- Do not have AVX2 intrinsics and disabled MKL-DNN
-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: /paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Download dependence[cudaerror] from http://paddlepaddledeps.bj.bcebos.com/cudaErrorMessage.tar.gz
-- Build OpenBLAS by External Project (include: /paddle/build/third_party/install/openblas/include, library: /paddle/build/third_party/install/openblas/lib/libopenblas.a)
CMake Warning at /home/cmake-3.16.0-Linux-x86_64/share/cmake-3.16/Modules/FindProtobuf.cmake:499 (message):
  Protobuf compiler version 3.1.0 doesn't match library version 2.6.1
Call Stack (most recent call first):
  cmake/external/protobuf.cmake:18 (FIND_PACKAGE)
  cmake/third_party.cmake:234 (include)
  CMakeLists.txt:161 (include)


-- Protobuf protoc executable: /paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
-- GLOO_NAME: gloo, GLOO_URL: https://pslib.bj.bcebos.com/gloo.tar.gz
-- CUDA detected: 10.1
-- Added CUDA NVCC flags for: sm_30 sm_35 sm_50 sm_52 sm_60 sm_61 sm_70 sm_75
-- Current TensorRT header is /usr/include/NvInfer.h. Current TensorRT version is v6.
-- Ccache is founded, use ccache to speed up compile.
-- Paddle version is 0.0.0
CMake Warning at CMakeLists.txt:224 (message):
  On inference mode, will take place some specific optimization.  Turn on the
  ON_INFER flag when building inference_lib only.


-- commit: c36c22f
-- branch: release/1.8
-- Configuring done
-- Generating done
-- Build files have been written to: /paddle/build
```

I've tried turning AVX on, but that yields a similar error message.

**Comment by Labstrakt** [comment]
I just compiled the `release/2.0` branch...with the same resulting error message. :(

**Comment by mhillebrand** [comment]
It turns out this was a confusion between python3 and python2. I ran the following commands:

```
$ echo $PATH
/usr/local/go/bin:/root/go/bin:/usr/local/python2.7.15/bin:/usr/local/python2.7.15/include:/usr/local/bin:/usr/local/python3.5.1/bin:/usr/local/include/python3.6m/:/usr/local/python3.5.1/include:/home/cmake-3.16.0-Linux-x86_64/bin:/usr/local/gcc-8.2/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ export PATH=/usr/local/go/bin:/root/go/bin:/usr/local/bin:/usr/local/bin/python3.6:/usr/local/include/python3.6m/:/usr/local/python3.5.1/include:/home/cmake-3.16.0-Linux-x86_64/bin:/usr/local/gcc-8.2/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

$ echo $LD_LIBRARY_PATH
/usr/local/python2.7.15/lib:/usr/local/lib:/usr/local/python3.5.1/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
$ export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/lib/x86_64-linux-gnu/:/usr/local/cuda/:/usr/local/TensorRT6-cuda10.1-cudnn7

$ echo $CPLUS_INCLUDE_PATH
/usr/local/python2.7.15/include/python2.7:/usr/local/python3.5.1/include/python3.5:/usr/local/include/python3.6m/:
$ export CPLUS_INCLUDE_PATH=/usr/local/include/python3.6m/
```

Then I turned on AVX and MKL and recompiled. Seems to work now.
