### ISSUE TITLE
高层API单机多卡环境下添加transform报错

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/Paddle#32115]
单机多卡不加transform前正常训练，加了transform后报错

`import paddle
from paddle.vision.transforms import ToTensor
import paddle.distributed as dist
from paddle.vision import transforms as T
paddle.seed(8888)
import numpy as np
from visualdl import LogWriter
#数据增强
transform_train =T.Compose([T.Resize((256,256)),
                            T.RandomRotation(10),
                            T.Transpose(),
                            T.Normalize(mean=[0, 0, 0],                          
                                        std =[255, 255, 255]),                   
                            T.Normalize(mean=[0.50950350, 0.54632660, 0.57409690],
                                        std= [0.26059777, 0.26041326, 0.29220656])
                            ])
transform_eval =T.Compose([T.Resize((256,256)),
                            T.Transpose(),
                            T.Normalize(mean=[0, 0, 0],                           
                                        std =[255, 255, 255]),                   
                            T.Normalize(mean=[0.50950350, 0.54632660, 0.57409690],
                                        std= [0.26059777, 0.26041326, 0.29220656])
                            ])
                            
train_dataset = paddle.vision.datasets.Cifar100(mode='train', transform=transform_train)
test_dataset = paddle.vision.datasets.Cifar100(mode='test', transform=transform_eval)

resnet50 = paddle.vision.models.resnet50()

# Mnist继承paddle.nn.Layer属于Net，model包含了训练功能
model = paddle.Model(resnet50)

model.prepare(
    paddle.optimizer.Adam(learning_rate=0.01, parameters=model.parameters()),
    paddle.nn.CrossEntropyLoss(),
    paddle.metric.Accuracy())
def train():
    # 启动训练
    model.fit(train_dataset,test_dataset,epochs=100,batch_size=64,verbose=1)

if __name__ == '__main__':
    dist.spawn(train)`

报错信息
[INFO]: current net device: eth0, ip: 172.28.0.58
[INFO]: paddle job envs:
POD_IP=job-4cabaf5649a9c74f01ece94d3d8031e6-trainer-0.job-4cabaf5649a9c74f01ece94d3d8031e6
PADDLE_PORT=12345
PADDLE_TRAINER_ID=0
PADDLE_TRAINERS_NUM=1
PADDLE_USE_CUDA=1
NCCL_SOCKET_IFNAME=eth0
PADDLE_IS_LOCAL=1
OUTPUT_PATH=/root/paddlejob/workspace/output
LOCAL_LOG_PATH=/root/paddlejob/workspace/log
LOCAL_MOUNT_PATH=/mnt/code_20210407115722,/mnt/datasets_20210407115722
JOB_ID=job-4cabaf5649a9c74f01ece94d3d8031e6
TRAINING_ROLE=TRAINER
[INFO]: user command: python -u train.py
[INFO]: start trainer
~/paddlejob/workspace/code /mnt
Cache file /root/.cache/paddle/dataset/cifar/cifar-100-python.tar.gz not found, downloading https://dataset.bj.bcebos.com/cifar/cifar-100-python.tar.gz 
Begin to download

Download finished
W0407 11:57:32.636672   220 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0407 11:57:32.640615   220 device_context.cc:372] device: 0, cuDNN Version: 7.6.
W0407 11:57:51.051769   435 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0407 11:57:51.055773   435 device_context.cc:372] device: 0, cuDNN Version: 7.6.
W0407 11:57:51.104475   436 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0407 11:57:51.108616   436 device_context.cc:372] device: 0, cuDNN Version: 7.6.
W0407 11:57:51.320035   438 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0407 11:57:51.324132   438 device_context.cc:372] device: 0, cuDNN Version: 7.6.
W0407 11:57:51.795372   439 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0407 11:57:51.799536   439 device_context.cc:372] device: 0, cuDNN Version: 7.6.
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/100

step  10/196 [>.............................] - loss: 6.2724 - acc: 0.0156 - ETA: 3:01 - 973ms/step/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return (isinstance(seq, collections.Sequence) and
/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/nn/layer/norm.py:648: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 1ul, paddle::operators::CompareOpKernel<paddle::platform::CUDADeviceContext, paddle::operators::EqualFunctor<int> >, paddle::operators::CompareOpKernel<paddle::platform::CUDADeviceContext, paddle::operators::EqualFunctor<long> >, paddle::operators::CompareOpKernel<paddle::platform::CUDADeviceContext, paddle::operators::EqualFunctor<float> >, paddle::operators::CompareOpKernel<paddle::platform::CUDADeviceContext, paddle::operators::EqualFunctor<double> > >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   void paddle::operators::ElementwiseComputeEx<paddle::operators::EqualFunctor<long>, paddle::platform::CUDADeviceContext, long, bool>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, paddle::operators::EqualFunctor<long>, paddle::framework::Tensor*)
5   paddle::framework::SignalHandle(char const*, int)
6   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1617767889 (unix time) try "date -d @1617767889" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0xdc) received by PID 435 (TID 0x7f12d313c700) from PID 220 ***]

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   std::shared_ptr<paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type> paddle::imperative::PrepareData<paddle::imperative::VarBase>(paddle::framework::OperatorWithKernel const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::OpKernelType const&)
3   paddle::framework::TransformData(paddle::framework::OpKernelType const&, paddle::framework::OpKernelType const&, paddle::framework::Tensor const&, paddle::framework::Tensor*)
4   paddle::framework::TransDataDevice(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
5   paddle::framework::TensorCopySync(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
6   void paddle::memory::Copy<paddle::platform::CUDAPlace, paddle::platform::CUDAPinnedPlace>(paddle::platform::CUDAPlace, void*, paddle::platform::CUDAPinnedPlace, void const*, unsigned long, CUstream_st*)
7   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)
8   paddle::framework::SignalHandle(char const*, int)
9   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1617767889 (unix time) try "date -d @1617767889" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0xdc) received by PID 436 (TID 0x7f8f09da7700) from PID 220 ***]

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 1ul, paddle::operators::CompareOpKernel<paddle::platform::CUDADeviceContext, paddle::operators::EqualFunctor<int> >, paddle::operators::CompareOpKernel<paddle::platform::CUDADeviceContext, paddle::operators::EqualFunctor<long> >, paddle::operators::CompareOpKernel<paddle::platform::CUDADeviceContext, paddle::operators::EqualFunctor<float> >, paddle::operators::CompareOpKernel<paddle::platform::CUDADeviceContext, paddle::operators::EqualFunctor<double> > >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   void paddle::operators::ElementwiseComputeEx<paddle::operators::EqualFunctor<long>, paddle::platform::CUDADeviceContext, long, bool>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, paddle::operators::EqualFunctor<long>, paddle::framework::Tensor*)
5   paddle::framework::SignalHandle(char const*, int)
6   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1617767890 (unix time) try "date -d @1617767890" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0xdc) received by PID 438 (TID 0x7fe9d3047700) from PID 220 ***]

Traceback (most recent call last):
  File "train.py", line 99, in <module>
    dist.spawn(train)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 449, in spawn
    while not context.join():
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 255, in join
    self._throw_exception(error_index)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 273, in _throw_exception
    raise Exception(msg)
Exception: 

----------------------------------------------
Process 3 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 204, in _func_wrapper
    result = func(*args)
  File "/root/paddlejob/workspace/code/train.py", line 93, in train
    model.fit(train_dataset,test_dataset,epochs=100,batch_size=64,verbose=1)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/hapi/model.py", line 1495, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/hapi/model.py", line 1802, in _run_one_epoch
    data[len(self._inputs):])
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/hapi/model.py", line 941, in train_batch
    loss = self._adapter.train_batch(inputs, labels)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/hapi/model.py", line 656, in train_batch
    * [to_variable(x) for x in inputs])
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/vision/models/resnet.py", line 244, in forward
    x = self.layer2(x)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 95, in forward
    input = layer(input)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/vision/models/resnet.py", line 140, in forward
    out = self.bn3(out)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/nn/layer/norm.py", line 660, in forward
    use_global_stats=self._use_global_stats)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/nn/functional/norm.py", line 198, in batch_norm
    *attrs)
SystemError: (Fatal) Operator batch_norm raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 128.000244MB memory on GPU 0, available memory is only 41.875000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
. (at /paddle/paddle/fluid/imperative/tracer.cc:172)

/mnt
[INFO]: train job failed! train_ret: 1

**Comment by tink2123** [comment]
看报错是显存不足导致的，请检查当前0号卡是否有其他程序占用，或者换一张卡运行。

**Comment by gaorui999** [comment]
1、减小了batchsize(64→32)之后可以正常运行了
2、修改了使用全部卡
if __name__ == '__main__':
        dist.spawn(train, nprocs=4)

不过我有疑问，我这是使用的Cifar100数据集，我在aistudio notebook里用单卡，batch都可以设置为256，而不会显存不足。
为什么在单机多卡的情况下就会有这个问题，我用的是脚本文件里的单机4V100卡

**Comment by tink2123** [comment]
gpu 型号不同，显存大小也不同。您本地单卡bs=256能跑吗？是只有多卡会报显存不足吗？
看您的报错，当前可用显存只有 41.8MB，可以动态观察一下显存变化情况。

**Comment by gaorui999** [comment]
我在aistudio notebook里用V100单卡的可以正常跑，bs=1024都能正常跑，只有多卡会显示显存不够

**Comment by tink2123** [comment]
可能是 aistudio 资源分配有误，创建一个新的项目试下呢？
