### ISSUE TITLE
OSError: (External)  Cuda error(700), an illegal memory access was encountered.   

### ISSUE THREAD

**Issue by hlzonWang** [PaddlePaddle/Paddle#32799]
使用以下代码读入数据不报错：
class DataIterator:

    def __init__(self, source, batch_size=256, max_batch_size=20):
        self.source = open(source, 'r')
        self.source_dicts = []
        self.batch_size = batch_size
        self.source_buffer = []
        self.k = batch_size * max_batch_size
        self.end_of_data = False

    def __iter__(self):
        return self

    def reset(self):
        self.source.seek(0)

    def __next__(self):
        if self.end_of_data:
            self.end_of_data = False
            self.reset()
            raise StopIteration

        source = []
        target = []

        if len(self.source_buffer) == 0:
            for k_ in range(self.k):
                ss = self.source.readline()
                if ss == "":
                    break
                self.source_buffer.append(ss.strip("\n").split(","))

        if len(self.source_buffer) == 0:
            self.end_of_data = False
            self.reset()
            raise StopIteration

        try:
            # actual work here
            while True:

                # read from source file and map to word index
                try:
                    ss = self.source_buffer.pop()
                except IndexError:
                    break
                source.append(ss[:-1])
                target.append(ss[-1])
                if len(source) >= self.batch_size or len(target) >= self.batch_size:
                    break
        except IOError:
            self.end_of_data = True

        if len(source) == 0 or len(target) == 0:
            source, target = self.next()

        source = np.array(source, np.float32)
        target = np.array(target, np.float32)
        return source, target

但使用Paddle的：
class RandomDataset(paddle.io.Dataset):
    def __init__(self):
        self.res_data = None

    def data_reader(self, path):
        data = pd.read_table(path, sep=',', header=None)
        smo = SMOTE()
        x = data[[i for i in range(0, 266)]]
        y = data[266]
        x_smo, y_smo = smo.fit_resample(x, y)
        self.res_data = [x_smo.values, y_smo.values]

    def __getitem__(self, idx):
        feature = self.res_data[0][idx].astype('float32')
        label = self.res_data[1][idx].astype('float32')
        return feature, label

    def __len__(self):
        return len(self.res_data[1])

是否Paddle训练和Paddle的io不兼容？

**Comment by hlzonWang** [comment]
Traceback (most recent call last):
  File "train.py", line 121, in <module>
    train()
  File "train.py", line 55, in train
    loss.backward()
  File "</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-114>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 177, in backward
    self._run_backward(framework._dygraph_tracer(), retain_graph)
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:296)

**Comment by ForFishes** [comment]
您好，我这里帮你看下。Paddle的训练和Dataset应该是兼容的。能否提供具体的使用Dataset的训练代码呢？

**Comment by LiuHao-THU** [comment]
> 您好，我这里帮你看下。Paddle的训练和Dataset应该是兼容的。能否提供具体的使用Dataset的训练代码呢？

同样遇到这个问题，但是我得代码在不同的环境，有一个可以跑，有一个就会cuda error

**Comment by LiuHao-THU** [comment]
![image](https://user-images.githubusercontent.com/30975916/120750552-1ae5af00-c539-11eb-8a79-02c75db10d2b.png)

**Comment by CodeLearn2000** [comment]
> > 您好，我这里帮你看下。Paddle的训练和Dataset应该是兼容的。能否提供具体的使用Dataset的训练代码呢？
> 
> 同样遇到这个问题，但是我得代码在不同的环境，有一个可以跑，有一个就会cuda error
我这里这个问题已经解决了，是动态图和静态图不兼容导致的，把静态图的损失函数换成动态图的就解决了。

**Comment by hlzonWang** [comment]
> > 您好，我这里帮你看下。Paddle的训练和Dataset应该是兼容的。能否提供具体的使用Dataset的训练代码呢？
> 
> 同样遇到这个问题，但是我得代码在不同的环境，有一个可以跑，有一个就会cuda error

我这里这个问题已经解决了，是动态图和静态图不兼容导致的，把静态图的损失函数换成动态图的就解决了。

**Comment by hlzonWang** [comment]
> > 您好，我这里帮你看下。Paddle的训练和Dataset应该是兼容的。能否提供具体的使用Dataset的训练代码呢？
> 
> 同样遇到这个问题，但是我得代码在不同的环境，有一个可以跑，有一个就会cuda error

如果出错是在梯度回传上，可以试一下用不同的变量回传，比如辅助LOSS，比如ACC，这样好调试一点。

**Comment by IvanaXu** [comment]
Same...
