### ISSUE TITLE
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. An unsupported value or parameter was passed to the function (a negative vector size, for example).  (at /paddle/paddle/fluid/platform/cuda_helper.h:107)

### ISSUE THREAD

**Issue by dongfangyixi** [PaddlePaddle/Paddle#33547]
![image](https://user-images.githubusercontent.com/6477100/121813846-7550df00-cca0-11eb-8b89-e2a05c7080d1.png)

with cuda 11.2 cudnn 8.1.1.33

![image](https://user-images.githubusercontent.com/6477100/121813921-ec867300-cca0-11eb-8d48-bea1d78d7684.png)
![image](https://user-images.githubusercontent.com/6477100/121813990-4ab35600-cca1-11eb-8d62-d6a954b8ce65.png)
![image](https://user-images.githubusercontent.com/6477100/121814012-6159ad00-cca1-11eb-8619-7c5d6fbf16eb.png)

installed with 
```
python -m pip install paddlepaddle-gpu==2.1.0.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
```

test cmd:
```
paddle.utils.run_check()
```

**Comment by hong19860320** [comment]
麻烦分别执行下如下命令，把结果贴上来哈~

`
$ nvidia-smi

$ nvcc -V

$ echo $PATH

$ echo $LD_LIBRARY_PATH
`

**Comment by dongfangyixi** [comment]
nvidia-smi:
![image](https://user-images.githubusercontent.com/6477100/121989272-6b2cfe80-cdce-11eb-9f4e-1ed34d556765.png)

nvcc -V:
![image](https://user-images.githubusercontent.com/6477100/121989311-80099200-cdce-11eb-9946-bda7fc577c54.png)

which nvidia-smi:
/usr/bin/nvidia-smi

which nvcc;
/usr/bin/nvcc

echo $PATH:
/home/xx/.local/bin:/home/xu/miniconda3/bin/:/home/xx/miniconda3/bin:/home/xx/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

echo $LD_LIBRARY_PATH:
/home/xu/env/cuda/lib64/
** /home/xx/env/cuda/lib64/  is where cudnn 8.1 installed.

**Comment by pangyoki** [comment]
你好，nvcc -V显示的cuda版本是10.1，应该是cuda版本不对导致的。可以检查下/usr/local/cuda链接的cuda版本是哪个？链接到cuda11.2看是否可行。

**Comment by lcdisme** [comment]
> ![image](https://user-images.githubusercontent.com/6477100/121813846-7550df00-cca0-11eb-8b89-e2a05c7080d1.png)
> 
> with cuda 11.2 cudnn 8.1.1.33
> 
> ![image](https://user-images.githubusercontent.com/6477100/121813921-ec867300-cca0-11eb-8d48-bea1d78d7684.png)
> ![image](https://user-images.githubusercontent.com/6477100/121813990-4ab35600-cca1-11eb-8d62-d6a954b8ce65.png)
> ![image](https://user-images.githubusercontent.com/6477100/121814012-6159ad00-cca1-11eb-8619-7c5d6fbf16eb.png)
> 
> installed with
> 
> ```
> python -m pip install paddlepaddle-gpu==2.1.0.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
> ```
> 
> test cmd:
> 
> ```
> paddle.utils.run_check()
> ```

你好，你的问题解决了吗？我也遇到这个情况，请问是怎么解决的，谢谢！

**Comment by dongfangyixi** [comment]
@lcdisme 解决了，我之前nvcc版本和cuda不一致，paddle 也需要nvcc版本和cuda一致。（虽然pytorch 和 tf 都不需要）

**Comment by dongfangyixi** [comment]
主要是nvcc版本 link的 和 系统的不一样，所以需要重装 一下cuda 11.2

**Comment by lcdisme** [comment]
> 主要是nvcc版本 link的 和 系统的不一样，所以需要重装 一下cuda 11.2

好的，谢谢。我的是由于cudnn版本不兼容，所以退回cuda10.2就可以了。看来安装异常主要还是要排查环境。

**Comment by LayBrick** [comment]
如何退回cuda10.2
