### ISSUE TITLE
 Cublas error, `CUBLAS_STATUS_INVALID_VALUE`.

### ISSUE THREAD

**Issue by kaixin-bai** [PaddlePaddle/Paddle#33861]
```bash
> nvcc -V   
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```
```bash
Wed Jun 30 10:50:14 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.80       Driver Version: 460.80       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
| 30%   38C    P8    11W / 175W |    828MiB /  7982MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1926      G   /usr/lib/xorg/Xorg                 36MiB |
|    0   N/A  N/A      2110      G   /usr/bin/gnome-shell               91MiB |
|    0   N/A  N/A      3494      G   /usr/lib/xorg/Xorg                372MiB |
|    0   N/A  N/A      3689      G   /usr/bin/gnome-shell               79MiB |
|    0   N/A  N/A      4073      G   ...AAAAAAAAA= --shared-files       45MiB |
|    0   N/A  N/A      4657      G   ...AAAAAAAAA= --shared-files       60MiB |
|    0   N/A  N/A      5977      G   /usr/lib/firefox/firefox          135MiB |
+-----------------------------------------------------------------------------+
```

cuda和cudnn是用的conan安装：cuda/10.0.130@xx/stable, cudnn/7.6.4@xx/stable。我只能使用这两个，不可以换别的方式。
在我自己的电脑上可以正常运行，但是部署在同事电脑上的时候出现问题。试了不同的安装方式(cu101)，报错是一样的：
```bash
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
/usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0630 10:47:54.273962 30112 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0630 10:47:54.276033 30112 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/l.aigner/.local/lib/python3.6/site-packages/paddle/utils/install_check.py", line 196, in run_check
    _run_static_single(use_cuda)
  File "/home/l.aigner/.local/lib/python3.6/site-packages/paddle/utils/install_check.py", line 124, in _run_static_single
    exe.run(startup_prog)
  File "/home/l.aigner/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/home/l.aigner/.local/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/l.aigner/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/home/l.aigner/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1239, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/l.aigner/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1329, in _run_program
    [fetch_var_name])
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. An unsupported value or parameter was passed to the function (a negative vector size, for example).  (at /paddle/paddle/fluid/platform/cuda_helper.h:107)


```

**Comment by kaixin-bai** [comment]
在出问题的这台电脑上最开始是可以跑的，但是会随机报另一个错，中途paddle安装错了一个版本(cu11.1)然后卸载重装后就不行了

**Comment by kaixin-bai** [comment]
问题解决，因为同事电脑上python的默认环境是3.9，把安装方式换掉让它安装在python3.6里就好了。
