### ISSUE TITLE
OSError: (External)  Cuda error(700), an illegal memory access was encountered exe.run(fetch_var_names, return_merged)._move_to_list()

### ISSUE THREAD

**Issue by Melon-Zhou** [PaddlePaddle/Paddle#33888]
- 标题：CNN网络静态图训练过程出现Cuda error(700)
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu-2.1.0.post101
    2）GPU：Tesla V100 ， 16G显存，NVIDIA-SMI 418.67 ， Driver Version: 418.67，CUDA Version: 10.1
  
    3）系统环境
![image](https://user-images.githubusercontent.com/16741165/124062420-4dfd5e80-da63-11eb-8e2a-6921410dd7cd.png)

- 训练信息
    1）单机单卡：复现环境可私聊。
同样的代码，cpu下可以正常运行，gpu则会运行失败。如果当设定了export GLOG_v=4，则gpu也能正常运行。

**Comment by Melon-Zhou** [comment]
![image](https://user-images.githubusercontent.com/16741165/124065045-8ce1e300-da68-11eb-8a11-b3b76b197f7c.png)
![image](https://user-images.githubusercontent.com/16741165/124065086-9a976880-da68-11eb-98f2-210e260bccd4.png)

**Comment by Melon-Zhou** [comment]
报错信息中的文档链接：
https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038

**Comment by LDOUBLEV** [comment]
排查发现和环境有关系，可能和环境缺少一些依赖库有关系，测试发现在cuda10.2 + cudnn7.6 + paddle2.1上可以正常运行
