### ISSUE TITLE
安装报错OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. 

### ISSUE THREAD

**Issue by guantongpeng** [PaddlePaddle/Paddle#34385]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1
    2）CPU：Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz
    3）GPU：GPU3090 CUDA11.2 CUDNN8.1
    4）系统环境：Ubuntu18、Python3.7

- 安装方式信息：
新创建了一个conda环境，然后在环境中使用pip安装:python -m pip install paddlepaddle-gpu==2.1.1.post112 -f 

安装完成之后测试：
import paddle
paddle.utils.run_check()
报错：
![image](https://user-images.githubusercontent.com/52579652/126952843-c79d3b74-c195-4496-9879-f21b1556462a.png)

**Comment by SWHL** [comment]
我也遇见同样的问题
- 版本
    - CUDA 11.4
    - Docker运行
    - python 3.7
    
- 安装完成之后测试：
```python
import paddle
paddle.utils.run_check()
```
报错同样是这个

**Comment by LayBrick** [comment]
我也遇到了这个问腿
版本
cuda11.2
pip 运行
python3.7
cudnn 8.2

![image](https://user-images.githubusercontent.com/91247260/136315594-174b962a-fa89-47ff-8118-fda1d3aed04f.png)

**Comment by guantongpeng** [comment]
> 我也遇见同样的问题
> 
> * 版本
>   
>   * CUDA 11.4
>   * Docker运行
>   * python 3.7
> * 安装完成之后测试：
> 
> ```python
> import paddle
> paddle.utils.run_check()
> ```
> 
> 报错同样是这个

试着使用conda安装看看行不行

**Comment by guantongpeng** [comment]
> 我也遇到了这个问腿 版本 cuda11.2 pip 运行 python3.7 cudnn 8.2
> 
> ![image](https://user-images.githubusercontent.com/91247260/136315594-174b962a-fa89-47ff-8118-fda1d3aed04f.png)

使用conda安装试试

**Comment by zhijianli** [comment]
我也遇见同样的问题

版本

CUDA 11.2　
cudnn 8.1.1 
paddlepaddle-gpu 版本：2.3.0.post112
python 3.8
安装完成之后测试：

import paddle
paddle.utils.run_check()

报错同样是这个

**Comment by gjj123** [comment]
我也遇见同样的问题

版本
CUDA 11.0　
cudnn 8.0.4
paddlepaddle-gpu 版本：2.3.0.post110
python 3.6.8
机器NVIDIA A100
安装完成之后测试：

import paddle
paddle.utils.run_check()

报错同样是这个

**Comment by hohdiy** [comment]
我也是相同的错误，求救啊，没有人支招么？

**Comment by gjj123** [comment]
> 我也是相同的错误，求救啊，没有人支招么？

换个paddle 版本试试我从2.3换成2.2 就可以了

**Comment by zhaoyantao-murray** [comment]
改用cuda10.2，cudnn7.6.5，python3.6配置paddle环境解决了问题
