### ISSUE TITLE
cudnn64_7.dll 依赖问题

### ISSUE THREAD

**Issue by hide-in-code** [PaddlePaddle/Paddle#34837]
问题描述：
我选择的版本是windows，gpu版本(2.1稳定版)，cuda版本按官方推荐选择10.2，按照nvidia官方流程安装了cudnn加速库，安装完之后发现报如下错误：
![image](https://user-images.githubusercontent.com/19517597/129135510-d0d23abd-dd34-488e-8334-2a5e9b80aad8.png)

起初以为是环境变量的问题，但是我的环境变量设置是正确的，nvcc命令能正常执行；后来发现报错中提到paddlepaddle依赖的库是cudnn64_7.dll，我在cuda的目录下搜索，找到的是cudnn64_8.dll，将该库重命名到cudnn64_7.dll之后，重新启动训练，已经可以正常使用，算是一个隐藏的坑，这个对新手查错非常困难，我在官方论坛内也发现有人发帖(今年三月份)提这个问题，但没有回复(github的issue中也有)。希望官方能关注一下这个问题，并能做出一些兼容
![image](https://user-images.githubusercontent.com/19517597/129135566-06d7540e-785f-4dea-873d-a945cac340bd.png)

**Comment by hide-in-code** [comment]
将 cudnn64_8.dll 重命名至 cudnn64_7.dll 之后已经可以正常启动训练。但这种方式毕竟不好

**Comment by hide-in-code** [comment]
经过和官方了解，发现是因为cudnn的版本安装有问题，官方推荐的版本为：[cudnn 7.6.5](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html)，我自己安装版本为 cudnn 8.2 所以导致动态库找不到(怪自己没好好读文档)，下载cudnn是，需要翻到之前发布的版本 https://developer.nvidia.com/rdp/cudnn-archive 中找到对应的版本。
