### ISSUE TITLE
复现SIGN出错

### ISSUE THREAD

**Issue by CAODH** [PaddlePaddle/Paddle#35411]
W0902 20:02:11.228497 1068467 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0902 20:02:11.283596 1068467 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    model = SIGN(args)
  File "/home/duanhua/projects/paddle/PaddleHelix/apps/drug_target_interaction/sign/model.py", line 41, in __init__
    self.input_layer = SpatialInputLayer(hidden_dim, cut_dist, activation=F.relu)
  File "/home/duanhua/projects/paddle/PaddleHelix/apps/drug_target_interaction/sign/layers.py", line 46, in __init__
    self.dist_embedding_layer = nn.Embedding(int(cut_dist)-1, hidden_dim, sparse=True)
  File "/home/duanhua/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1343, in __init__
    self.weight = self.create_parameter(
  File "/home/duanhua/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/duanhua/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/duanhua/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/home/duanhua/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 561, in __call__
    op = block.append_op(
  File "/home/duanhua/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2921, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/duanhua/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. An unsupported value or parameter was passed to the function (a negative vector size, for example).  (at /paddle/paddle/fluid/platform/cuda_helper.h:107)
  [operator < uniform_random > error]
复现百度的文章SIGN时报错，目前不知道什么原因

**Comment by CAODH** [comment]
cpu 上用 paddle.utils.run_check()没问题的
（slurm 集群）

**Comment by wawltor** [comment]
> cpu 上用 paddle.utils.run_check()没问题的
> （slurm 集群）


> cpu 上用 paddle.utils.run_check()没问题的
> （slurm 集群）

麻烦提供一下你现在的显卡类型，cudnn版本，cuda版本

**Comment by CAODH** [comment]
> > cpu 上用 paddle.utils.run_check()没问题的
> > （slurm 集群）
> 
> > cpu 上用 paddle.utils.run_check()没问题的
> > （slurm 集群）
> 
> 麻烦提供一下你现在的显卡类型，cudnn版本，cuda版本

cuda 11.2  cudnn 7.6.5 rtx 3080 
pytorch可以正常使用
![image](https://user-images.githubusercontent.com/53987775/131853386-8ed8b1f0-fb88-495e-a38d-586a29f9dfd3.png)

**Comment by wawltor** [comment]
> > > cpu 上用 paddle.utils.run_check()没问题的
> > > （slurm 集群）
> > 
> > 
> > > cpu 上用 paddle.utils.run_check()没问题的
> > > （slurm 集群）
> > 
> > 
> > 麻烦提供一下你现在的显卡类型，cudnn版本，cuda版本
> 
> cuda 11.2 cudnn 7.6.5 rtx 3080
> pytorch可以正常使用
> ![image](https://user-images.githubusercontent.com/53987775/131853386-8ed8b1f0-fb88-495e-a38d-586a29f9dfd3.png)

建议升好一下cudnn的版本  cuda11.2需要配合cudnn 8来使用

**Comment by CAODH** [comment]
> > > > cpu 上用 paddle.utils.run_check()没问题的
> > > > （slurm 集群）
> > > 
> > > 
> > > > cpu 上用 paddle.utils.run_check()没问题的
> > > > （slurm 集群）
> > > 
> > > 
> > > 麻烦提供一下你现在的显卡类型，cudnn版本，cuda版本
> > 
> > 
> > cuda 11.2 cudnn 7.6.5 rtx 3080
> > pytorch可以正常使用
> > ![image](https://user-images.githubusercontent.com/53987775/131853386-8ed8b1f0-fb88-495e-a38d-586a29f9dfd3.png)
> 
> 建议升好一下cudnn的版本 cuda11.2需要配合cudnn 8来使用

具体那个版本呢？方便说一下嘛。谢谢！

**Comment by wawltor** [comment]
> > > > > cpu 上用 paddle.utils.run_check()没问题的
> > > > > （slurm 集群）
> > > > 
> > > > 
> > > > > cpu 上用 paddle.utils.run_check()没问题的
> > > > > （slurm 集群）
> > > > 
> > > > 
> > > > 麻烦提供一下你现在的显卡类型，cudnn版本，cuda版本
> > > 
> > > 
> > > cuda 11.2 cudnn 7.6.5 rtx 3080
> > > pytorch可以正常使用
> > > ![image](https://user-images.githubusercontent.com/53987775/131853386-8ed8b1f0-fb88-495e-a38d-586a29f9dfd3.png)
> > 
> > 
> > 建议升好一下cudnn的版本 cuda11.2需要配合cudnn 8来使用
> 
> 具体那个版本呢？方便说一下嘛。谢谢！

cudnn版本升级8.1

**Comment by CAODH** [comment]
解决了！ cuda 11.3 cudnn 8.2.1

**Comment by CAODH** [comment]
> > > > > > cpu 上用 paddle.utils.run_check()没问题的
> > > > > > （slurm 集群）
> > > > > 
> > > > > 
> > > > > > cpu 上用 paddle.utils.run_check()没问题的
> > > > > > （slurm 集群）
> > > > > 
> > > > > 
> > > > > 麻烦提供一下你现在的显卡类型，cudnn版本，cuda版本
> > > > 
> > > > 
> > > > cuda 11.2 cudnn 7.6.5 rtx 3080
> > > > pytorch可以正常使用
> > > > ![image](https://user-images.githubusercontent.com/53987775/131853386-8ed8b1f0-fb88-495e-a38d-586a29f9dfd3.png)
> > > 
> > > 
> > > 建议升好一下cudnn的版本 cuda11.2需要配合cudnn 8来使用
> > 
> > 
> > 具体那个版本呢？方便说一下嘛。谢谢！
> 
> cudnn版本升
好了，谢谢！

**Comment by CAODH** [comment]
update cuda to 11.3 and cudnn to 8.21.1 will fix this problem ！
thanks all
