### ISSUE TITLE
paddlehub finetune时遇到OSError: (External)  Cublas error, `CUBLAS_STATUS_EXECUTION_FAILED`. The GPU program failed to execute. 

### ISSUE THREAD

**Issue by ZRSlayee** [PaddlePaddle/Paddle#36630]
在使用paddlehub finetune Ernie-GEN模型时，训练几个step会报如下错误：

Traceback (most recent call last):
  File "test.py", line 46, in <module>
    save_interval = 500)
  File "/home/gpu_user/zmh/virenv/paddle/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/home/gpu_user/.paddlehub/modules/ernie_gen/module.py", line 185, in finetune
    loss.backward()
  File "/home/gpu_user/zmh/virenv/paddle/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/gpu_user/zmh/virenv/paddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/gpu_user/zmh/virenv/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/home/gpu_user/zmh/virenv/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 239, in backward
    framework._dygraph_tracer())
OSError: (External)  Cublas error, `CUBLAS_STATUS_EXECUTION_FAILED`. The GPU program failed to execute. This is often caused by a launch failure of the kernel on the GPU, which can be caused by multiple reasons.  (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:40)

- 版本、环境信息：
    1）PaddlePaddle版本：2.1.3.post101
    2）PaddleHub版本：2.1.1
    3）GPU：TeslaM60，CUDA10.1，CUDnn7.6.4
    4）系统环境：ubuntu16.0，python3.7.5

参数设置如下：
new_model = model.finetune(
    train_path = "nlpcc_data/train.txt",
    dev_path = "nlpcc_data/test.txt",
    save_dir = "ernie_gen_summary", 
    use_gpu = True,
    max_steps = 1000, 
    batch_size = 1,
    max_encode_len = 800, 
    max_decode_len = 64, 
    learning_rate = 1e-6,
    warmup_proportion=0.1,
    weight_decay=0.1,
    noise_prob=0,
    label_smooth=0,
    beam_width=5,
    length_penalty=1.0,
    log_interval = 1,
    save_interval = 500)

p.s. 当我将学习率设置为5e-5时，loss和ppl会出现nan，并且会时不时报cudaSystemError: (Fatal) Operator elementwise_max raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered.

可否解答一下？谢谢。

**Comment by linjieccc** [comment]
您好，能否提供最小复现代码，我们复现后会尽快回复，谢谢！

**Comment by ZRSlayee** [comment]
> 您好，能否提供最小复现代码，我们复现后会尽快回复，谢谢！

您好，代码和数据已上传至百度网盘，下载后可直接运行，谢谢！
链接：https://pan.baidu.com/s/1iNbIlczq8bUrMwgBuRAbnA 
提取码：ys35

**Comment by linjieccc** [comment]
> > 您好，能否提供最小复现代码，我们复现后会尽快回复，谢谢！
> 
> 您好，代码和数据已上传至百度网盘，下载后可直接运行，谢谢！ 链接：https://pan.baidu.com/s/1iNbIlczq8bUrMwgBuRAbnA 提取码：ys35

缺少train.txt

**Comment by ZRSlayee** [comment]
> > > 您好，能否提供最小复现代码，我们复现后会尽快回复，谢谢！
> > 
> > 
> > 您好，代码和数据已上传至百度网盘，下载后可直接运行，谢谢！ 链接：https://pan.baidu.com/s/1iNbIlczq8bUrMwgBuRAbnA 提取码：ys35
> 
> 缺少train.txt

您好，train.txt和test.txt都在nlpcc_data文件夹下，运行test.py即可

**Comment by linjieccc** [comment]
经排查是`max_encode_len`设置过大导致的问题，我这边尝试将`max_encode_len`改为400，模型可以正常收敛。

**Comment by ZRSlayee** [comment]
> 经排查是`max_encode_len`设置过大导致的问题，我这边尝试将`max_encode_len`改为400，模型可以正常收敛。

能正常运行了，谢谢。我想请问一下，ernie-gen的最大输入是否有设置上限？

**Comment by linjieccc** [comment]
> > 经排查是`max_encode_len`设置过大导致的问题，我这边尝试将`max_encode_len`改为400，模型可以正常收敛。
> 
> 能正常运行了，谢谢。我想请问一下，ernie-gen的最大输入是否有设置上限？

这里module使用到的预训练模型是ernie-1.0，支持max length 512的输入，可以参考module代码：
https://github.com/PaddlePaddle/PaddleHub/blob/d4298260b1a35cd23cc85514ebaaf1975697c479/modules/text/text_generation/ernie_gen/module.py#L58

**Comment by ZRSlayee** [comment]
> > > 经排查是`max_encode_len`设置过大导致的问题，我这边尝试将`max_encode_len`改为400，模型可以正常收敛。
> > 
> > 
> > 能正常运行了，谢谢。我想请问一下，ernie-gen的最大输入是否有设置上限？
> 
> 这里module使用到的预训练模型是ernie-1.0，支持max length 512的输入，可以参考module代码： https://github.com/PaddlePaddle/PaddleHub/blob/d4298260b1a35cd23cc85514ebaaf1975697c479/modules/text/text_generation/ernie_gen/module.py#L58

已解决，谢谢！
