### ISSUE TITLE
安装错误：测试通过，推理出错

### ISSUE THREAD

**Issue by chereyk** [PaddlePaddle/Paddle#36681]
1）PaddlePaddle版本：2.1.3，来源于官网安装
    2）GPU：GPU型号：RTX3060，CUDA：11.0和CUDNN版本号：8.0.2
    3）系统环境：win10专业版、Python3.7。
- 安装方式信息：
1）pip安装
- 问题描述：安装完成之后使用cpu推理正常运行，调用paddle.utils.run_check()正常通过，但使用gpu推理时出现报错如下：
Traceback (most recent call last):
  File "F:/project/paddleocr/tools/infer/predict_system.py", line 192, in <module>
    main(args)
  File "F:/project/paddleocr/tools/infer/predict_system.py", line 125, in main
    res = text_sys(img)
  File "F:/project/paddleocr/tools/infer/predict_system.py", line 59, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "F:\project\paddleocr\tools\infer\predict_det.py", line 195, in __call__
    self.predictor.run()
OSError: In user code:

    File "tools/export_model.py", line 75, in <module>
      main()
    File "tools/export_model.py", line 70, in main
      paddle.jit.save(model, save_path)
    File "<decorator-gen-60>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
      concrete_program = static_func.concrete_program
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
      concrete_program, _ = self.get_concrete_program(*input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-58>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 625, in from_func_spec
      outputs = static_func(*inputs)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 74, in forward
      x = self.backbone(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpfjz7mcq2.py", line 22, in forward
      for_loop_condition_0, for_loop_body_0, [__for_loop_var_index_0, y])
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 44, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 58, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/backbones/det_resnet_vd.py", line 278, in forward
      y = block(y)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 86, in forward
      input = layer(input)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/backbones/det_resnet_vd.py", line 163, in forward
      y = self.conv0(inputs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/backbones/det_resnet_vd.py", line 67, in forward
      y = self._conv(inputs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 644, in forward
      use_cudnn=self._use_cudnn)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 144, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2846, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1931, in __init__
      for frame in traceback.extract_stack():

    ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at C:/home/workspace/Paddle_release/paddle/fluid/operators/fused/conv_fusion_op.cu:306)
      [operator < conv2d_fusion > error]

Process finished with exit code 1

-输出的其他信息：

'env' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
W1025 11:29:27.494096 18496 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I1025 11:29:27.555927 18496 graph_pattern_detector.cc:91] ---  detected 24 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I1025 11:29:27.575873 18496 graph_pattern_detector.cc:91] ---  detected 24 subgraphs
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I1025 11:29:27.581859 18496 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I1025 11:29:27.610752 18496 memory_optimize_pass.cc:199] Cluster name : conv2d_transpose_4.tmp_0  size: 26214400
I1025 11:29:27.610752 18496 memory_optimize_pass.cc:199] Cluster name : conv2d_60.tmp_0  size: 102400
I1025 11:29:27.610752 18496 memory_optimize_pass.cc:199] Cluster name : elementwise_add_8.tmp_0  size: 26214400
I1025 11:29:27.610752 18496 memory_optimize_pass.cc:199] Cluster name : tmp_2  size: 26214400
I1025 11:29:27.610752 18496 memory_optimize_pass.cc:199] Cluster name : tmp_1  size: 6553600
I1025 11:29:27.610752 18496 memory_optimize_pass.cc:199] Cluster name : nearest_interp_v2_5.tmp_0  size: 6553600
I1025 11:29:27.610752 18496 memory_optimize_pass.cc:199] Cluster name : pool2d_3.tmp_0  size: 409600
I1025 11:29:27.610752 18496 memory_optimize_pass.cc:199] Cluster name : x  size: 4915200
I1025 11:29:27.610752 18496 memory_optimize_pass.cc:199] Cluster name : relu_4.tmp_0  size: 1638400
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I1025 11:29:27.632716 18496 analysis_predictor.cc:636] ======= optimize end =======
I1025 11:29:27.632716 18496 naive_executor.cc:98] ---  skip [feed], feed -> x
I1025 11:29:27.633718 18496 naive_executor.cc:98] ---  skip [conv2d_transpose_4.tmp_0], fetch -> fetch
'env' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I1025 11:29:29.007040 18496 graph_pattern_detector.cc:91] ---  detected 39 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
I1025 11:29:29.144671 18496 graph_pattern_detector.cc:91] ---  detected 1 subgraphs
e[32m--- Running IR pass [fc_fuse_pass]e[0m
I1025 11:29:29.145673 18496 graph_pattern_detector.cc:91] ---  detected 1 subgraphs
e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I1025 11:29:29.153648 18496 graph_pattern_detector.cc:91] ---  detected 39 subgraphs
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I1025 11:29:29.163622 18496 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I1025 11:29:29.233426 18496 memory_optimize_pass.cc:199] Cluster name : lstm_0.tmp_3  size: 1
I1025 11:29:29.233426 18496 memory_optimize_pass.cc:199] Cluster name : batch_norm_2.tmp_2  size: 819200
I1025 11:29:29.233426 18496 memory_optimize_pass.cc:199] Cluster name : lstm_0.tmp_2  size: 4096
I1025 11:29:29.233426 18496 memory_optimize_pass.cc:199] Cluster name : batch_norm_2.tmp_3  size: 819200
I1025 11:29:29.233426 18496 memory_optimize_pass.cc:199] Cluster name : batch_norm_8.tmp_3  size: 204800
I1025 11:29:29.233426 18496 memory_optimize_pass.cc:199] Cluster name : relu_4.tmp_0  size: 204800
I1025 11:29:29.233426 18496 memory_optimize_pass.cc:199] Cluster name : lstm_0.tmp_1  size: 4096
I1025 11:29:29.233426 18496 memory_optimize_pass.cc:199] Cluster name : x  size: 38400
I1025 11:29:29.233426 18496 memory_optimize_pass.cc:199] Cluster name : lstm_0._generated_var_0  size: 1
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I1025 11:29:29.263360 18496 analysis_predictor.cc:636] ======= optimize end =======
I1025 11:29:29.263360 18496 naive_executor.cc:98] ---  skip [feed], feed -> x
I1025 11:29:29.264353 18496 naive_executor.cc:98] ---  skip [batch_norm_2.tmp_2], fetch -> fetch
W1025 11:29:29.288285 18496 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.0
W1025 11:29:29.305241 18496 device_context.cc:422] device: 0, cuDNN Version: 8.0.

**Comment by pollyyan** [comment]
您执行的具体指令是什么呀～

**Comment by chereyk** [comment]
> 您执行的具体指令是什么呀～

直接在pycharm中run tools/infer/predict_system.py

**Comment by pollyyan** [comment]
您好，我这边在windows中paddlepaddle-gpu=2.1.3.post112、CUDA11.2 py37运行是正常的：
![image](https://user-images.githubusercontent.com/38637686/138651149-92f7e892-2821-4d61-9a5a-cb27b6a4a8f8.png)

**Comment by chereyk** [comment]
> 您好，我这边在windows中paddlepaddle-gpu=2.1.3.post112、CUDA11.2 py37运行是正常的： ![image](https://user-images.githubusercontent.com/38637686/138651149-92f7e892-2821-4d61-9a5a-cb27b6a4a8f8.png)

请问您使用的gpu是什么型号的呢，cudnn是哪个版本？

**Comment by pollyyan** [comment]
GPU型号：GeForce RTX 3080，cudnn版本：8.1.0

**Comment by chereyk** [comment]
> GPU型号：GeForce RTX 3080，cudnn版本：8.1.0

非常感谢，按您的配置重新安装之后可以正常训练了
