### ISSUE TITLE
安装paddle环境时编译报错，error code is 126

### ISSUE THREAD

**Issue by genjiyep** [PaddlePaddle/Paddle#38004]
下载的paddle为最新2.2版本，python版本3.9，cuda安装的10.2，报错为RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
下图1为编译报错截图
![屏幕截图 2021-12-09 144138](https://user-images.githubusercontent.com/95277066/145357141-bc12ab9c-ad72-4fc1-98e1-72fee512ad60.png)
                图2和图3是cuda与cudnn测试结果
![1](https://user-images.githubusercontent.com/95277066/145358064-af0916d5-0537-4e3b-ade4-9fcc71aa2e8e.png)
![2](https://user-images.githubusercontent.com/95277066/145358079-722029da-12c8-46bc-8ce5-2e414477c0a7.png)
![cuda](https://user-images.githubusercontent.com/95277066/145358089-c6aad7df-2c7c-48b1-a747-91e2b6c1b673.png)

想问一下我怎么才能解决这个问题呢？

**Comment by haozech** [comment]
建议升级一下cudnn版本，10.2的cuda版本应该需要cudnn 8.2.2的版本。 参考这里 https://blog.csdn.net/qq_43800855/article/details/120059808 。
另外paddle 安装的wheel包可以参考这里 https://blog.csdn.net/qq_43800855/article/details/120059808

**Comment by DDDivano** [comment]
cudnn的版本是哪一个图？

**Comment by genjiyep** [comment]
已经解决了，是cudnn版本问题，缺少一个dll文件

**Comment by insider-charlie** [comment]
> cudnn的版本是哪一个图？

执行`nvcc --version`可以查看cuda版本
在安装对应版本的cudnn后, 可以通过官网https://www.paddlepaddle.org.cn/ 安装正确版本的paddlepaddle-gpu
