### ISSUE TITLE
cuda显存较小，如何指定使用cpu加载模型，进行训练？

### ISSUE THREAD

**Issue by rfslzy** [PaddlePaddle/Paddle#38281]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu   2.2.1
    2）CPU：AMD R7 5800HS
    3）GPU：NVIDIA MX450, CUDA 10.2, CUDnn 7.6
    4）系统环境：win10，python3.7
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 模型信息
    1）模型名称
 2）使用数据集名称 3）使用算法名称 4）模型链接
- 复现信息：如为报错，请给出复现环境、复现步骤
```
from paddle.vision.models import vgg16
model = vgg16(pretrained=True)  # cuda显存不够
```
报错如下
```
Out of memory error on GPU 0. Cannot allocate 64.000244MB memory on GPU 0, 1.999756GB memory has been allocated and available memory is only 0.000000B.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
```

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

目前显卡显存较小，请问如何指定使用cpu加载模型，进行训练呢？

**Comment by gongel** [comment]
你好，通过`set_device`来设置运行的设备
```python
paddle.set_device('cpu')
```

**Comment by rfslzy** [comment]
问题已解决，谢谢指点

> 你好，通过`set_device`来设置运行的设备
> 
> ```python
> paddle.set_device('cpu')
> ```
