### ISSUE TITLE
【论文复现】OSError: (External) CUDNN error(7), CUDNN_STATUS_MAPPING_ERROR. 

### ISSUE THREAD

**Issue by CuberrChen** [PaddlePaddle/Paddle#38618]
- 标题：特定CUDA版本下稳定复现CUDNN error
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.1
    2）CPU：---
    3）GPU：V100 16G/32G
    4）系统环境：ubuntu 16.04，python 3.7

- 训练信息
    1）单机，单卡/多卡
    2）显存信息 16G/32G
    3）Operator信息
- 复现信息：代码中所有算子都是直接调用Paddle提供的卷积块，主要包含Conv3D，BN3D，Conv3DTranspose等模块。
- 问题描述：在CUDA版本为10.1/10.2时，稳定报如下错误。但是当CUDA版本为11.0以上版本时，可以正常训练完成。
  File "train_mgpu.py", line 284, in train
    loss.backward()
  File "<decorator-gen-128>", line 2, in backward
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 249, in backward
    framework._dygraph_tracer())
OSError: (External) CUDNN error(7), CUDNN_STATUS_MAPPING_ERROR. 
  [Hint: 'CUDNN_STATUS_MAPPING_ERROR'.  An access to GPU memory space failed, which is usually caused by a failure to bind a texture.  To correct, prior to the function call, unbind any previously bound textures.  Otherwise, this may indicate an internal error/bug in the library.  ] (at /paddle/paddle/fluid/operators/conv_cudnn_op.cu:758)

**Comment by CuberrChen** [comment]
#37778 也提到了该问题。

**Comment by wangxinxin08** [comment]
你好，你的cudnn版本是什么？初步推测是cudnn版本和cuda版本不匹配导致的

**Comment by CuberrChen** [comment]
@wangxinxin08 

使用的是AIStudio提供的Notebook或者多卡脚本环境。

在如下环境下是正常的。
```
- **CUDA 版本（nvidia-smi指令）**：NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0
- **Paddle提供的获取环境信息的env_summary.py脚本得到的环境信息**：
Paddle version: 2.2.1
Paddle With CUDA: True
OS: Ubuntu 16.04
Python version: 3.7.4
CUDA version: 10.1.243
cuDNN version: 7.3.1
Nvidia driver version: 450.51.06
```

但是下面的环境就会出错。
比如下面这个多卡脚本环境：
```
-  **CUDA 版本（nvidia-smi指令）**：NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1
- **Paddle提供的获取环境信息的env_summary.py脚本得到的环境信息**：
Paddle version: 2.2.1
Paddle With CUDA: True
OS: CentOS 6.10
Python version: 3.7.0
CUDA version: 10.1.243
cuDNN version: None.None.None
Nvidia driver version: 418.67

```
看起来并不能通过env_summary得到多卡环境下的cuDNN信息..

**Comment by wangxinxin08** [comment]
@CuberrChen 可以使用以下命令`find / -name "*cudnn*.so*"`查找下cudnn的版本

**Comment by CuberrChen** [comment]
nvidia-smi：
```
Fri Dec 31 13:56:35 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   45C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:07:00.0 Off |                    0 |
| N/A   40C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:08:00.0 Off |                    0 |
| N/A   37C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:09:00.0 Off |                    0 |
| N/A   47C    P0    45W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
nvcc -V：
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
find / -name "*cudnn*.so*"：
```
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.3.1
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so
```

env_summary:
```
****************************************
Paddle version: 2.2.1
Paddle With CUDA: True
OS: CentOS 6.10
Python version: 3.7.0
CUDA version: 10.1.243
cuDNN version: None.None.None
Nvidia driver version: 418.67

```
@wangxinxin08 
不过。怎么会存在cuda版本和cudnn版本不匹配的问题，都是Aisdtudio配好的环境，运行其他的程序也没问题的。
但是想来也不是我脚本code的问题呀，因为在cuda11.0的时候可以正常训练....

**Comment by CuberrChen** [comment]
从这些信息中能推断出问题在哪里吗？或者能提供一个暂时的解决办法吗？ 目前需求多GPU训练，但是多卡脚本环境都是CUDA10.1/ 10.2。

**Comment by wangxinxin08** [comment]
可以提供下任务编号，AI studio的同学帮你定位一下问题

**Comment by CuberrChen** [comment]
@wangxinxin08 
多卡任务：114251

**Comment by wangxinxin08** [comment]
@CuberrChen 你训练报错的环境是AI studio提供的环境吗？

**Comment by CuberrChen** [comment]
@wangxinxin08 是啊。无论是Notebook环境还是多卡脚本环境，都出现了这个错误。

**Comment by wangxinxin08** [comment]
> @wangxinxin08 是啊。无论是Notebook环境还是多卡脚本环境，都出现了这个错误。

能分享下你的项目吗？

**Comment by CuberrChen** [comment]
项目已经公开。后面发现当单张卡的batchsize小于等于2时所有环境就都不会出现这个错误。不知道是Paddle的问题还是CUDNN的问题。

项目链接：
https://aistudio.baidu.com/aistudio/projectdetail/3291060?contributionType=1
