### ISSUE TITLE
使用官方推理模型进行预测时报错：缺少（cudnn64_7.dll）

### ISSUE THREAD

**Issue by Fallinloverain** [PaddlePaddle/Paddle#39001]
- 标题：使用官方推理模型进行预测时报错：缺少（cudnn64_7.dll）
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：
    3）GPU：3080，CUDA 11.5和CUDNN 8.3.1
    4）系统环境：win11，Python 3.8.12
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：
当使用指令运行推理模型时，出现如下报错
![image](https://user-images.githubusercontent.com/94366337/149762146-46030796-bb20-4440-aa28-979ee9a4b01d.png)
我查询过网上类似问题，下载cuda 10.2和cudnn 7可以解决，但是现在cuda10.2已经停止下载了，而且30系列显卡最低使用cuda 11，这应该如何解决呢，谢谢

**Comment by Fallinloverain** [comment]
已解决，解决方法：下载cuda 11.1版本和 cudnn 8.1.1，有且只有这版本可以同时兼容windows11和30系列显卡，安装指令用的是python -m pip install paddlepaddle-gpu==2.2.1.post111 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
