### ISSUE TITLE
2021百度多形态事件抽取官方的aistudio版本现在跑不通了？是什么原因呢

### ISSUE THREAD

**Issue by lujiang001108** [PaddlePaddle/Paddle#39004]
aistudio@jupyter-756224-3421635:~$ bash run_duee_fin.sh trigger_train
check and create directory
dir ./ckpt exist
dir ./ckpt/DuEE-Fin exist
dir ./submit exist

start DuEE-Fin trigger train
W0117 20:06:12.927531 19293 init.cc:143] Compiled with WITH_GPU, but no GPU found in runtime.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py:312: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: 0
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: sequence_labeling.py
training_script_args: ['--num_epoch', '20', '--learning_rate', '5e-5', '--tag_path', './conf/DuEE-Fin/trigger_tag.dict', '--train_data', './data/DuEE-Fin/trigger/train.tsv', '--dev_data', './data/DuEE-Fin/trigger/dev.tsv', '--test_data', './data/DuEE-Fin/trigger/test.tsv', '--predict_data', './data/DuEE-Fin/sentence/test.json', '--do_train', 'True', '--do_predict', 'False', '--max_seq_len', '300', '--batch_size', '4', '--skip_step', '10', '--valid_step', '50', '--checkpoints', './ckpt/DuEE-Fin/trigger', '--init_ckpt', './ckpt/DuEE-Fin/trigger/best.pdparams', '--predict_save_path', './ckpt/DuEE-Fin/trigger/test_pred.json', '--device', 'gpu']
worker_num: None
workers: 
------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/launch.py", line 16, in <module>
    launch.launch()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/fleet/launch.py", line 596, in launch
    args)  # which_distributed_mode must modify args.backend
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/fleet/launch.py", line 383, in which_distributed_mode
    accelerators = fluid.core.get_cuda_device_count()
OSError: (External) CUDA error(35), CUDA driver version is insufficient for CUDA runtime version. 
  [Hint: 'cudaErrorInsufficientDriver'. This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:107)

end DuEE-Fin trigger train

**Comment by youth123** [comment]
我们会安排具体人员查看

**Comment by youth123** [comment]
那个请问是ai studio的哪一个具体用例呢

**Comment by lujiang001108** [comment]
老师好，就是2021LIC多形态信息抽取中的事件抽取代码。网址：https://aistudio.baidu.com/aistudio/projectdetail/1639964
















在 2022-01-19 16:53:51，"李季" ***@***.***> 写道：

那个请问是ai studio的哪一个具体用例呢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by linjieccc** [comment]
您好，应该是对paddlepaddle版本进行了手动升级导致的AIStudio环境cuda版本过低的问题。我们对该AIStudio项目进行了升级，您可以用最新版本再运行下哈，有问题随时反馈，谢谢

**Comment by lujiang001108** [comment]
更新了paddlepaddle-gpu版本到2.2.0，还是报错如下。还有是，官方可以修复一下嘛，你们在你们的网址里面现在能跑通吗？
















在 2022-03-02 19:56:26，"Linjie Chen" ***@***.***> 写道：

您好，应该是对paddlepaddle版本进行了手动升级导致的AIStudio环境cuda版本过低的问题。我们对该AIStudio项目进行了升级，您可以用最新版本再运行下哈，有问题随时反馈，谢谢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by linjieccc** [comment]
试下从
https://aistudio.baidu.com/aistudio/projectdetail/1639964
这里启动一个新的环境，重新运行一下项目哈，验证过可以正常运行

**Comment by lujiang001108** [comment]
老师，我从您给的链接进去的，您看下这个报错是什么意思。我总觉得还是版本问题，您没有问题吗？













在 2022-03-12 17:35:59，"Linjie Chen" ***@***.***> 写道：

试下从
https://aistudio.baidu.com/aistudio/projectdetail/1639964
这里启动一个新的环境，重新运行一下项目哈，验证过可以正常运行

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
