### ISSUE TITLE
paddle.get_cudnn_version()报错：code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ziyuwzf** [PaddlePaddle/Paddle#39102]
- 标题：paddle.get_cudnn_version()报错：code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory
- 版本、环境信息：
    1）PaddlePaddle版本：2.2
    2）CPU：请提供CPU型号，
    3）GPU：2080，裸机CUDA11.2和CUDNN7.6.1，
    4）系统环境：请docker容器内
- 安装方式信息：
1）非paddle官方docker容器内通过pip安装
- 问题信息：
描述：
在docker市场中，找到tensorflow的镜像，通过镜像启动容器，进入容器后通过pip安装paddlepaddle-gpu==2.2。进入python终端，import paddle正常。在此容器内，可以正常通过nvcc -V获取cuda版本，其他深度学习库正常运作。
代码：
import paddle
print(paddle.get_cudnn_version())
日志：
W0121 11:28:26.123500   524 dynamic_loader.cc:287] The third-party dynamic library (libcudnn.so) that Paddle depends on isnot configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
None

**Comment by jim19930609** [comment]
应该是LD_LIBRARY_PATH路径设置问题，或者libcudnn.so没有安装在默认路径。可以麻烦您运行：find / -name libcudnn.so，看一下系统内libcudnn.so的路径吗？
如果该指令没有返回结果则意味着您的机器上没有安装CUDNN，需要重新安装。
如果有返回结果请设置：export LD_LIBRARY_PATH={找到的libcudnn.so路径}:${LD_LIBRARY_PATH}

**Comment by ziyuwzf** [comment]
> 

物理机的cuda和cudnn环境都是好的，文件都有，正常使用。在tensorflow的镜像生成的容器里面，手动安装paddlepaddle-gpu>=2.0就出现了这种错误。低版本的paddlepaddle-gpu没试过，担心版本过低。

**Comment by ziyuwzf** [comment]
> 应该是LD_LIBRARY_PATH路径设置问题，或者libcudnn.so没有安装在默认路径。可以麻烦您运行：find / -name libcudnn.so，看一下系统内libcudnn.so的路径吗？ 如果该指令没有返回结果则意味着您的机器上没有安装CUDNN，需要重新安装。 如果有返回结果请设置：export LD_LIBRARY_PATH={找到的libcudnn.so路径}:${LD_LIBRARY_PATH}



> * 标题：paddle.get_cudnn_version()报错：code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory
> * 版本、环境信息：
>      1）PaddlePaddle版本：2.2
>      2）CPU：请提供CPU型号，
>      3）GPU：2080，裸机CUDA11.2和CUDNN7.6.1，
>      4）系统环境：请docker容器内
> * 安装方式信息：
>   1）非paddle官方docker容器内通过pip安装
> * 问题信息：
>   描述：
>   在docker市场中，找到tensorflow的镜像，通过镜像启动容器，进入容器后通过pip安装paddlepaddle-gpu==2.2。进入python终端，import paddle正常。在此容器内，可以正常通过nvcc -V获取cuda版本，其他深度学习库正常运作。
>   代码：
>   import paddle
>   print(paddle.get_cudnn_version())
>   日志：
>   W0121 11:28:26.123500   524 dynamic_loader.cc:287] The third-party dynamic library (libcudnn.so) that Paddle depends on isnot configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
>   Suggestions:
>   
>   1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
>   2. Configure third-party dynamic library environment variables as follows:
>   
>   
>   * Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
>   * Windows: set PATH by `set PATH=XXX;
>     None

通过cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2命令，物理机执行成功，但是在tensorflow的容器内和paddle官方的容器内执行均不成功，没有cudnn.h相关文件

**Comment by jim19930609** [comment]
> > 应该是LD_LIBRARY_PATH路径设置问题，或者libcudnn.so没有安装在默认路径。可以麻烦您运行：find / -name libcudnn.so，看一下系统内libcudnn.so的路径吗？ 如果该指令没有返回结果则意味着您的机器上没有安装CUDNN，需要重新安装。 如果有返回结果请设置：export LD_LIBRARY_PATH={找到的libcudnn.so路径}:${LD_LIBRARY_PATH}
> 
> > * 标题：paddle.get_cudnn_version()报错：code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory
> > * 版本、环境信息：
> >      1）PaddlePaddle版本：2.2
> >      2）CPU：请提供CPU型号，
> >      3）GPU：2080，裸机CUDA11.2和CUDNN7.6.1，
> >      4）系统环境：请docker容器内
> > * 安装方式信息：
> >   1）非paddle官方docker容器内通过pip安装
> > * 问题信息：
> >   描述：
> >   在docker市场中，找到tensorflow的镜像，通过镜像启动容器，进入容器后通过pip安装paddlepaddle-gpu==2.2。进入python终端，import paddle正常。在此容器内，可以正常通过nvcc -V获取cuda版本，其他深度学习库正常运作。
> >   代码：
> >   import paddle
> >   print(paddle.get_cudnn_version())
> >   日志：
> >   W0121 11:28:26.123500   524 dynamic_loader.cc:287] The third-party dynamic library (libcudnn.so) that Paddle depends on isnot configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
> >   Suggestions:
> >   
> >   1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
> >   2. Configure third-party dynamic library environment variables as follows:
> >   
> >   
> >   * Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
> >   * Windows: set PATH by `set PATH=XXX;
> >     None
> 
> 通过cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2命令，物理机执行成功，但是在tensorflow的容器内和paddle官方的容器内执行均不成功，没有cudnn.h相关文件

从这个描述来看，应该是物理机内安装了cudnn，但是容器内cudnn没有安装或者不是在/usr/local/cuda/路径下。如果是Paddle官方容器的话请选择带有cuda镜像的类似：2.0.2-gpu-cuda11.0-cudnn8

另外从报错信息看和cudnn.h无关，应该是找不到动态库libcudnn.so。简单的检查容器内是否有安装cudnn支持的方法是运行：find / -name libcudnn.so，看是否有返回

**Comment by ziyuwzf** [comment]
> > > 应该是LD_LIBRARY_PATH路径设置问题，或者libcudnn.so没有安装在默认路径。可以麻烦您运行：find / -name libcudnn.so，看一下系统内libcudnn.so的路径吗？ 如果该指令没有返回结果则意味着您的机器上没有安装CUDNN，需要重新安装。 如果有返回结果请设置：export LD_LIBRARY_PATH={找到的libcudnn.so路径}:${LD_LIBRARY_PATH}
> > 
> > 
> > > * 标题：paddle.get_cudnn_version()报错：code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory
> > > * 版本、环境信息：
> > >      1）PaddlePaddle版本：2.2
> > >      2）CPU：请提供CPU型号，
> > >      3）GPU：2080，裸机CUDA11.2和CUDNN7.6.1，
> > >      4）系统环境：请docker容器内
> > > * 安装方式信息：
> > >   1）非paddle官方docker容器内通过pip安装
> > > * 问题信息：
> > >   描述：
> > >   在docker市场中，找到tensorflow的镜像，通过镜像启动容器，进入容器后通过pip安装paddlepaddle-gpu==2.2。进入python终端，import paddle正常。在此容器内，可以正常通过nvcc -V获取cuda版本，其他深度学习库正常运作。
> > >   代码：
> > >   import paddle
> > >   print(paddle.get_cudnn_version())
> > >   日志：
> > >   W0121 11:28:26.123500   524 dynamic_loader.cc:287] The third-party dynamic library (libcudnn.so) that Paddle depends on isnot configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
> > >   Suggestions:
> > >   
> > >   1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
> > >   2. Configure third-party dynamic library environment variables as follows:
> > >   
> > >   
> > >   * Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
> > >   * Windows: set PATH by `set PATH=XXX;
> > >     None
> > 
> > 
> > 通过cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2命令，物理机执行成功，但是在tensorflow的容器内和paddle官方的容器内执行均不成功，没有cudnn.h相关文件
> 
> 从这个描述来看，应该是物理机内安装了cudnn，但是容器内cudnn没有安装或者不是在/usr/local/cuda/路径下。如果是Paddle官方容器的话请选择带有cuda镜像的类似：2.0.2-gpu-cuda11.0-cudnn8
> 
> 另外从报错信息看和cudnn.h无关，应该是找不到动态库libcudnn.so。简单的检查容器内是否有安装cudnn支持的方法是运行：find / -name libcudnn.so，看是否有返回

给镜像重新安装cudnn后，问题解决。是tensorflow的官方镜像缺失cudnn文件出了问题。
