### ISSUE TITLE
Windows下安装GPU版本的paddlepaddle，paddle.utils.run_check()验证失败

### ISSUE THREAD

**Issue by gyg123456** [PaddlePaddle/Paddle#39256]
- 版本、环境信息
    1）PaddlePaddle版本：paddlepaddle-gpu：2.2.2
    2）CUDA版本：10.2
    3）CUDNN版本：cuDNN v7.6.5 (November 18th, 2019), for CUDA 10.2
    4）CPU：AMD Ryzen 7 5800H with Radeon Graphics
    5）GPU：NVIDIA GeForce RTX 3060 Laptop GPU
    6）操作系统：Windows 10 家庭中文版 + Python 3.6.15

- 安装方式信息
    python -m pip install paddlepaddle-gpu==2.2.2 -i https://mirror.baidu.com/pypi/simple

- 复现信息：命令行下import paddle成功但paddle.utils.run_check()验证安装失败
- 问题描述
`(paddle_gpu) C:\Users\GYG>python
Python 3.6.15 (default, Dec  3 2021, 18:25:24) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0126 22:57:04.184931  6884 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 10.2
W0126 22:57:04.239192  6884 device_context.cc:465] device: 0, cuDNN Version: 7.6.
W0126 23:13:17.324173  6884 operator.cc:248] uniform_random raises an exception class thrust::system::system_error, parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\envs\paddle_gpu\lib\site-packages\paddle\utils\install_check.py", line 196, in run_check
    _run_static_single(use_cuda)
  File "D:\Anaconda\envs\paddle_gpu\lib\site-packages\paddle\utils\install_check.py", line 124, in _run_static_single
    exe.run(startup_prog)
  File "D:\Anaconda\envs\paddle_gpu\lib\site-packages\paddle\fluid\executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
  File "D:\Anaconda\envs\paddle_gpu\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\Anaconda\envs\paddle_gpu\lib\site-packages\paddle\fluid\executor.py", line 1260, in run
    return_merged=return_merged)
  File "D:\Anaconda\envs\paddle_gpu\lib\site-packages\paddle\fluid\executor.py", line 1402, in _run_impl
    use_program_cache=use_program_cache)
  File "D:\Anaconda\envs\paddle_gpu\lib\site-packages\paddle\fluid\executor.py", line 1492, in _run_program
    [fetch_var_name])
RuntimeError: parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device`

**Comment by pangyoki** [comment]
你好，麻烦打印下`nvidia-smi`和`nvcc -V`看看输出结果。

**Comment by gyg123456** [comment]
> 你好，麻烦打印下`nvidia-smi`和`nvcc -V`看看输出结果。

```
(paddle_gpu) C:\Users\GYG>nvidia-smi
Thu Jan 27 18:03:27 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 511.23       Driver Version: 511.23       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   16C    P8    14W /  N/A |      0MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by gyg123456** [comment]
> 你好，麻烦打印下`nvidia-smi`和`nvcc -V`看看输出结果。
```
(paddle_gpu) C:\Users\GYG>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89
```

**Comment by pangyoki** [comment]
> > 你好，麻烦打印下`nvidia-smi`和`nvcc -V`看看输出结果。
> 
> ```
> (paddle_gpu) C:\Users\GYG>nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
> Cuda compilation tools, release 10.2, V10.2.89
> ```

看起来cuda环境没啥问题，不过我们没有验证过 cuda driver version 11.6的情况。建议使用docker试一下吧：paddlepaddle/paddle:2.2.2-gpu-cuda10.2-cudnn7

docker安装文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html

**Comment by gyg123456** [comment]
> 
是不是将nvidia-smi命令下的CUDA VERSION降低到10.2就可以解决问题了呢？

**Comment by pangyoki** [comment]
> 是不是将nvidia-smi命令下的CUDA VERSION降低到10.2就可以解决问题了呢？

可以尝试下这种方法，但是不确定是否一定能解决。
docker里是标准环境，建议先用docker看能不能正常跑起来。

**Comment by gyg123456** [comment]
> > 是不是将nvidia-smi命令下的CUDA VERSION降低到10.2就可以解决问题了呢？
> 
> 可以尝试下这种方法，但是不确定是否一定能解决。 docker里是标准环境，建议先用docker看能不能正常跑起来。

好像并不支持windows系统下的docker呢。

**Comment by gyg123456** [comment]
> > 是不是将nvidia-smi命令下的CUDA VERSION降低到10.2就可以解决问题了呢？
> 
> 可以尝试下这种方法，但是不确定是否一定能解决。 docker里是标准环境，建议先用docker看能不能正常跑起来。

我是Window 10操作系统，paddle好像并不支持windows系统下docker的安装。

**Comment by gyg123456** [comment]
> > 是不是将nvidia-smi命令下的CUDA VERSION降低到10.2就可以解决问题了呢？
> 
> 可以尝试下这种方法，但是不确定是否一定能解决。 docker里是标准环境，建议先用docker看能不能正常跑起来。

具体如何操作呢，docker里需要安装cuda 11.6吗

**Comment by gyg123456** [comment]
> > 是不是将nvidia-smi命令下的CUDA VERSION降低到10.2就可以解决问题了呢？
> 
> 可以尝试下这种方法，但是不确定是否一定能解决。 docker里是标准环境，建议先用docker看能不能正常跑起来。

可否加一下微信聊下呢

**Comment by zlsh80826** [comment]
請試一下 [2.2.2-gpu-cuda11.2-cudnn8](https://hub.docker.com/layers/paddlepaddle/paddle/2.2.2-gpu-cuda11.2-cudnn8/images/sha256-09603d35054766f0d328ab4368a5eb8dbf92d0802041308992df1db41601e817?context=explore), 30系的顯卡需要 cuda 11 才能支援

對應 cmake 編譯代碼: https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cuda.cmake#L197

**Comment by gyg123456** [comment]
> 

好的，谢谢你

**Comment by gyg123456** [comment]
> 請試一下 [2.2.2-gpu-cuda11.2-cudnn8](https://hub.docker.com/layers/paddlepaddle/paddle/2.2.2-gpu-cuda11.2-cudnn8/images/sha256-09603d35054766f0d328ab4368a5eb8dbf92d0802041308992df1db41601e817?context=explore), 30系的顯卡需要 cuda 11 才能支援
> 
> 對應 cmake 編譯代碼: https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cuda.cmake#L197

好的，谢谢你

**Comment by gyg123456** [comment]
cuda11.2配合cudnn8.2，解决了以上问题

**Comment by inlet511** [comment]
1070ti，win11, cuda 11.6, cuDNN也是匹配版本，确认没有问题，pytorch等其他环境都有，正常使用。
使用conda创建的环境， python=3.10.9， 安装paddlepaddle用的也是匹配的选项： python -m pip install paddlepaddle-gpu==2.4.1.post116 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
显示  paddlepaddle-gpu (2.4.1.post116)，(paddlespeech  1.0.1) 均正常
但是，使用 paddle.utils.run_check() 提示我 cudnn64_8未正常安装：PreconditionNotMetError: The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)

……还没见过安装都很顺利，但是检查不通过的库……
