### ISSUE TITLE
报错nExternalError: CUDNN error(3), CUDNN_STATUS_BAD_PARAM.

### ISSUE THREAD

**Issue by Karenlyw** [PaddlePaddle/Paddle#39284]
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.0 post101 paddlehub:2.0.0
    2）GPU：单机双卡Tesla M60、CUDA10.1 CUDNN7.6.5
    3）linux，Python版本3.7
使用hubserving启动ocr服务 hub serving start -m chinese_ocr_db_crnn_server -p 8866
服务器端不报错，客户端调接口报错：
{'msg': '\n\n  Compile Traceback (most recent call last):\n    File "tools/export_model.py", line 75, in <module>\n      main()\n    File "tools/export_model.py", line 51, in main\n      config, eval_program, startup_prog)\n    File "/paddle/PaddleOCR/PaddleOCR/tools/program.py", line 215, in build_export\n      image, outputs = model(mode=\'export\')\n    File "/paddle/PaddleOCR/PaddleOCR/ppocr/modeling/architectures/det_model.py", line 137, in __call__\n      predicts = self.head(conv_feas, mode)\n    File "/paddle/PaddleOCR/PaddleOCR/ppocr/modeling/heads/det_db_head.py", line 196, in __call__\n      shrink_maps = self.binarize(fuse)\n    File "/paddle/PaddleOCR/PaddleOCR/ppocr/modeling/heads/det_db_head.py", line 63, in binarize\n      act="relu")\n    File "/root/anaconda3/envs/deploy/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2878, in batch_norm\n      type="batch_norm", inputs=inputs, outputs=outputs, attrs=attrs)\n    File "/root/anaconda3/envs/deploy/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op\n      return self.main_program.current_block().append_op(*args, **kwargs)\n    File "/root/anaconda3/envs/deploy/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2880, in append_op\n      attrs=kwargs.get("attrs", None))\n    File "/root/anaconda3/envs/deploy/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1977, in __init__\n      for frame in traceback.extract_stack():\n\n--------------------------------------\nC++ Traceback (most recent call last):\n--------------------------------------\n0   paddle::AnalysisPredictor::ZeroCopyRun()\n1   paddle::framework::NaiveExecutor::Run()\n2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)\n3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const\n4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const\n5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)\n6   paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const\n7   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)\n8   paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)\n\n----------------------\nError Message Summary:\n----------------------\nExternalError: CUDNN error(3), CUDNN_STATUS_BAD_PARAM. \n  [Hint: \'CUDNN_STATUS_BAD_PARAM\'.  An incorrect value or parameter was passed to the function. To correct, ensure that all the parameters being passed have valid values.  ] (at /paddle/paddle/fluid/operators/batch_norm_op.cu:378)\n  [operator < batch_norm > error]', 'results': '', 'status': '101'}

**Comment by ZzSean** [comment]
你好，根据报错信息应该是batchnorm中的参数传递出错了，由于该算子底层调用的是CUDNN，因此可以用CUDNN LOG 来打印信息，看log中报错接口的参数要求和实际的参数哪里出错，该LOG功能使用参考https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#api-logging
export CUDNN_LOGINFO_DBG=1
export CUDNN_LOGDEST_DBG=<log_file_name>

**Comment by ZzSean** [comment]
你好，请问问题是否已经解决，该issue能否close？
