### ISSUE TITLE
windows下anaconda安装，验证报错

### ISSUE THREAD

**Issue by DYANYYY** [PaddlePaddle/Paddle#39303]
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle2.2
    2）CPU：Core(TM) i9-8950HK
    3）GPU：NVIDIA GeForce GTX 1080
    4）系统环境：Windows 10 Home，64-bit，python3.9

- 安装方式信息：
Anaconda安装conda install paddlepaddle-gpu==2.2.2 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
         
- 复现信息：(PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)
- 问题描述：
- >>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\utils\install_check.py", line 196, in run_check
    _run_static_single(use_cuda)
  File "C:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\utils\install_check.py", line 124, in _run_static_single
    exe.run(startup_prog)
  File "C:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
  File "C:\Anaconda3\envs\paddle_env\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 1250, in run
    return self._run_impl(
  File "C:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 1394, in _run_impl
    return self._run_program(
  File "C:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 1491, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)

**Comment by ZzSean** [comment]
你好，根据报错信息来看，应该是依赖的cudnn没有正确安装，麻烦确认下cudnn的版本和安装信息

**Comment by DYANYYY** [comment]
好的

**Comment by ZzSean** [comment]
你好，请问问题是否已经解决，该issue能否close？

**Comment by DYANYYY** [comment]
已解决，感谢，可以close
