### ISSUE TITLE
SlowFast RCNN 导出模型预测时，Predictor.run

### ISSUE THREAD

**Issue by Xingyu-Romantic** [PaddlePaddle/Paddle#39916]
环境信息：CUDA11.2, CUDNN8.0
             paddlepaddle-gpu        2.2.2   post101

错误信息如下：
finish object detection
Traceback (most recent call last):
  File "ji.py", line 100, in <module>
    print(process_image(init(), '/home/data/607/fall_recognition_20210816_1210.mp4'))
  File "ji.py", line 86, in process_image
    predictor.run()
OSError: In user code:

    File "tools/export_model.py", line 208, in <module>
      main()
    File "tools/export_model.py", line 202, in main
      paddle.jit.save(model, osp.join(args.output_path, model_name))
    File "<decorator-gen-101>", line 2, in save
      
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/jit.py", line 744, in save
      inner_input_spec)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-99>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpg3nkycs2.py", line 63, in forward
      __return_value_0, data_batch, mode), (__return_value_0,))
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmpg3nkycs2.py", line 59, in false_fn_3
      mode), (__return_value_0, data_batch, mode), (__return_value_0,))
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmpg3nkycs2.py", line 55, in false_fn_2
      __return_value_0,))
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmpg3nkycs2.py", line 49, in false_fn_1
      data_batch, mode), (__return_value_0,), (__return_value_0,)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/project/train/src_repo/PaddleVideo/paddlevideo/modeling/framework/detectors/base.py", line 31, in forward
      return self.infer_step(data_batch)
    File "/project/train/src_repo/PaddleVideo/paddlevideo/modeling/framework/detectors/two_stage.py", line 126, in infer_step
      img_shape,
    File "/project/train/src_repo/PaddleVideo/paddlevideo/modeling/heads/roi_head.py", line 149, in simple_test
      self.action_thr,
    File "/project/train/src_repo/PaddleVideo/paddlevideo/modeling/heads/roi_head.py", line 166, in simple_test_bboxes
      bbox_results = self._bbox_forward(x, rois, rois_num)
    File "/project/train/src_repo/PaddleVideo/paddlevideo/modeling/heads/roi_head.py", line 100, in _bbox_forward
      bbox_feat = self.bbox_roi_extractor(x, rois, rois_num)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmp73cile_k.py", line 73, in forward
      for_loop_body_5, [rois, feat, rois_num, roi_feats, t])
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
      loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
      loop_vars = control_flow.while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/control_flow.py", line 1250, in while_loop
      now_cond = cond(*output_vars)
    File "/tmp/tmp73cile_k.py", line 46, in for_loop_condition_5
      in_control_flow=True)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
      attrs={'axis': axis})
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDA error(700), an illegal memory access was encountered. 
      [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/fluid/platform/stream/cuda_stream.cc:92)
      [operator < less_than > error]
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  (External) CUDA error(700), an illegal memory access was encountered. 
  [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:599)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()
3   paddle::memory::allocation::AlignedAllocation::~AlignedAllocation()
4   paddle::memory::allocation::CUDAAllocator::FreeImpl(paddle::memory::allocation::Allocation*)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1645755189 (unix time) try "date -d @1645755189" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x5b5) received by PID 1461 (TID 0x7f5eb3ac0740) from PID 1461 ***]

Aborted (core dumped)

**Comment by Xingyu-Romantic** [comment]
已经解决，， 输入尺寸与模型尺寸不匹配，resize即可

**Comment by PyAllegro** [comment]
> 已经解决，， 输入尺寸与模型尺寸不匹配，resize即可
你好，我这边也遇到了同样的问题，可以讲下你具体改动的内容吗（目前还处于跑通demo阶段,非常感谢!）
