### ISSUE TITLE
在docker容器中安装paddlepaddle后paddle.utils.run_check()报错 

### ISSUE THREAD

**Issue by Xbotgo-Justin1** [PaddlePaddle/Paddle#43035]
### 问题描述 Issue Description
我用的是docker： 
基础镜像：docker pull nvidia/cuda:11.1.1-devel-centos7
想在这上边构建paddle环境
但是cuDNN version: None.None.None？？是为什么？
paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0526 15:34:45.617776 26217 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.1
W0526 15:34:45.618185 26217 dynamic_loader.cc:305] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/utils/install_check.py", line 266, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/utils/install_check.py", line 170, in _run_static_single
    exe.run(startup_prog)
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1299, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/python3/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1285, in run
    res = self._run_impl(
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1510, in _run_impl
    return self._run_program(
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1607, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:59)

### 版本&环境信息 Version & Environment Information

/usr/local/python3/lib/python3.8/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
1.py:51: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  plat = distro.linux_distribution()[0]
1.py:52: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  ver = distro.linux_distribution()[1]
****************************************
Paddle version: 2.3.0
Paddle With CUDA: True

OS: CentOS Linux 7
Python version: 3.8.3

CUDA version: 11.1.105
Build cuda_11.1.TC455_06.29190527_0
cuDNN version: None.None.None
Nvidia driver version: 470.63.01
****************************************

**Comment by esythan** [comment]
镜像中应该是没有cudnn，想问下镜像是从哪里下载的，如果可以，替换成paddle官网提供的镜像，具体的镜像和安装参见：
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html#anchor-0

**Comment by Xbotgo-Justin1** [comment]
基础镜像：docker pull nvidia/cuda:11.1.1-devel-centos7  就是来自nivdia的habor镜像
很奇怪，这个基础镜像还要手动装cudnn， 已解决。 谢谢
