### ISSUE TITLE
多进程下CUDA报错

### ISSUE THREAD

**Issue by simon-sxx** [PaddlePaddle/Paddle#43193]
### bug描述 Describe the Bug

使用multiprocessing进行多进程推理时报错，单进程推理时正常

报错如下：

Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "predict_new.py", line 259, in __call__
    det_results = self.detector_1.predict(inputs)
  File "predict_new.py", line 145, in predict
    input_tensor.copy_from_cpu(inputs[input_names[i]])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/inference/wrapper.py", line 36, in tensor_copy_from_cpu
    self.copy_from_cpu_bind(data)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:172)

preprocess:  28.76756238937378
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "predict_new.py", line 259, in __call__
    det_results = self.detector_1.predict(inputs)
  File "predict_new.py", line 145, in predict
    input_tensor.copy_from_cpu(inputs[input_names[i]])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/inference/wrapper.py", line 36, in tensor_copy_from_cpu
    self.copy_from_cpu_bind(data)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:172)

**Comment by RichardWooSJTU** [comment]
您好，请贴出以下信息使我们快速定位问题：
1. 环境：OS，python，paddle版本，显卡信息（可以直接贴nvidia-smi），cuda版本，cudnn版本。
2. 推理代码
同时也可以贴出更完整的log，辛苦~

**Comment by shangzhizhou** [comment]
您好，请把import paddle放到子进程里，注意其它import 的模块是否在内部也初始化了paddle，如果有也需要放到子进程里

**Comment by simon-sxx** [comment]
> 您好，请把import paddle放到子进程里，注意其它import 的模块是否在内部也初始化了paddle，如果有也需要放到子进程里

请问在内部初始化了paddle是什么意思呢

**Comment by sunjinghua** [comment]
请问这个问题解决了么？目前推理时遇到相同的问题

**Comment by Lemonlcy** [comment]
请问这个问题解决了么？目前推理时遇到相同的问题，在内部import之后还是卡在load_predictor(model_dir)里
