### ISSUE TITLE
Can not run with virtualized GPU

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#4439]
Use GPU on a virtual machine: `nvidia-smi`

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Graphics Device     On   | 0000:00:07.0     Off |                    0 |
| N/A   26C    P8    10W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```
bin/python train.py
False
I0927 18:03:30.291254 52858 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1
W0927 18:03:31.570487 52858 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
F0927 18:03:31.577112 52858 hl_gpu_matrix_kernel.cuh:181] Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function
*** Check failure stack trace: ***
    @     0x7f1d5a752a1d  google::LogMessage::Fail()
    @     0x7f1d5a7564cc  google::LogMessage::SendToLog()
    @     0x7f1d5a752513  google::LogMessage::Flush()
    @     0x7f1d5a7579de  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1d5a5dd2f4  hl_gpu_apply_unary_op<>()
    @     0x7f1d5a5dd635  paddle::BaseMatrixT<>::applyUnary<>()
    @     0x7f1d5a5dd863  paddle::BaseMatrixT<>::zero()
    @     0x7f1d5a478c51  paddle::Parameter::enableType()
    @     0x7f1d5a4744dc  paddle::parameterInitNN()
    @     0x7f1d5a476c2a  paddle::NeuralNetwork::init()
    @     0x7f1d5a49f7a1  paddle::GradientMachine::create()
    @     0x7f1d5a72f7e3  GradientMachine::createFromPaddleModelPtr()
    @     0x7f1d5a72f9bf  GradientMachine::createByConfigProtoStr()
    @     0x7f1d5a33f49d  _wrap_GradientMachine_createByConfigProtoStr
    @           0x4b4cb9  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x52940f  function_call
    @           0x422cba  PyObject_Call
    @           0x4271ad  instancemethod_call
    @           0x422cba  PyObject_Call
    @           0x48121f  slot_tp_init
    @           0x47eb1a  type_call
    @           0x422cba  PyObject_Call
    @           0x4b31dd  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b6c52  PyEval_EvalCode
Aborted
```

**Comment by zhangyuepeng** [comment]
when I install a old version with cuda8.0 and cudnn5, I meet the same error. But when install a new version with cuda8.0 and cudnn6. the error is gone. I don't know the reason.

**Comment by typhoonzero** [comment]
Update:

最终用户更新了libc，使用cuda 8可以正常运行了。

**Comment by zhangyuepeng** [comment]
@typhoonzero Maybe，that's the solution. I remember I had ever updated the glibc.
