### ISSUE TITLE
paddle 2.3.0 官方镜像在 A40 上多卡运行会卡住

### ISSUE THREAD

**Issue by pineking** [PaddlePaddle/Paddle#44777]
### 请提出你的问题 Please ask your question

官方 2.3.0 gpu 镜像：paddlepaddle/paddle/2.3.1-gpu-cuda11.2-cudnn8
https://hub.docker.com/layers/paddle/paddlepaddle/paddle/2.3.1-gpu-cuda11.2-cudnn8/images/sha256-4bef1dfb215daf7153fb8cd0ce14121136ace3130dfca392b5c252c049d8b276?context=explore

单卡正常，两卡就有问题，卡住不动

![image](https://user-images.githubusercontent.com/72760/182103411-df86baaa-ea7a-428d-b3e5-4be6e394ef52.png)

**Comment by danleifeng** [comment]
是截图最后卡住了么？ （调用 paddle.utils.run_check() ) ?
有预设环境变量么?

**Comment by pineking** [comment]
> 是截图最后卡住了么？ （调用 paddle.utils.run_check() ) ? 有预设环境变量么?
对，截图最后卡住了，调用 paddle.utils.run_check() 一直卡住

**Comment by pineking** [comment]
问题解决：export NCCL_P2P_DISABLE =1
https://github.com/NVIDIA/nccl/issues/631

**Comment by hy4015** [comment]
> 问题解决：export NCCL_P2P_DISABLE =1
> [NVIDIA/nccl#631](https://github.com/NVIDIA/nccl/issues/631)

但这样不就禁用了nvlink了吗？请问后来您有更好的解决办法吗？我目前也遇到了这个问题。
