### ISSUE TITLE
paddle_inference C++预测库 GPU版  cuDNN 8.4	CUDA 11.6 trt8.4.1.5预测时出错

### ISSUE THREAD

**Issue by zly19540609** [PaddlePaddle/Paddle#45209]
### bug描述 Describe the Bug

paddle_inference C++预测库2.3.1 GPU版  cuDNN 8.4	CUDA 11.6 trt8.4.1.5预测时出错
出错位置
`//predictor_->Run();
CHECK(predictor_->Run());`
提示错误
0x00007FFF7138420D (cudnn64_8.dll) (QtPaddle.exe 中)处有未经处理的异常: 请求了严重的程序退出

更换paddle_inference C++预测库2.3.1 GPU版  cuDNN 8.2	CUDA 11.2 trt8.0.1.6预测时正常

**Comment by joey12300** [comment]
请问你测试的机器cuda和cudnn版本是多少呢？使用trt的paddle预编译包需要完全对齐cuda和cudnn版本。

**Comment by zly19540609** [comment]
cuda_11.6.0_511.23
cudnn 8.4.0.27
TensorRT 8.4.1.5

**Comment by joey12300** [comment]
> cuda_11.6.0_511.23 cudnn 8.4.0.27 TensorRT 8.4.1.5

了解，目前的状态是：自己运行的环境，与paddle的预编译包所示的版本完全对齐了，但是仍然跑挂；然后选个低版本的预编译包就能正常运行了是吗？

另外，方便提供最小可复现代码吗？

**Comment by zly19540609** [comment]
是的，自己运行的环境，与paddle的预编译包所示的版本完全对齐了，但是仍然跑挂，换成CUDA 11.2 低版本预编译包就能正常运行了

**Comment by zly19540609** [comment]
代码是你们官方PaddleDetection c++ 部署的示例代码 模型用的是ppyolov2官方模型

**Comment by zly19540609** [comment]
我找到能让程序运行的方法了，下载zlibwapi.dll，放到环境变量中后，程序正常运行了，我不是很理解这个原理
[zlib123dllx64.zip](https://github.com/PaddlePaddle/Paddle/files/9371861/zlib123dllx64.zip)

**Comment by Mr-nobody233** [comment]
> 我找到能让程序运行的方法了，下载zlibwapi.dll，放到环境变量中后，程序正常运行了，我不是很理解这个原理 [zlib123dllx64.zip](https://github.com/PaddlePaddle/Paddle/files/9371861/zlib123dllx64.zip)

nb，老哥，我也遇到同样问题，用这个dll就解决了
