### ISSUE TITLE
(External) Cuda error(700), an illegal memory access was encountered.

### ISSUE THREAD

**Issue by blurmemo** [PaddlePaddle/Paddle#45434]
### 问题描述 Please describe your issue

最近在用solov2模型进行摄像头实时检测分割，运行python deploy/python/infer.py -model_dir=./inference_model/solov2_r50_fpn_3x_coco --device=GPU --camera_id=0
会报(External) Cuda error(700), an illegal memory access was encountered.
如果改成cpu则正常打开摄像头，但是会卡死
请问--device=GPU的报错如何解决
版本、环境信息
1）paddlenlp 2.3 paddlepaddle-gpu 2.3.2 CUDA=11.6 cuDNN=8.4.0
2）系统环境：Windows python 3.8x
![QQ图片20220825235441](https://user-images.githubusercontent.com/92586621/186712764-46118d49-e9be-4127-9655-ddb1760ed4e8.png)

**Comment by zhiboniu** [comment]
有没有更完整的log，另外出错的时候显存是否够用呢

**Comment by blurmemo** [comment]
> 

已经解决了，安装的uda高了，虽然我的电脑适配的是11.6

**Comment by zhiboniu** [comment]
好的
