### ISSUE TITLE
OSError: (External) CUBLAS error(7). 

### ISSUE THREAD

**Issue by gjghs** [PaddlePaddle/Paddle#45683]
### bug描述 Describe the Bug

训练ppyoloe时报错，简单的复现了一下报了同样的错误
import paddle
import paddle.nn.functional as F
a = paddle.ones((32, 8505, 4, 17))
b = paddle.to_tensor([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9. , 10., 11., 12., 13., 14., 15., 16.])
a.matmul(b)

OSError: (External) CUBLAS error(7). 
  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:55)
  [operator < matmul_v2 > error]

### 其他补充信息 Additional Supplementary Information

使用的是dockerhub里最新的gpu版本，paddle版本2.3.0.post112，paddledetection2.4release
显卡是3090
W0902 06:52:44.857926 3886003 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.2
W0902 06:52:44.861104 3886003 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.

**Comment by gjghs** [comment]
已解决，head里面修改
![~EN8K64IW%S2 L2}_SLONOO](https://user-images.githubusercontent.com/47850883/188307342-f3ae37a2-8260-4c22-ae55-d5775b27ae4a.png)

**Comment by tianxin1860** [comment]
您好，针对这个问题的修复欢迎在这个 Repo  https://github.com/PaddlePaddle/PaddleDetection 提 PR。
