### ISSUE TITLE
训练完成，在推理阶段发生(External) CUDA error(719), unspecified launch failure.

### ISSUE THREAD

**Issue by ABC1234-gitup** [PaddlePaddle/Paddle#45742]
### bug描述 Describe the Bug

(python_env) D:\HYD\PaddleDetection-release-2.3>python -u ./tools/eval.py -c configs/centernet/centernet_r50_140e_coco.yml -o weights=./work/output/centernet_r50_140e_coco/0.pdparams
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
W0905 10:25:07.250306  7876 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.7, Runtime API Version: 11.6
W0905 10:25:07.253298  7876 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[09/05 10:25:08] ppdet.utils.checkpoint INFO: Finish loading model weights: ./work/output/centernet_r50_140e_coco/0.pdparams
Traceback (most recent call last):
  File "./tools/eval.py", line 152, in <module>
    main()
  File "./tools/eval.py", line 148, in main
    run(FLAGS, cfg)
  File "./tools/eval.py", line 106, in run
    trainer.evaluate()
  File "D:\HYD\PaddleDetection-release-2.3\ppdet\engine\trainer.py", line 503, in evaluate
    self._eval_with_loader(self.loader)
  File "D:\HYD\PaddleDetection-release-2.3\ppdet\engine\trainer.py", line 481, in _eval_with_loader
    outs = self.model(data)
  File "C:\Users\user\.conda\envs\python_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\user\.conda\envs\python_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\HYD\PaddleDetection-release-2.3\ppdet\modeling\architectures\meta_arch.py", line 56, in forward
    out = self.get_pred()
  File "D:\HYD\PaddleDetection-release-2.3\ppdet\modeling\architectures\centernet.py", line 100, in get_pred
    scale_factor=self.inputs['scale_factor'])
  File "D:\HYD\PaddleDetection-release-2.3\ppdet\modeling\post_process.py", line 464, in __call__
    scores, inds, topk_clses, ys, xs = self._topk(heat)
  File "D:\HYD\PaddleDetection-release-2.3\ppdet\modeling\layers.py", line 815, in _topk
    topk_xs = topk_inds % width
  File "C:\Users\user\.conda\envs\python_env\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\gpu_context.cc:435)
  [operator < elementwise_mod > error]

### 其他补充信息 Additional Supplementary Information

环境：
python                    3.7.13
paddlepaddle-gpu          2.3.2
cudatoolkit               11.6.0              
cudnn                     8.4.1.50
window 10系统
我的虚拟环境中除了paddlepaddle-gpu，还有pytorch  1.12.1

**Comment by wangxinxin08** [comment]
你使用PaddleDetection官方的权重: https://bj.bcebos.com/v1/paddledet/models/centernet_r50_140e_coco.pdparams 试下能不能正常eval呢？如果依然不能正常eval，建议使用docker或者安装cuda 11.6.2和cudnn 8.4.0这个组合

**Comment by ABC1234-gitup** [comment]
改变权重后出现同样的错误，我选择安装cuda 11.6.2和cudnn 8.4.0这个组合，在环境里我先装的pytorch,下载cudnn-windows-x86_64-8.4.0.27_cuda11.6-archive。pytorch安装完成后安装paddlepaddle，使用官网命令在安装过程中会自动安装cudnn 8.4.1这个版本，请问在命令安装paddlepaddle时可以指定cudnn的版本号吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 训练完成，在推理阶段发生(External) CUDA error(719), unspecified launch failure. (Issue #45742)





 
你使用PaddleDetection官方的权重: https://bj.bcebos.com/v1/paddledet/models/centernet_r50_140e_coco.pdparams 试下能不能正常eval呢？如果依然不能正常eval，建议使用docker或者安装cuda 11.6.2和cudnn 8.4.0这个组合

**Comment by wangxinxin08** [comment]
不能指定cudnn的版本号，你可以先试下现在还有问题没有

**Comment by ABC1234-gitup** [comment]
我试了下还是出现同样的问题。
Traceback (most recent call last):
&nbsp; File "./tools/eval.py", line 153, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "./tools/eval.py", line 148, in main
&nbsp; &nbsp; run(FLAGS, cfg)
&nbsp; File "./tools/eval.py", line 106, in run
&nbsp; &nbsp; trainer.evaluate()
&nbsp; File "D:\HYD\95-99\PaddleDetection-release-2.3\ppdet\engine\trainer.py", line 503, in evaluate
&nbsp; &nbsp; self._eval_with_loader(self.loader)
&nbsp; File "D:\HYD\95-99\PaddleDetection-release-2.3\ppdet\engine\trainer.py", line 481, in _eval_with_loader
&nbsp; &nbsp; outs = self.model(data)
&nbsp; File "C:\Users\HENGIDEAL\.conda\envs\python_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
&nbsp; &nbsp; return self._dygraph_call_func(*inputs, **kwargs)
&nbsp; File "C:\Users\HENGIDEAL\.conda\envs\python_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
&nbsp; &nbsp; outputs = self.forward(*inputs, **kwargs)
&nbsp; File "D:\HYD\95-99\PaddleDetection-release-2.3\ppdet\modeling\architectures\meta_arch.py", line 56, in forward
&nbsp; &nbsp; out = self.get_pred()
&nbsp; File "D:\HYD\95-99\PaddleDetection-release-2.3\ppdet\modeling\architectures\centernet.py", line 100, in get_pred
&nbsp; &nbsp; scale_factor=self.inputs['scale_factor'])
&nbsp; File "D:\HYD\95-99\PaddleDetection-release-2.3\ppdet\modeling\post_process.py", line 464, in __call__
&nbsp; &nbsp; scores, inds, topk_clses, ys, xs = self._topk(heat)
&nbsp; File "D:\HYD\95-99\PaddleDetection-release-2.3\ppdet\modeling\layers.py", line 815, in _topk
&nbsp; &nbsp; topk_xs = topk_inds % width
&nbsp; File "C:\Users\HENGIDEAL\.conda\envs\python_env\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 299, in __impl__
&nbsp; &nbsp; return math_op(self, other_var, 'axis', axis)
OSError: (External) CUDA error(719), unspecified launch failure.
&nbsp; [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\gpu_context.cc:435)
&nbsp; [operator < elementwise_mod &gt; error]





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月6日(星期二) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 训练完成，在推理阶段发生(External) CUDA error(719), unspecified launch failure. (Issue #45742)





 
不能指定cudnn的版本号，你可以先试下现在还有问题没有

**Comment by wangxinxin08** [comment]
建议回退cuda版本到11.2或者10.2，太新的cuda版本可能出问题

**Comment by wangxinxin08** [comment]
另外，可以测试下以下代码能够正常跑
``` python
import paddle
scores = paddle.randn((1, 2, 3, 3))
k = 10
shape_fm = paddle.shape(scores)
shape_fm.stop_gradient = True
cat, height, width = shape_fm[1], shape_fm[2], shape_fm[3]
scores_r = paddle.reshape(scores, [cat, -1])
topk_scores, topk_inds = paddle.topk(scores_r, k)
topk_ys = topk_inds // width
topk_xs = topk_inds % width
```

**Comment by ABC1234-gitup** [comment]
不可以正常跑。会出现以下错误：
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月6日(星期二) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 训练完成，在推理阶段发生(External) CUDA error(719), unspecified launch failure. (Issue #45742)





 
另外，可以测试下以下代码能够正常跑
 import paddle scores = paddle.randn((1, 2, 3, 3)) k = 10 shape_fm = paddle.shape(scores) shape_fm.stop_gradient = True cat, height, width = shape_fm[1], shape_fm[2], shape_fm[3] scores_r = paddle.reshape(scores, [cat, -1]) topk_scores, topk_inds = paddle.topk(scores_r, k) topk_ys = topk_inds // width topk_xs = topk_inds % width

**Comment by wangxinxin08** [comment]
建议先回退CUDA版本吧

**Comment by ABC1234-gitup** [comment]
cuda 退回到10.2版本，问题解决。十分感谢！
