### ISSUE TITLE
使用docker安装paddle，无法使用多gpu

### ISSUE THREAD

**Issue by mike-egg123** [PaddlePaddle/Paddle#47554]
### bug描述 Describe the Bug

我的环境是Ubuntu22，然后目前的paddle稳定版还不支持，因此我参照[这篇文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/install/docker/linux-docker.html)选择使用docker进行安装，但是装好了之后出现了无法使用多gpu的情况，报错信息如下
```
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W1101 13:16:00.328781    11 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.7
W1101 13:16:00.337703    11 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py:1585: UserWarning: Standalone executor is not used for data parallel
  UserWarning)
W1101 13:16:02.654585    11 parallel_executor.cc:666] Cannot enable P2P access from 0 to 1
W1101 13:16:02.654606    11 parallel_executor.cc:666] Cannot enable P2P access from 0 to 2
W1101 13:16:02.654609    11 parallel_executor.cc:666] Cannot enable P2P access from 1 to 0
W1101 13:16:02.654614    11 parallel_executor.cc:666] Cannot enable P2P access from 1 to 2
W1101 13:16:02.654618    11 parallel_executor.cc:666] Cannot enable P2P access from 2 to 0
W1101 13:16:02.654623    11 parallel_executor.cc:666] Cannot enable P2P access from 2 to 1
WARNING:root:PaddlePaddle meets some problem with 3 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests 
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
WARNING:root:
 Original Error is: (External) NCCL error(2), unhandled system error. 
  [Hint: Please search for the error code(2) on website (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html#ncclresult-t) to get Nvidia's official solution and advice about NCCL Error.] (at /paddle/paddle/fluid/platform/device/gpu/nccl_helper.h:181)

PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.
```
请问我需要如何操作才能在多卡环境中使用paddle呢？

**Comment by danleifeng** [comment]
请问你选择的docker镜像是哪个？另外您的本地机器gpu信息能提供么（nvidia-smi 查看）

**Comment by dingjiaweiww** [comment]
你好，经过充分的测试，paddle 现在已支持Ubuntu 22

**Comment by mike-egg123** [comment]
你好，请问是哪个版本呢？我看官网的快速安装部分只有2.3版和develop版，2.3应该还不支持，develop版之前我放到我的Ubuntu22上面跑不起来。。。

**Comment by mike-egg123** [comment]
> 请问你选择的docker镜像是哪个？另外您的本地机器gpu信息能提供么（nvidia-smi 查看）
我的gpu信息如下：
```
Mon Nov  7 09:18:41 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:3B:00.0 Off |                  N/A |
| 30%   42C    P0   107W / 350W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:AF:00.0 Off |                  N/A |
| 30%   39C    P0   110W / 350W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:D8:00.0 Off |                  N/A |
| 30%   38C    P0   110W / 350W |      0MiB / 24576MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
使用的镜像是：
`paddlepaddle/paddle:2.4.0rc0-gpu-cuda11.7-cudnn8.4-trt8.4`

**Comment by freedomaswind94** [comment]
> > 请问你选择的docker镜像是哪个？另外您的本地机器gpu信息能提供么（nvidia-smi 查看）
> > 我的gpu信息如下：
> 
> ```
> Mon Nov  7 09:18:41 2022       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ...  Off  | 00000000:3B:00.0 Off |                  N/A |
> | 30%   42C    P0   107W / 350W |      0MiB / 24576MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   1  NVIDIA GeForce ...  Off  | 00000000:AF:00.0 Off |                  N/A |
> | 30%   39C    P0   110W / 350W |      0MiB / 24576MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   2  NVIDIA GeForce ...  Off  | 00000000:D8:00.0 Off |                  N/A |
> | 30%   38C    P0   110W / 350W |      0MiB / 24576MiB |      4%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> ```
> 
> 使用的镜像是： `paddlepaddle/paddle:2.4.0rc0-gpu-cuda11.7-cudnn8.4-trt8.4`

你好，请问您最后是怎么解决的，我也是docker装的2.4.1

**Comment by m00nLi** [comment]
百毒的代码真的是shit

**Comment by overjjjj** [comment]
您好，请问最后解决方案是什么，我也遇到同样的问题了

**Comment by m00nLi** [comment]
解决了，改用PyTorch成功解决。不建议使用PaddlePaddle用的越多你会发现bug越多，连百度官方都解决不了的bug。如无必要，尽量不要用百度的东西



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月31日(周二) 凌晨0:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] 使用docker安装paddle，无法使用多gpu (Issue #47554)




 
您好，请问最后解决方案是什么，我也遇到同样的问题了
