### ISSUE TITLE
OSError: (External) CUBLAS error(13). 

### ISSUE THREAD

**Issue by ZzyChris97** [PaddlePaddle/Paddle#47749]
### 请提出你的问题 Please ask your question

环境信息：
* python: 3.9.2
* paddlepaddle-gpu: 2.3.1.post112
* cuda version: 11.4
* Driver version: 470.57.02
* gpu: NVIDIA A100

执行inverse报错，发生错误的代码段
```
forward_kernel = paddle.zeros([N + 3, N + 3])
target_control_partial_repr = compute_partial_repr(target_control_points, target_control_points)
forward_kernel[:N, :N] = target_control_partial_repr
forward_kernel[:N, -3] = 1
forward_kernel[-3, :N] = 1
forward_kernel[:N, -2:] = target_control_points
forward_kernel[-2:, :N] = target_control_points.transpose([1, 0])

inverse_kernel = paddle.inverse(forward_kernel)
```

错误信息如下：
```
Traceback (most recent call last):
  File "/home/hr/projects/ppocr/PaddleOCR/applications/academy/dataprocess/Paddle-TextSR-STT/predict.py", line 77, in <module>
    Mission.demo()
  File "/home/hr/projects/ppocr/PaddleOCR/applications/academy/dataprocess/Paddle-TextSR-STT/predict.py", line 14, in demo
    model_dict = self.generator_init()
  File "/home/hr/projects/ppocr/PaddleOCR/applications/academy/dataprocess/Paddle-TextSR-STT/interfaces/base.py", line 136, in generator_init
    model = tbsrn.TBSRN(scale_factor=self.scale_factor, width=cfg.width, height=cfg.height,
  File "/home/hr/projects/ppocr/PaddleOCR/applications/academy/dataprocess/Paddle-TextSR-STT/model/tbsrn.py", line 198, in __init__
    self.tps = TPSSpatialTransformer(
  File "/home/hr/projects/ppocr/PaddleOCR/applications/academy/dataprocess/Paddle-TextSR-STT/model/tps_spatial_transformer.py", line 78, in __init__
    inverse_kernel = paddle.linalg.inv(forward_kernel)
  File "/home/hr/anaconda3/lib/python3.9/site-packages/paddle/tensor/math.py", line 1696, in inverse
    return _C_ops.inverse(x)
OSError: (External) CUBLAS error(13). 
  [Hint: 'CUBLAS_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is often caused by a launch failure of the kernel on the GPU, which can be caused by multiple reasons.  To correct: check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed. ] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:193)
  [operator < inverse > error]
```

**Comment by JZ-LIANG** [comment]
这是paddle 调用 cublas 底层库时的报错，根据 Cublas 官方document 解释，这个和 硬件驱动版本 和 cublas 是否正确安装相关， 不是Paddle调用时入参的问题，请检查当前cublas 环境。

**Comment by np-n** [comment]
Still facing the same problem, @JZ-LIANG, how to fix Cublas environment issue.

**Comment by np-n** [comment]
I stuck on similar issue: 
```
[2023/04/17 09:56:15] ppocr DEBUG: dt_boxes num : 2, elapse : 0.011786937713623047
[2023/04/17 09:56:15] ppocr DEBUG: cls num  : 2, elapse : 0.003351449966430664
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_9526/2725330578.py in <module>
      1 start_time = time.time()
----> 2 result = ocr.ocr(image_path, cls=True)
      3 print(result)
      4 end_time = time.time()
      5 total_time = end_time - start_time

~/miniconda3/envs/paddleocr_gpu/lib/python3.7/site-packages/paddleocr/paddleocr.py in ocr(self, img, det, rec, cls)
    553             ocr_res = []
    554             for idx, img in enumerate(imgs):
--> 555                 dt_boxes, rec_res, _ = self.__call__(img, cls)
    556                 tmp_res = [[box.tolist(), res]
    557                            for box, res in zip(dt_boxes, rec_res)]

~/miniconda3/envs/paddleocr_gpu/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py in __call__(self, img, cls)
     93                 len(img_crop_list), elapse))
     94 
---> 95         rec_res, elapse = self.text_recognizer(img_crop_list)
     96         time_dict['rec'] = elapse
     97         logger.debug("rec_res num  : {}, elapse : {}".format(

~/miniconda3/envs/paddleocr_gpu/lib/python3.7/site-packages/paddleocr/tools/infer/predict_rec.py in __call__(self, img_list)
    607                 else:
    608                     self.input_tensor.copy_from_cpu(norm_img_batch)
--> 609                     self.predictor.run()
    610                     outputs = []
    611                     for output_tensor in self.output_tensors:

OSError: (External) CUBLAS error(13). 
  [Hint: Please search for the error code(13) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
  [operator < fc > error]
```
How to fix it?

**Comment by mnansary** [comment]
Facing the same issue
```
 File "/home/apsisdev/anaconda3/envs/nidocr/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 494, in ocr
    rec_res, elapse = self.text_recognizer(img)
  File "/home/apsisdev/anaconda3/envs/nidocr/lib/python3.8/site-packages/paddleocr/tools/infer/predict_rec.py", line 385, in __call__
    self.predictor.run()
OSError: (External) CUBLAS error(13). 
  [Hint: Please search for the error code(13) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
  [operator < fc > error]

```

**Comment by Ysnower** [comment]
File "/home/wmj/anaconda3/lib/python3.7/site-packages/paddle/nn/utils/spectral_norm_hook.py", line 72, in compute_weight
    transpose_y=False,
  File "/home/wmj/anaconda3/lib/python3.7/site-packages/paddle/tensor/linalg.py", line 244, in matmul
    return _C_ops.matmul(x, y, transpose_x, transpose_y)
OSError: (External) CUBLAS error(13). 
  [Hint: Please search for the error code(13) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:55)

**Comment by magicleo** [comment]
调用ernie ranker时也面临同样的问题！！
  File "/mnt/storage/anaconda3/lib/python3.10/site-packages/paddlenlp/taskflow/taskflow.py", line 850, in __call__
    results = self.task_instance(inputs)
  File "/mnt/storage/anaconda3/lib/python3.10/site-packages/paddlenlp/taskflow/task.py", line 516, in __call__
    outputs = self._run_model(inputs)
  File "/mnt/storage/anaconda3/lib/python3.10/site-packages/paddlenlp/taskflow/text_similarity.py", line 279, in _run_model
    self.predictor.run()
OSError: (External) CUBLAS error(13).
  [Hint: Please search for the error code(13) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
  [operator < multihead_matmul > error]

**Comment by BaoChunxiao** [comment]
我也遇到了这个问题，后来解决了
我paddle版本是paddlepaddle-gpu==2.5.2，按照官网的安装教程选择的CUDA11.8
我服务器通过nvidia-smi看到的Driver Version: 520.56.06，CUDA Version: 11.8
然后在conda环境里执行"conda install cudatoolkit"，装了一个cudatoolkit，版本是11.0.221
后来我又从NVIDIA官网下载并安装了cuda_11.8.0_520.61.05_linux.run
然后执行paddle的程序就也报这个错误
然后我在conda环境里执行"conda uninstall cudatoolkit"，把用conda安装的cudatoolkit给卸载掉
就不报错了

猜测原因是paddle是选择CUDA11.8进行的安装，一开始conda安装的cudatoolkit是11.0.221，版本不匹配，后来卸载掉conda安装的cudatoolkit后，paddle的程序找到了NVIDIA官网下载安装的cuda，版本是11.8，就对上了

**Comment by AdamLTy** [comment]
检查一下进行运算的tensor是不是在相同设备上
