### ISSUE TITLE
paddlepaddle-gpu对应cuda版本问题

### ISSUE THREAD

**Issue by jyjy007** [PaddlePaddle/Paddle#47987]
### 问题描述 Issue Description

我的显卡是3070ti，切换了很多次的cuda版本，10.2/11.0/11.2都试过，但是一直有问题。

cuda10.2：
运行某模块后报错：
```
W1115 11:09:24.998811 15844 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 10.2
W1115 11:09:25.022526 15844 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
W1115 11:09:25.089778 15844 operator.cc:288] truncated_gaussian_random raises an exception class thrust::system::system_error, parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
```
网上搜了一下，可能是cuda10.2不匹配目前的3070ti的gpu

cuda11.0/11.2：
运行某模块后报错：
```
W1115 11:33:06.096570  3416 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 10.2
W1115 11:33:06.096570  3416 dynamic_loader.cc:276] Note: [Recommend] copy cudnn into CUDA installation directory. 
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
```
看起来识别cuda版本没识别到？
但是nvcc -V查看版本是对的:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:15:10_Pacific_Standard_Time_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
```
cudnn我也下载了8.1.1，并拷贝了相关文件到cuda的对应目录。
环境变量应该也是对的：
```
CUDA_BIN_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin
CUDA_LIB_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\lib\x64
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
CUDA_PATH_V11_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
CUDA_SDK_BIN_PATH=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.2\bin\win64
CUDA_SDK_LIB_PATH=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.2\common\lib\x64
CUDA_SDK_PATH=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.2
```

请帮忙看看这是什么问题？

### 版本&环境信息 Version & Environment Information

paddlepadle-gpu==2.3.2
cuda==11.2.0
cudnn==8.1.1
gpu==3070ti
os==win10

**Comment by tink2123** [comment]
尝试参考以下命令安装paddle：
```
python -m pip install paddlepaddle-gpu==2.3.2.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
```

如果依然不行，建议使用docker，避免复杂的环境配置问题

**Comment by jyjy007** [comment]
解决了，非常感谢！
