### ISSUE TITLE
libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ThinkSYR** [PaddlePaddle/Paddle#49280]
### bug描述 Describe the Bug
安装没有报错
```shell
python -m pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```
import有问题：
```shell
Python 3.7.15 (default, Nov 24 2022, 21:12:53) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /home/huangsiyuan/miniconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/huangsiyuan/miniconda3/envs/ppocr/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/huangsiyuan/miniconda3/envs/ppocr/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/huangsiyuan/miniconda3/envs/ppocr/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/huangsiyuan/miniconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/huangsiyuan/miniconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/huangsiyuan/miniconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/home/huangsiyuan/miniconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
>>> 
```

### 其他补充信息 Additional Supplementary Information

我的cuda nvcc运行时版本是8.0：
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```
但是nvidia-smi driver是11.4：
```
Fri Dec 23 09:32:19 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 470.74       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN Xp     Off  | 00000000:02:00.0 Off |                  N/A |
| 23%   21C    P8    16W / 250W |   1749MiB / 12194MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
安装paddle是只能按运行时版本来的吗？因为我安装pytorch没有碰到过这个问题

**Comment by Caozhou1995** [comment]
pip安装的是CUDA11.2版本的paddle whl包，但你CUDA版本是11.4，目前官网上未显示对CUDA 11.4稳定支持，支持的CUDA版本参考官网安装文档：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html。建议选择合适的CUDA版本进行安装，或者尝试使用源码编译方式

**Comment by angel-yi** [comment]
解决了吗，我也是这样

**Comment by yiliyili** [comment]
cpu的机器,安装最新版paddlespeech,报错ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

$ paddlespeech help
Error: Can not import paddle core while this file exists: /home/wwwuser/miniconda3/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/wwwuser/miniconda3/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddlespeech/cli/base_commands.py", line 20, in <module>
    from ..resource import CommonTaskResource
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddlespeech/resource/__init__.py", line 14, in <module>
    from .resource import CommonTaskResource
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddlespeech/resource/resource.py", line 20, in <module>
    from ..cli.utils import download_and_decompress
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddlespeech/cli/utils.py", line 26, in <module>
    import paddle
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/home/wwwuser/miniconda3/lib/python3.10/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by XindongHao** [comment]
遇到同样的问题，等待官方修复方案
暂时采用安装低版本的解决方案（亲测可用）：
1. python==3.7.0
2. 安装2.3版本paddle [paddle conda安装教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.3/install/conda/linux-conda.html)
`conda install paddlepaddle-gpu==2.3.2 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`

**Comment by BorisPolonsky** [comment]
> pip安装的是CUDA11.2版本的paddle whl包，但你CUDA版本是11.4，目前官网上未显示对CUDA 11.4稳定支持，支持的CUDA版本参考官网安装文档：[https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html。建议选择合适的CUDA版本进行安装，或者尝试使用源码编译方式](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html%E3%80%82%E5%BB%BA%E8%AE%AE%E9%80%89%E6%8B%A9%E5%90%88%E9%80%82%E7%9A%84CUDA%E7%89%88%E6%9C%AC%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85%EF%BC%8C%E6%88%96%E8%80%85%E5%B0%9D%E8%AF%95%E4%BD%BF%E7%94%A8%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91%E6%96%B9%E5%BC%8F)

能不能做到像PyTorch pip安装whl一样，不依赖用户自己的cuda so呢

**Comment by dattran2346** [comment]
First, you need to check what CUDA version is available on your machine, I install cudatoolkit when I install pytorch so I check by

```
$ conda list | grep cuda
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi                                                                      nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
```

So my cudatoolkit is 11.7, I then install the correct paddlepaddle using this command
```
$ pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```

This solved my issue.
