### ISSUE TITLE
Paddle 目前自动搜索cuda库的路径是什么？感觉新安装的2.4.0以上版本都需要自行指定LD PATH

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/Paddle#50272]
### 请提出你的问题 Please ask your question

我发现我用 cuda .run安装的cuda都必须在指定 LD PATH后才能让paddle读取到形如cudart之类的动态链接库，我不是很清楚paddle对这个搜索的逻辑是什么，有什么方法在安装后无需指定LD PATH直接可以使用吗？这和paddle搜索动态依赖的方式是否有所关系？谢谢（我发现默认都是在 /usr/lib下搜索，如果把文件软连接进来也是一样可以成功的）

**Comment by tink2123** [comment]
可以查找本地“libcudart.so”所在目录，并将其添加到LD_LIBRARY_PATH中。

例如：执行find / -name libcudart.so, 发现 libcudart.so 在/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so路径下， 使用如下命令添加即可。

export LD_LIBRARY_PATH=/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so:${LD_LIBRARY_PATH}

**Comment by sanbuphy** [comment]
> 可以查找本地“libcudart.so”所在目录，并将其添加到LD_LIBRARY_PATH中。
> 
> 例如：执行find / -name libcudart.so, 发现 libcudart.so 在/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so路径下， 使用如下命令添加即可。
> 
> export LD_LIBRARY_PATH=/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so:${LD_LIBRARY_PATH}

你好，我是这样解决的问题，但我想知道这个是不是源码内搜索策略的问题（因为之前都不需要这一步），是什么原因导致的呢？如果是新手的话，很可能没办法解决这个问题

**Comment by sanbuphy** [comment]
已经自行解决

**Comment by holyseven** [comment]
@sanbuphy 想请问一下是怎么解决的？

**Comment by sanbuphy** [comment]
> @sanbuphy 想请问一下是怎么解决的？

应该是搜索规则的问题，我直接加入了默认的cuda（软链接到最新的cuda）地址到LD_PATH就好了(以及一些常用的lib库）

我考虑了WSL和ubuntu的通用性，结合常用地址迭代了这个：https://aistudio.baidu.com/aistudio/projectdetail/5448389

```
echo 'export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"' >> ~/.bashrc
echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/targets/x86_64-linux/lib' >> ~/.bashrc
echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/targets/x86_64-linux/lib/stubs/' >> ~/.bashrc
```

实际上这种cmake带来的问题估计都可以通过ldd或者丢失依赖，然后把对应的动态库加入到LD_LIBRARY_PATH解决，或者在系统/usr/lib下软链接一个就可以解决99.9%的问题

**Comment by holyseven** [comment]
明白了，多谢~
