### ISSUE TITLE
paddle 2.4.1 & cudatoolkit=11.7 时 cudnn的版本应该是什么？

### ISSUE THREAD

**Issue by Yam0214** [PaddlePaddle/Paddle#50977]
### 请提出你的问题 Please ask your question

想在conda虚拟环境里安装paddle以及cudatoolkit，用以下安装命令

```shell
conda install paddlepaddle-gpu==2.4.1 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
```

但是报下面错

```python
>>> import paddle
>>> x = paddle.to_tensor([1,2,3])
>>> x.tile((1,2,3))
W0227 17:41:51.633018 4138380 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.7
W0227 17:41:51.633183 4138380 dynamic_loader.cc:307] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/tensor/manipulation.py", line 3147, in tile
    return _C_ops.tile(x, repeat_times)
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:60)
```

```python
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0227 17:46:03.036801 4139194 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.7
W0227 17:46:03.036923 4139194 dynamic_loader.cc:307] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/utils/install_check.py", line 269, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/utils/install_check.py", line 173, in _run_static_single
    exe.run(startup_prog)
  File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/executor.py", line 1661, in _run_impl
    return new_exe.run(scope, list(feed.keys()), fetch_list,
  File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/executor.py", line 631, in run
    tensors = self._new_exe.run(scope, feed_names,
RuntimeError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/utils/install_check.py", line 33, in _simple_network
      weight = paddle.create_parameter(
    File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/layers/tensor.py", line 152, in create_parameter
      return helper.create_parameter(attr, shape, convert_dtype(dtype), is_bias,
    File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
      self.startup_program.global_block().create_parameter(
    File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/framework.py", line 3965, in create_parameter
      initializer(param, self)
    File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/initializer.py", line 56, in __call__
      return self.forward(param, block)
    File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/initializer.py", line 184, in forward
      op = block.append_op(type="fill_constant",
    File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/framework.py", line 4017, in append_op
      op = Operator(
    File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/framework.py", line 2858, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
      [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:60)
      [operator < fill_constant > error]
>>> 
```

**Comment by Braveblacklion** [comment]
I had the same error. Maybe this command helps (if you use Windows): 

python -m pip install paddlepaddle-gpu==2.4.1.post117 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

from the official Site (https://www.paddlepaddle.org.cn/)

**Comment by zoooo0820** [comment]
@Yam0214 you can refer to this [link](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#nvidia-gpu) . cuda11.7 + cudnn8.4

**Comment by Yam0214** [comment]
@Braveblacklion Thx for the advice, and I'm using paddle in ubuntu indeed.

I resolved the issue by executing this command.
```shell
# conda env config vars set LD_LIBRARY_PATH=$LD_LIBRARY_PATH:path/to/my/env/include:path/to/my/env/lib
conda env config vars set LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ouyanghongyu/anaconda3/envs/paddle2.4/include:/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib
```

refer to [使用conda安装了cudatoolkit11.7和cudnn8.6, paddle却报错：Cannot load cudnn shared library. Cannot invoke method](https://blog.csdn.net/hai0915/article/details/128690336?spm=1001.2101.3001.6650.3&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EYuanLiJiHua%7EPosition-3-128690336-blog-106967942.pc_relevant_landingrelevant&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EYuanLiJiHua%7EPosition-3-128690336-blog-106967942.pc_relevant_landingrelevant&utm_relevant_index=4)

**Comment by Study-boy-dot** [comment]
Below is how I fix this issue.
Ubuntu 22.04, using python venv instead of conda.
Download cudnn with the link: https://developer.nvidia.com/cudnn
