### ISSUE TITLE
develop版本paddle安装cudnn错误

### ISSUE THREAD

**Issue by zhangzhiqiangccm** [PaddlePaddle/Paddle#51190]
### 问题描述 Issue Description

cudnn:8.6   cudn:11.7
已经修改环境变量，但是

>      paddle.utils.run_check()
Running verify PaddlePaddle program ... 
I0304 17:44:36.816897 3122901 interpretercore.cc:273] New Executor is Running.
W0304 17:44:36.817149 3122901 gpu_resources.cc:85] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.7
W0304 17:44:36.817360 3122901 dynamic_loader.cc:307] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/app/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 278, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/opt/app/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 168, in _run_static_single
    exe.run(startup_prog)
  File "/opt/app/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1593, in run
    res = self._run_impl(
  File "/opt/app/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1862, in _run_impl
    return new_exe.run(
  File "/opt/app/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 682, in run
    tensors = self._new_exe.run(
RuntimeError: In user code:

PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
      [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:64)
      [operator < fill_constant > error]

### 版本&环境信息 Version & Environment Information

paddle:0.0.0
cuda:11.7
cudnn:8.6
修改了环境变量
 conda env config vars set LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/app/anaconda3/envs/paddle/include:/opt/app/anaconda3/envs/paddle/lib
 依旧报错

**Comment by yt605155624** [comment]
如果个人的 cuda 环境不会配置，可以尝试在官方 docker 中运行

**Comment by zhangzhiqiangccm** [comment]
> 如果个人的 cuda 环境不会配置，可以尝试在官方 docker 中运行

已经解决，paddle的develop版本和cudnn匹配时有些问题，更改环境变量可能是不起效的，需要重新链接。此外，develop版本缺少libnccl.so，需要从nvidia官网重新下载并设置链接，否则无法使用多卡。

**Comment by lywang76** [comment]
> > 如果个人的 cuda 环境不会配置，可以尝试在官方 docker 中运行
> 
> 已经解决，paddle的develop版本和cudnn匹配时有些问题，更改环境变量可能是不起效的，需要重新链接。此外，develop版本缺少libnccl.so，需要从nvidia官网重新下载并设置链接，否则无法使用多卡。

Can you show me how you solved the problem? 
I met the same issue.
