### ISSUE TITLE
OSError: (External) CUDNN error(1), CUDNN_STATUS_NOT_INITIALIZED.

### ISSUE THREAD

**Issue by ge35tay** [PaddlePaddle/Paddle#52250]
### bug描述 Describe the Bug

```bash
NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7
```
安装方式来自：https://www.paddlepaddle.org.cn/
```bash
conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
```

在进行solov2训练是报错：
```bash
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.65s)
creating index...
index created!
[03/28 14:45:08] ppdet.data.source.coco INFO: Load [900 samples valid, 0 samples invalid] in file /home/yinghan.huang/Projects/VisionDetect/datasets/train.json.
W0328 14:45:08.060938  7583 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.7, Runtime API Version: 11.7
W0328 14:45:08.062546  7583 gpu_resources.cc:91] device: 0, cuDNN Version: 8.8.
[03/28 14:45:13] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/yinghan.huang/.cache/paddle/weights/ResNet50_vd_ssld_v2_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main()
  File "tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "/home/yinghan.huang/Projects/VisionDetect/PaddleDetection/ppdet/engine/trainer.py", line 539, in train
    outputs = model(data)
  File "/home/yinghan.huang/anaconda3/envs/ppdet/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/yinghan.huang/Projects/VisionDetect/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 57, in forward
    self.model_arch()
  File "/home/yinghan.huang/Projects/VisionDetect/PaddleDetection/ppdet/modeling/architectures/solov2.py", line 67, in model_arch
    body_feats = self.backbone(self.inputs)
  File "/home/yinghan.huang/anaconda3/envs/ppdet/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/yinghan.huang/Projects/VisionDetect/PaddleDetection/ppdet/modeling/backbones/resnet.py", line 578, in forward
    conv1 = self.conv1(x)
  File "/home/yinghan.huang/anaconda3/envs/ppdet/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/yinghan.huang/anaconda3/envs/ppdet/lib/python3.8/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/home/yinghan.huang/anaconda3/envs/ppdet/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/yinghan.huang/Projects/VisionDetect/PaddleDetection/ppdet/modeling/backbones/resnet.py", line 118, in forward
    out = self.conv(inputs)
  File "/home/yinghan.huang/anaconda3/envs/ppdet/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/yinghan.huang/anaconda3/envs/ppdet/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 712, in forward
    out = F.conv._conv_nd(
  File "/home/yinghan.huang/anaconda3/envs/ppdet/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 140, in _conv_nd
    pre_bias = _C_ops.conv2d(
OSError: (External) CUDNN error(1), CUDNN_STATUS_NOT_INITIALIZED. 
  [Hint: Please search for the error code(1) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/backends/gpu/gpu_resources.cc:227)
```

### 其他补充信息 Additional Supplementary Information

看到issue中有类似问题，但是无解决方法，基本都是通过cudnn版本降级来解决。我这里遇到的问题如何定位出错原因？

**Comment by ge35tay** [comment]
问题已经解决，原因是虽然我们通过conda安装了cudatoolkit和cudnn，但是对应的cuda和cudnn的动态库并未被链接，解决方法是将动态库所在路径添加到环境变量LD_LIBRARY_PATH中，或者软链接到项目所在路径:
```bash
export LD_LIBRARY_PATH=/home/yinghan.huang/anaconda3/pkgs/cudatoolkit-11.2.2-hbe64b41_11/lib:/home/yinghan.huang/anaconda3/pkgs/cudnn-8.2.1.32-h86fa8c9_0/lib
```

**Comment by kaixin-bai** [comment]
补充信息：
报错信息的原因大概是本地用的cudnn和安装的cudatoolkit的cuda版本不匹配。

通过`conda search cudnn`得到conda上如下`cudnn`版本:
```bash
# Name                       Version           Build  Channel             
cudnn                          7.0.5       cuda8.0_0  pkgs/main           
cudnn                          7.1.2       cuda9.0_0  pkgs/main           
cudnn                          7.1.3       cuda8.0_0  pkgs/main           
cudnn                          7.2.1       cuda9.2_0  pkgs/main           
cudnn                          7.3.1      cuda10.0_0  pkgs/main           
cudnn                          7.3.1       cuda9.0_0  pkgs/main           
cudnn                          7.3.1       cuda9.2_0  pkgs/main           
cudnn                          7.6.0      cuda10.0_0  pkgs/main           
cudnn                          7.6.0      cuda10.1_0  pkgs/main           
cudnn                          7.6.0       cuda9.0_0  pkgs/main           
cudnn                          7.6.0       cuda9.2_0  pkgs/main           
cudnn                          7.6.4      cuda10.0_0  pkgs/main           
cudnn                          7.6.4      cuda10.1_0  pkgs/main           
cudnn                          7.6.4       cuda9.0_0  pkgs/main           
cudnn                          7.6.4       cuda9.2_0  pkgs/main           
cudnn                          7.6.5      cuda10.0_0  pkgs/main           
cudnn                          7.6.5      cuda10.1_0  pkgs/main           
cudnn                          7.6.5      cuda10.2_0  pkgs/main           
cudnn                          7.6.5       cuda9.0_0  pkgs/main           
cudnn                          7.6.5       cuda9.2_0  pkgs/main           
cudnn                          8.2.1      cuda11.3_0  pkgs/main           
cudnn                       8.9.2.26        cuda11_0  pkgs/main 
```

我们本地的cuda是11.7，cudnn是8.8，我们直接按照安装说明安装`paddle`后续会报`cudnn`的错，最后的解决方案是使用`paddle`和在conda中安装低版本的cudatoolkit11.2配上cudnn8.2.1，这样才能顺利运行`paddle`.
