### ISSUE TITLE
symbol cudaGraphDebugDotPrint, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/Paddle#52623]
### 请提出你的问题 Please ask your question

安装完paddle之后，import paddle 之后报下面这个错误：
```
>>> import paddle
Error: Can not import paddle core while this file exists: /root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/core.py", line 338, in <module>
    raise e
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: /root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: symbol cudaGraphDebugDotPrint, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference

```
我的版本：
系统：centos
cuda:  11.6
paddlepaddle: paddlepaddle-gpu   =  2.4.2.post116

**Comment by FrostML** [comment]
确认下环境里是否有多个版本的 CUDA？

**Comment by Tian14267** [comment]
一共有两个版本的cuda，但是链接修改过了
![image](https://user-images.githubusercontent.com/27938135/230540281-15ed38a3-5a55-4a91-a747-8f458c20ca29.png)
@FrostML

**Comment by FrostML** [comment]
最好能保证环境里确定唯一的 CUDA 版本，通常有多个环境存在不好说系统自动去找了哪一个。可以看看 `libpaddle.so` 链接的哪一个 `libcudart.so.11.0`。

**Comment by Tian14267** [comment]
@FrostML 你好大神，我找了下环境中的`paddle`和`libpaddle.so`，但是无法判断它需要链接哪个？这个该怎么确定呢
![image](https://user-images.githubusercontent.com/27938135/230549709-0343b7fb-7557-48d6-8723-3e9004437732.png)

**Comment by Tian14267** [comment]
通过删除环境，重新安装，解决。

**Comment by bdbaigc** [comment]
> @FrostML 你好大神，我找了下环境中的`paddle`和`libpaddle.so`，但是无法判断它需要链接哪个？这个该怎么确定呢 ![image](https://user-images.githubusercontent.com/27938135/230549709-0343b7fb-7557-48d6-8723-3e9004437732.png)

ldd /root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/libpaddle.so 就可以看到实际用的libcudart.so.11.0是哪个了，比如我电脑输出是：
libcudart.so.11.0 => /usr/local/cuda-11.2/lib64/libcudart.so.11.0 (0x00007f39f7cee000)


我解决这个问题是用conda安装了11.7的cuda驱动
安装示例：conda install -c conda-forge cudatoolkit=11.7
安装之后，把conda安装的cuda驱动加入到LIB搜索路径的前面，问题就解决了
export LD_LIBRARY_PATH=/root/miniconda3/envs/research/lib/:$LD_LIBRARY_PATH
