### ISSUE TITLE
OSError: (External) CUDA error(719), unspecified launch failure. 

### ISSUE THREAD

**Issue by soyons** [PaddlePaddle/Paddle#53754]
多人遇见此问题，影响工作，报错不明确
adt-40g-5-yq01-k8s-gpu-a100-8-0
paddlepaddle_gpu-2.4.2.post112-cp37-cp37m-linux_x86_64.whl

st-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/paddlejob/workspace/env_run/multipath/model/predecision.py", line 1035, in forward
    obs_feature, obs_polyline_feature, target_polyline_id, lane_mask=self.lane_polyline_mask[self.frame_num:]) #[3, 448], [3, 64, 256], [3, 1], [3, 256]
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/paddlejob/workspace/env_run/multipath/model/multipath.py", line 324, in forward
    lane_pred = self.lane_attention(encoded_feature, polyline_feature, lane_mask)
  File "/root/paddlejob/workspace/env_run/multipath/model/multipath.py", line 276, in lane_attention
    encoded_feature = F.normalize(encoded_feature, p=2, axis=-1)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/functional/norm.py", line 89, in normalize
    eps = fluid.dygraph.base.to_variable([epsilon], dtype=x.dtype)
  File "<decorator-gen-52>", line 2, in to_variable
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 796, in to_variable
    True)
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: Please search for the error code(719) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:259)

terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  (External) CUDA error(719), unspecified launch failure. 
  [Hint: Please search for the error code(719) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:283)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
1   paddle::distributed::ProcessGroupNCCL::~ProcessGroupNCCL()
2   phi::GPUContext::~GPUContext()
3   phi::GPUContext::~GPUContext()
4   phi::CUDAStream::~CUDAStream()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1683871398 (unix time) try "date -d @1683871398" if you are using GNU date ***]
LAUNCH INFO 2023-05-12 14:03:26,209 Exit code -15
  [SignalInfo: *** SIGABRT (@0x1a7c0) received by PID 108480 (TID 0x7efbffc0f740) from PID 108480 ***]

**Comment by YanhuiDua** [comment]
你好，请提供下paddle版本/cuda版本以及最小复现脚本

**Comment by starplanet** [comment]
paddle版本：
```
paddlepaddle-gpu               2.4.0.post112
```
cuda版本：
```
Thu May 18 14:59:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:05:00.0 Off |                    0 |
| N/A   65C    P0   260W / 300W |  13307MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

上一次训练还是好的，中止后，再跑脚本，就报cuda错误，不知道怎么恢复

完整错误信息：
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_8170/3364925475.py in <module>
----> 1 train()

/tmp/ipykernel_8170/2694572938.py in train()
    148         drop_last=False,
    149     )
--> 150     model = paddle.Model(RotNet())
    151     optim = paddle.optimizer.Adam(learning_rate=0.0008, parameters=model.parameters())
    152     loss = paddle.nn.CrossEntropyLoss()

/tmp/ipykernel_8170/2694572938.py in __init__(self, num_classes, train)
     58         super(RotNet, self).__init__()
     59         self.num_classes = num_classes
---> 60         self.backbone = models.resnet50(pretrained=True, num_classes=self.num_classes)
     61 
     62     def forward(self, inputs):

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/models/resnet.py in resnet50(pretrained, **kwargs)
    424             # [1, 1000]
    425     """
--> 426     return _resnet('resnet50', BottleneckBlock, 50, pretrained, **kwargs)
    427 
    428 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/models/resnet.py in _resnet(arch, Block, depth, pretrained, **kwargs)
    322                                                 model_urls[arch][1])
    323 
--> 324         param = paddle.load(weight_path)
    325         model.set_dict(param)
    326 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py in load(path, **configs)
   1053                             if isinstance(load_result[key], np.ndarray):
   1054                                 load_result[key] = _ndarray_to_tensor(
-> 1055                                     load_result[key], config.return_numpy
   1056                                 )
   1057 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py in _ndarray_to_tensor(obj, return_numpy)
    453         return obj
    454     if _non_static_mode():
--> 455         return paddle.to_tensor(obj)
    456     else:
    457         return _to_LodTensor(obj)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py in to_tensor(data, dtype, place, stop_gradient)
    544 
    545     if _non_static_mode():
--> 546         return _to_tensor_non_static(data, dtype, place, stop_gradient)
    547 
    548     # call assign for static graph

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py in _to_tensor_non_static(data, dtype, place, stop_gradient)
    409             zero_copy=False,
    410             name=None,
--> 411             stop_gradient=stop_gradient,
    412         )
    413     else:

OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: Please search for the error code(719) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:259)
```

解决了，原来是jupyter kernel挂掉了，重启jupyter内核，就可以了

**Comment by YanhuiDua** [comment]
好的，还有其他问题吗？没有的话这个issue先关闭掉了，有问题的话欢迎再提问~
