### ISSUE TITLE
运行optimizer.minimize(model_dict.loss, model_dict.startup_program)时报错ExternalError: NCCL error(1), unhandled cuda error. 

### ISSUE THREAD

**Issue by hrbxjylxjj** [PaddlePaddle/Paddle#54171]
### 请提出你的问题 Please ask your question

使用GPU进行模型训练，观察代码发现运行到optimizer.minimize(model_dict.loss, model_dict.startup_program)这一行时报错

C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::StandaloneExecutor::Run(paddle::framework::Scope*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&)
1   paddle::framework::InterpreterCore::Run(std::vector<std::string, std::allocator<std::string > > const&, bool)
2   paddle::framework::interpreter::BuildOpFuncList(phi::Place const&, paddle::framework::BlockDesc const&, std::set<std::string, std::less<std::string >, std::allocator<std::string > > const&, std::vector<paddle::framework::OpFuncNode, std::allocator<paddle::framework::OpFuncNode> >*, paddle::framework::VariableScope*, paddle::framework::interpreter::ExecutionConfig const&, bool)
3   paddle::framework::interpreter::HandleOperatorBase(phi::Place const&, paddle::framework::VariableScope const*, std::shared_ptr<paddle::framework::OperatorBase>, paddle::framework::OpFuncNode*, paddle::framework::Scope*)
4   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
5   paddle::operators::CCommInitAllOp::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
6   paddle::platform::NCCLCommContext::CreateAllNCCLComms(std::vector<int, std::allocator<int> > const&, int)
7   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
8   phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

ExternalError: NCCL error(1), unhandled cuda error. 
  [Hint: Please search for the error code(1) on website (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html#ncclresult-t) to get Nvidia's official solution and advice about NCCL Error.] (at /root/paddlejob/paddle.jxw/Paddle/paddle/fluid/platform/collective_helper.cc:137)
  [operator < c_comm_init_all > error]  [operator < c_comm_init_all > error]

**Comment by 2742195759** [comment]
minimize 是不是应该传入 main_program，而不是 start up program呢？

**Comment by MingqiFANG** [comment]
optimizer.minimize应该不用传入main_program或者 start up program吧？直接传入model.loss就好了
