### ISSUE TITLE
unittest中通讯相关的部分测例没有通过

### ISSUE THREAD

**Issue by zepingWww** [PaddlePaddle/Paddle#54855]
### 请提出你的问题 Please ask your question

在编译完paddle后，只需要测试CPU相关UT能否跑通，跑的脚本代码是`PY_VERSION=3.8 bash -x paddle/scripts/paddle_build.sh cicheck_py37`。
跑完后通讯相关的部分测例没有通过:
```
The following tests FAILED:
         20 - graph_node_test (Failed)
        115 - test_analyzer_dist_model (Failed)
        1111 - test_communicator_async (Timeout)
        1112 - test_communicator_geo (Timeout)
        1114 - test_fleet_base_2 (Timeout)
        1115 - test_fleet_base_3 (Failed)
        1213 - test_fleet_fp16_allreduce_meta_optimizer (Timeout)
        1224 - test_communicator_sync (Timeout)
Errors while running CTest
```

运行环境：
系统：CentOS Linux 7
python 3.8

部分测例的报错：
`ctest -R test_analyzer_dist_model -V`
```
UpdateCTestConfiguration  from :/paddle/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/paddle/build/DartConfiguration.tcl
Test project /paddle/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 115
    Start 115: test_analyzer_dist_model

115: Test command: /paddle/build/paddle/fluid/inference/tests/api/test_analyzer_dist_model "--infer_model=/paddle/build/third_party/inference_demo/ocr/model"
115: Environment variables:
115:  FLAGS_cudnn_deterministic=true
115: Test timeout computed to be: 10000000
115: [==========] Running 1 test from 1 test case.
115: [----------] Global test environment set-up.
115: [----------] 1 test from test_dist_model
115: [ RUN      ] test_dist_model.dist_model
115: Analysis Predictor DistModel test.
115: WARNING: Logging before InitGoogleLogging() is written to STDERR
115: E0625 18:01:49.625959 26816 analysis_config.cc:121] Please use PaddlePaddle with GPU version.
115: unknown file: Failure
115: C++ exception with description "(NotFound) Cannot open file /paddle/build/third_party/inference_demo/ocr/model/__model__, please confirm whether the file is normal.
115:   [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at /paddle/paddle/fluid/inference/api/analysis_predictor.cc:2105)
115: " thrown in the test body.
115: [  FAILED  ] test_dist_model.dist_model (21 ms)
115: [----------] 1 test from test_dist_model (21 ms total)
115:
115: [----------] Global test environment tear-down
115: [==========] 1 test from 1 test case ran. (21 ms total)
115: [  PASSED  ] 0 tests.
115: [  FAILED  ] 1 test, listed below:
115: [  FAILED  ] test_dist_model.dist_model
115:
115:  1 FAILED TEST
1/1 Test #115: test_analyzer_dist_model .........***Failed    0.22 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
RUN_TYPE=INFER    =   0.22 sec*proc (1 test)

Total Test time (real) =   0.69 sec

The following tests FAILED:
        115 - test_analyzer_dist_model (Failed)
Errors while running CTest
```

`ctest -R test_communicator_sync -V`
```
UpdateCTestConfiguration  from :/paddle/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/paddle/build/DartConfiguration.tcl
Test project /paddle/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1224
    Start 1224: test_communicator_sync

1224: Test command: /usr/local/bin/cmake "-E" "env" "PYTHONPATH=/paddle/build/python" "FLAGS_communicator_send_queue_size=1" "FLAGS_communicator_max_merge_var_num=1" "http_proxy=" "https_proxy=" "PYTHONPATH=../..:/paddle/build/python" "/root/miniconda3/envs/paddle-build/bin/python3.8" "/paddle/tools/test_runner.py" "test_communicator_sync"
1224: Test timeout computed to be: 10000000
1224: [2023-06-25 18:02:40,283] [    INFO] distributed_strategy.py:153 - distributed strategy initialized
1224: [2023-06-25 18:02:40,302] [    INFO] distributed_strategy.py:153 - distributed strategy initialized
1224: I0625 18:02:40.479349 26820 server.cpp:1107] Server[paddle::distributed::DownpourPsClientService] is serving on port=8500.
1224: I0625 18:02:40.479452 26820 server.cpp:1110] Check out http://DevGen04:8500 in web browser.
1224: I0625 18:02:40.479549 26820 brpc_ps_client.cc:127] BrpcPsClient Service addr: 10.10.7.5, 8500, 0
1224: I0625 18:02:40.481554 26820 brpc_ps_client.cc:196] Client connect success:10.10.7.5:8500,
1224: I0625 18:02:50.484787 26820 brpc_ps_client.cc:681] BrpcPsClient::flush begin
1224: I0625 18:02:50.585011 26820 brpc_ps_client.cc:692] BrpcPsClient::flush done
1224: I0625 18:02:50.585024 26820 brpc_ps_client.cc:722] BrpcPsClient::FinalizeWorker begin join thread
1224: I0625 18:02:50.590689 26820 brpc_ps_client.cc:727] BrpcPsClient::FinalizeWorker begin join server
1224: I0625 18:02:50.590698 26820 server.cpp:1167] Server[paddle::distributed::DownpourPsClientService] is going to quit
1224: I0625 18:02:50.590898 26820 brpc_ps_client.cc:731] BrpcPsClient::FinalizeWorker done
1224: /paddle/build/python/paddle/distributed/fleet/base/role_maker.py:327: UserWarning: gloo is not initialized, will not communicator with other nodes
1224:   warnings.warn(self._err_init)
1224: /paddle/build/python/paddle/distributed/fleet/base/role_maker.py:371: UserWarning: gloo is not initialized, will not communicator with other nodes
1224:   warnings.warn(self._err_init)
1224: /paddle/build/python/paddle/distributed/ps/the_one_ps.py:1252: UserWarning: gloo may not initialize correctly
1224:   warnings.warn("gloo may not initialize correctly")
1224: fl-ps > coordinator address is null!
1224: is_heter_ps_mode in distributed_ops_pass False?
1224: is_heter_ps_mode? False
1224: remote_optimize_vars: [], remote_optimize_op_role_vars: [], local_optimize_vars: []
1224: is_heter_ps_mode? False
1224: paddle.static.default_startup_program: <function default_startup_program at 0x7fefd057c9d0>
1224: fl-ps > local_sparse: [], remote_sparse: []
1224: is_heter_ps_mode? False
1224: is_heter_ps_mode? False
1224: is_heter_ps_mode? False
1224: communicator config: {'communicator_max_merge_var_num': '1', 'communicator_send_wait_times': '5', 'communicator_thread_pool_size': '5', 'communicator_send_queue_size': '1'}
1224: fl-ps > trainer_endpoint: 127.0.0.1:36001
1224: fl-ps > with_coordinator? False
1224: fl-ps > coordinator addr: []
1224: create c2c connection done
1224:
1224:
1224: --------------------------------------
1224: C++ Traceback (most recent call last):
1224: --------------------------------------
1224: No stack trace in paddle, may be caused by external reasons.
1224:
1224: ----------------------
1224: Error Message Summary:
1224: ----------------------
1224: FatalError: `Segmentation fault` is detected by the operating system.
1224:   [TimeInfo: *** Aborted at 1687687370 (unix time) try "date -d @1687687370" if you are using GNU date ***]
1224:   [SignalInfo: *** SIGSEGV (@0x8) received by PID 26820 (TID 0x7fefd6476740) from PID 8 ***]
1224:
1224: Segmentation fault
1/1 Test #1224: test_communicator_sync ...........***Failed   32.51 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  33.01 sec

The following tests FAILED:
        1224 - test_communicator_sync (Failed)
Errors while running CTest
```

**Comment by zepingWww** [comment]
因为glibc版本比较旧，所以用的gcc7.5.0，补充一下编译选项：
```
cmake -S . -B build \
-DCMAKE_BUILD_TYPE=Release \
-DPYTHON_EXECUTABLE:FILEPATH=/root/miniconda3/envs/paddle-build/bin/python3.8 \
-DPYTHON_INCLUDE_DIR:PATH=/root/miniconda3/envs/paddle-build/include/python3.8 \
-DPYTHON_LIBRARIES:FILEPATH=/root/miniconda3/envs/paddle-build/lib/libpython3.so \
-DWITH_GPU=OFF \
-DWITH_CUDNN_DSO=OFF \
-DWITH_TENSORRT=OFF \
-DWITH_ROCM=OFF \
-DWITH_CINN=OFF \
-DWITH_DISTRIBUTE=ON \
-DWITH_MKL=ON \
-DWITH_AVX=ON \
-DCUDA_ARCH_NAME=All \
-DNEW_RELEASE_PYPI=OFF \
-DNEW_RELEASE_ALL=OFF \
-DNEW_RELEASE_JIT=OFF \
-DWITH_PYTHON=ON \
-DWITH_TESTING=ON \
-DWITH_COVERAGE=OFF \
-DWITH_INCREMENTAL_COVERAGE=OFF \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DWITH_CONTRIB=ON \
-DWITH_INFERENCE_API_TEST=ON \
-DWITH_INFRT=OFF \
-DPY_VERSION=3.8 \
-DCMAKE_INSTALL_PREFIX=/paddle/install \
-DWITH_PSCORE=ON \
-DWITH_PSLIB=OFF \
-DWITH_GLOO=ON \
-DLITE_GIT_TAG=release/v2.10 \
-DWITH_XPU=OFF \
-DWITH_MLU=OFF \
-DWITH_IPU=OFF \
-DWITH_CNCL=OFF \
-DXPU_SDK_ROOT= \
-DWITH_LITE=OFF \
-DWITH_XPU_BKCL=OFF \
-DWITH_ARM=OFF \
-DWITH_ASCEND=OFF \
-DWITH_ASCEND_CL=OFF \
-DWITH_ASCEND_INT64=OFF \
-DWITH_STRIP=ON \
-DON_INFER=ON \
-DWITH_HETERPS=OFF \
-DWITH_FLUID_ONLY=OFF \
-DCUDA_ARCH_BIN= \
-DWITH_RECORD_BUILDTIME=OFF \
-DWITH_UNITY_BUILD=ON\
-DWITH_ONNXRUNTIME=OFF \
-DWITH_CUDNN_FRONTEND=OFF \
-DCMAKE_CXX_FLAGS="-Wno-error -w" \
-DCMAKE_C_FLAGS="-Wno-error -w" \
-DWITH_SETUP_INSTALL=OFF

cmake --build build --target install --parallel 32
```

**Comment by thisjiang** [comment]
请问Paddle代码版本是develop最新代码的么？

**Comment by zepingWww** [comment]
> 请问Paddle代码版本是develop最新代码的么？

b166581a3c89cc74ae0737480eda5c4d093eed7f
目前是这个

**Comment by thisjiang** [comment]
可以试试最新代码下编译测试会不会有问题，最近Paddle正升级C++17 & 单测迁移，不确定上个月的代码会不会有问题。

**Comment by thisjiang** [comment]
Hi~该问题目前有两个解决方法。一个是更新paddle到该commit之后的版本：https://github.com/PaddlePaddle/Paddle/commit/d740f67ae7513cc031687148db6e9a5a5a1cd8f4 。另一个办法是降级protobuf的版本到3.20.2

**Comment by zepingWww** [comment]
> Hi~该问题目前有两个解决方法。一个是更新paddle到该commit之后的版本：[d740f67](https://github.com/PaddlePaddle/Paddle/commit/d740f67ae7513cc031687148db6e9a5a5a1cd8f4) 。另一个办法是降级protobuf的版本到3.20.2

好的，我试一下哈，多谢~

**Comment by thisjiang** [comment]
Hi~请问更新代码后问题解决了么？解决了的话我就close掉这个issue了

**Comment by zepingWww** [comment]
> test_analyzer_dist_model

上面的问题解决了，目前还有4个有问题，3个是Timeout的问题，一个是精度问题。

```
The following tests FAILED:
        576 - test_imperative_transformer_sorted_gradient (Timeout)
        1005 - test_tensordot (Failed)
        1238 - test_bmn (Timeout)
        1777 - test_vision_models (Timeout)
```


test_tensordot 这个单测有时候过有时候不过：

```
(paddle_build) [root@DevGen04 build]# ctest -R test_tensordot -V
UpdateCTestConfiguration  from :/paddle/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/paddle/build/DartConfiguration.tcl
Test project /paddle/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1005
    Start 1005: test_tensordot

1005: Test command: /usr/local/bin/cmake "-E" "env" "PYTHONPATH=/paddle/build/python" "/root/anaconda3/envs/paddle_build/bin/python3.8" "/paddle/tools/test_runner.py" "test_tensordot"
1005: Test timeout computed to be: 200
1005: I0628 10:27:18.787497 43828 interpretercore.cc:282] New Executor is Running.
1005: Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
1005: If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
1/1 Test #1005: test_tensordot ...................   Passed   16.02 sec

The following tests passed:
        test_tensordot

100% tests passed, 0 tests failed out of 1

Total Test time (real) =  16.46 sec
(paddle_build) [root@DevGen04 build]# ctest -R test_tensordot -V
UpdateCTestConfiguration  from :/paddle/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/paddle/build/DartConfiguration.tcl
Test project /paddle/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1005
    Start 1005: test_tensordot

1005: Test command: /usr/local/bin/cmake "-E" "env" "PYTHONPATH=/paddle/build/python" "/root/anaconda3/envs/paddle_build/bin/python3.8" "/paddle/tools/test_runner.py" "test_tensordot"
1005: Test timeout computed to be: 200
1005: I0628 10:27:36.785554 43991 interpretercore.cc:282] New Executor is Running.
1005: Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
1005: If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
1005: test_tensordot failed
1005:  F..............................
1005: ======================================================================
1005: FAIL: test_dygraph (test_tensordot.TestTensordotAPI)
1005: ----------------------------------------------------------------------
1005: Traceback (most recent call last):
1005:   File "/paddle/build/python/paddle/fluid/tests/unittests/test_tensordot.py", line 204, in test_dygraph
1005:     np.testing.assert_allclose(paddle_res, np_res, rtol=1e-6)
1005:   File "/root/anaconda3/envs/paddle_build/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
1005:     assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
1005:   File "/root/anaconda3/envs/paddle_build/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
1005:     raise AssertionError(msg)
1005: AssertionError:
1005: Not equal to tolerance rtol=1e-06, atol=0
1005:
1005: Mismatched elements: 1 / 1 (100%)
1005: Max absolute difference: 0.00016785
1005: Max relative difference: 1.0340087e-06
1005:  x: array([162.326], dtype=float32)
1005:  y: array(162.32617, dtype=float32)
1005:
1005: ----------------------------------------------------------------------
1005: Ran 31 tests in 14.009s
1005:
1005: FAILED (failures=1)
1005:
1/1 Test #1005: test_tensordot ...................***Failed   15.48 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  15.93 sec

The following tests FAILED:
        1005 - test_tensordot (Failed)
Errors while running CTest
```

这个我打开编译选项WITH_AVX=ON看看会不会出现问题。

剩下的TIMEOUT的单测我理解可能是运行太慢了，同样打算改一下编译选项AVX=ON看一下能不能解决。

**Comment by zepingWww** [comment]
@thisjiang 没问题了，我关闭issue了~
