### ISSUE TITLE
cuda11.8版本下安装paddle check失败，提示缺少(libcudnn.so)，但是pytorchgpu完全正常

### ISSUE THREAD

**Issue by ruler77** [PaddlePaddle/Paddle#55805]
### 请提出你的问题 Please ask your question

cuda11.8版本下安装paddle check失败，提示缺少(libcudnn.so)，提示erro信息如下：
W0729 20:06:45.411698 568089 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 11.8, Runtime API Version: 11.8
W0729 20:06:45.411837 568089 dynamic_loader.cc:303] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
 ……
    File "/home/hao/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2781, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
      [Hint: cudnn_dso_handle should not be null.] (at ../paddle/phi/backends/dynload/cudnn.cc:64)
      [operator < fill_constant > error]

pytorch上运行正常，可正常使用gpu，也使用过find查找libcudnn.so确实没有，cuda和cudnn均按nvidia官网要求安装，版本完全匹配
![1](https://github.com/PaddlePaddle/Paddle/assets/34652236/384f8a6e-83bb-4672-af67-7653c5480bfa)
对应的/usr/local/cuda-11.8/lib64内容如下（已与/usr/local/cuda作软连接，内容一致）
![2](https://github.com/PaddlePaddle/Paddle/assets/34652236/e060d749-2dc3-41de-b089-8a00e53967dc)
服务器为ubuntu22.04lts 
bashrc文件内容打印如下：
'''
export CUDA_HOME=/usr/local/cuda
export PATH="$CUDA_HOME/bin:$PATH"
export LD_LIBRARY_PATH="$CUDA_HOME/lib64:$LD_LIBRARY_PATH"
'''

**Comment by nemonameless** [comment]
你好，可以试下
```
export LD_LIBRARY_PATH='/home/{用户名}/anaconda3/envs/{虚拟环境名}/lib/'

pa>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0124 22:52:18.063221 126315 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
W0124 22:52:18.068292 126315 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```
相关问题，https://github.com/PaddlePaddle/Paddle/issues/51190 https://github.com/PaddlePaddle/Paddle/issues/49106

**Comment by ruler77** [comment]
> 你好，可以试下
> 
> ```
> export LD_LIBRARY_PATH='/home/{用户名}/anaconda3/envs/{虚拟环境名}/lib/'
> 
> pa>>> paddle.utils.run_check()
> Running verify PaddlePaddle program ...
> W0124 22:52:18.063221 126315 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
> W0124 22:52:18.068292 126315 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
> PaddlePaddle works well on 1 GPU.
> PaddlePaddle works well on 1 GPUs.
> PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
> ```
> 
> 相关问题，#51190 #49106

用过你的方法没有效果，不过问题目前已经解决，我确认cuda里面确实没有libcudnn.so文件(安装过cudnn)，考虑到版本接口问题(错误提示Cannot invoke method cudnnGetVersion.，估计是接口问题)，我重新在https://developer.nvidia.com/rdp/cudnn-archive下载了tar.xz格式cudnn库复制到cuda中对应文件，此时已经有libcudnn.so文件了(中间报错许多xx.so too short，符号连接问题，重新建立到对应对应文件.so.x.y.0就行)，后续执行check就成功了，测试paddle 检测也能正常运行了(中间还出现了其他问题，不过全是版本问题导致接口调用错误)。
![image](https://github.com/PaddlePaddle/Paddle/assets/34652236/6f4a923a-9a7a-44b3-ac1a-c6df727f877d)

**Comment by plunder12** [comment]
我遇到了相同的问题，由于是没有管理员权限，没办法修改/usr下的cuda文件，这样有什么办法引入指定路径下的cudnn文件吗？本地已经安装了cuda117，当时没有cudnn

**Comment by inSight-mk1** [comment]
> 我遇到了相同的问题，由于是没有管理员权限，没办法修改/usr下的cuda文件，这样有什么办法引入指定路径下的cudnn文件吗？本地已经安装了cuda117，当时没有cudnn

conda install cudnn

**Comment by plunder12** [comment]
已收到！
