### ISSUE TITLE
多卡训练卡在"I0913 13:22:17.471719 24640 tcp_utils.cc:130] Successfully connected to 10.3.15.202:35873"

### ISSUE THREAD

**Issue by Yiveen** [PaddlePaddle/Paddle#57286]
### bug描述 Describe the Bug

在issue中发现很多人发过类似的问题，但是没有答复。我的环境是：
```bash
paddlepaddle-gpu          2.5.1.post116
paddleseg                 2.8.0
cudatoolkit               11.6.0              hecad31d_10    conda-forge
cudnn                     8.9.2.26               cuda11_0
```

在Paddleseg中通过以下命令进行多卡训练时会卡住，用多卡训练的案例也会卡在同样的地方：
```bash
~/PaddleSeg$ python -m paddle.distributed.launch tools/train.py --config configs/fastfcn/fastfcn_resnet50_os8_ade20k_480x480_120k_vimaProject.yml --do_eval --use_vdl --save_interval 500 --save_dir output_fastfcn_vimaProject
```

```bash
export CUDA_VISIBLE_DEVICES=0,1,2,3 # 设置4张可用的卡
python -m paddle.distributed.launch tools/train.py \
       --config configs/quick_start/pp_liteseg_optic_disc_512x512_1k.yml \
       --do_eval \
       --use_vdl \
       --save_interval 500 \
       --save_dir output
```

卡住的位置是：
```bash
~/PaddleSeg$ python -m paddle.distributed.launch tools/train.py --config configs/fastfcn/fastfcn_resnet50_os8_ade20k_480x480_120k_vimaProject.yml --do_eval --use_vdl --save_interval 500 --save_dir output_fastfcn_vimaProject
LAUNCH INFO 2023-09-13 13:22:12,450 -----------  Configuration  ----------------------
LAUNCH INFO 2023-09-13 13:22:12,450 auto_parallel_config: None
LAUNCH INFO 2023-09-13 13:22:12,450 devices: None
LAUNCH INFO 2023-09-13 13:22:12,450 elastic_level: -1
LAUNCH INFO 2023-09-13 13:22:12,450 elastic_timeout: 30
LAUNCH INFO 2023-09-13 13:22:12,450 gloo_port: 6767
LAUNCH INFO 2023-09-13 13:22:12,450 host: None
LAUNCH INFO 2023-09-13 13:22:12,450 ips: None
LAUNCH INFO 2023-09-13 13:22:12,450 job_id: default
LAUNCH INFO 2023-09-13 13:22:12,450 legacy: False
LAUNCH INFO 2023-09-13 13:22:12,450 log_dir: log
LAUNCH INFO 2023-09-13 13:22:12,450 log_level: INFO
LAUNCH INFO 2023-09-13 13:22:12,450 log_overwrite: False
LAUNCH INFO 2023-09-13 13:22:12,450 master: None
LAUNCH INFO 2023-09-13 13:22:12,450 max_restart: 3
LAUNCH INFO 2023-09-13 13:22:12,451 nnodes: 1
LAUNCH INFO 2023-09-13 13:22:12,451 nproc_per_node: None
LAUNCH INFO 2023-09-13 13:22:12,451 rank: -1
LAUNCH INFO 2023-09-13 13:22:12,451 run_mode: collective
LAUNCH INFO 2023-09-13 13:22:12,451 server_num: None
LAUNCH INFO 2023-09-13 13:22:12,451 servers: 
LAUNCH INFO 2023-09-13 13:22:12,451 start_port: 6070
LAUNCH INFO 2023-09-13 13:22:12,451 trainer_num: None
LAUNCH INFO 2023-09-13 13:22:12,451 trainers: 
LAUNCH INFO 2023-09-13 13:22:12,451 training_script: tools/train.py
LAUNCH INFO 2023-09-13 13:22:12,451 training_script_args: ['--config', 'configs/fastfcn/fastfcn_resnet50_os8_ade20k_480x480_120k_vimaProject.yml', '--do_eval', '--use_vdl', '--save_interval', '500', '--save_dir', 'output_fastfcn_vimaProject']
LAUNCH INFO 2023-09-13 13:22:12,451 with_gloo: 1
LAUNCH INFO 2023-09-13 13:22:12,451 --------------------------------------------------
LAUNCH INFO 2023-09-13 13:22:12,451 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2023-09-13 13:22:12,460 Run Pod: pmpmpg, replicas 6, status ready
LAUNCH INFO 2023-09-13 13:22:12,557 Watching Pod: pmpmpg, replicas 6, status running
2023-09-13 13:22:14 [WARNING]	Add the `num_classes` in train_dataset and val_dataset config to model config. We suggest you manually set `num_classes` in model config.
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
2023-09-13 13:22:14 [INFO]	
------------Environment Information-------------
platform: Linux-4.15.0-206-generic-x86_64-with-glibc2.17
Python: 3.8.17 (default, Jul  5 2023, 21:04:15) [GCC 11.2.0]
Paddle compiled with cuda: True
NVCC: Not Available
cudnn: 8.9
GPUs used: 6
CUDA_VISIBLE_DEVICES: 0,1,4,5,6,7
GPU: ['GPU 0: NVIDIA GeForce', 'GPU 1: NVIDIA GeForce', 'GPU 2: NVIDIA GeForce', 'GPU 3: NVIDIA GeForce', 'GPU 4: NVIDIA GeForce', 'GPU 5: NVIDIA GeForce', 'GPU 6: NVIDIA GeForce', 'GPU 7: NVIDIA GeForce']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddleSeg: 2.8.0
PaddlePaddle: 2.5.1
OpenCV: 4.5.5
------------------------------------------------
2023-09-13 13:22:14 [INFO]	
---------------Config Information---------------
batch_size: 16
iters: 120000
train_dataset:
  dataset_root: /data/net/dl_data/ProjectDatasets_bkx/VIMA_dataset/new_dataset
  mode: train
  num_classes: 7
  train_path: /data/net/dl_data/ProjectDatasets_bkx/VIMA_dataset/new_dataset/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 480
    - 480
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /data/net/dl_data/ProjectDatasets_bkx/VIMA_dataset/new_dataset
  mode: val
  num_classes: 7
  transforms:
  - type: Normalize
  type: Dataset
  val_path: /data/net/dl_data/ProjectDatasets_bkx/VIMA_dataset/new_dataset/val.txt
optimizer:
  momentum: 0.9
  type: SGD
  weight_decay: 4.0e-05
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
loss:
  coef:
  - 1
  - 0.4
  - 0.2
  types:
  - type: CrossEntropyLoss
  - type: CrossEntropyLoss
  - type: SECrossEntropyLoss
model:
  add_lateral: true
  aux_loss: true
  backbone:
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  mid_channels: 512
  num_classes: 7
  num_codes: 32
  type: FastFCN
  use_jpu: true
  use_se_loss: true
------------------------------------------------

/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
2023-09-13 13:22:15 [INFO]	Set device: gpu
2023-09-13 13:22:15 [INFO]	Use the following config to build model
model:
  add_lateral: true
  aux_loss: true
  backbone:
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  mid_channels: 512
  num_classes: 7
  num_codes: 32
  type: FastFCN
  use_jpu: true
  use_se_loss: true
W0913 13:22:15.307772 24640 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W0913 13:22:15.307852 24640 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.7, Runtime API Version: 11.6
W0913 13:22:15.307884 24640 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
2023-09-13 13:22:16 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2023-09-13 13:22:17 [INFO]	There are 275/275 variables loaded into ResNet_vd.
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
2023-09-13 13:22:17 [INFO]	Convert bn to sync_bn
2023-09-13 13:22:17 [INFO]	Use the following config to build train_dataset
train_dataset:
  dataset_root: /data/net/dl_data/ProjectDatasets_bkx/VIMA_dataset/new_dataset
  mode: train
  num_classes: 7
  train_path: /data/net/dl_data/ProjectDatasets_bkx/VIMA_dataset/new_dataset/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 480
    - 480
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
2023-09-13 13:22:17 [INFO]	Use the following config to build val_dataset
val_dataset:
  dataset_root: /data/net/dl_data/ProjectDatasets_bkx/VIMA_dataset/new_dataset
  mode: val
  num_classes: 7
  transforms:
  - type: Normalize
  type: Dataset
  val_path: /data/net/dl_data/ProjectDatasets_bkx/VIMA_dataset/new_dataset/val.txt
2023-09-13 13:22:17 [INFO]	If the type is SGD and momentum in optimizer config, the type is changed to Momentum.
2023-09-13 13:22:17 [INFO]	Use the following config to build optimizer
optimizer:
  momentum: 0.9
  type: Momentum
  weight_decay: 4.0e-05
2023-09-13 13:22:17 [INFO]	Use the following config to build loss
loss:
  coef:
  - 1
  - 0.4
  - 0.2
  types:
  - type: CrossEntropyLoss
  - type: CrossEntropyLoss
  - type: SECrossEntropyLoss
[2023-09-13 13:22:17,468] [    INFO] distributed_strategy.py:160 - distributed strategy initialized
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_selected_gpus', current_value='0', default_value='')
=======================================================================
I0913 13:22:17.471369 24640 tcp_utils.cc:181] The server starts to listen on IP_ANY:35873
I0913 13:22:17.471719 24640 tcp_utils.cc:130] Successfully connected to 10.3.15.202:35873

```

**Comment by Birdylx** [comment]
@Yiveen 注意到你的log里出现了/usr/local/cuda/bin/nvcc: not found信息，请确认你的cuda环境没有问题

**Comment by langtian66123** [comment]
您好，请问下该问题解决了么？
