### ISSUE TITLE
ExternalError: CUBLAS error(7). Hint: 'CUBLAS_STATUS_INVALID_VALUE'

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/Paddle#57945]
### bug描述 Describe the Bug

运行 **paddle** 的时候，一直报这个错误。尝试过很多方案，始终无法避免或者解决这个问题。

```
Running verify PaddlePaddle program ... 
I1009 11:02:23.369635  8855 interpretercore.cc:237] New Executor is Running.
W1009 11:02:23.370568  8855 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.6, Runtime API Version: 11.2
W1009 11:02:23.378064  8855 gpu_resources.cc:149] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 249, in run_check
    _run_static_single(use_cuda, use_xpu)
  File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 147, in _run_static_single
    exe.run(
  File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1392, in run
    res = self._run_impl(
  File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1618, in _run_impl
    ret = new_exe.run(
  File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/fluid/executor.py", line 654, in run
    tensors = self._new_exe.run(
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 249, in run_check
      _run_static_single(use_cuda, use_xpu)
    File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 133, in _run_static_single
      input, out, weight = _simple_network()
    File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 37, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/nn/functional/common.py", line 1860, in linear
      helper.append_op(
    File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4013, in append_op
      op = Operator(
    File "/root/anaconda3/envs/paddle_py39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2781, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUBLAS error(7). 
      [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at ../paddle/phi/backends/gpu/gpu_context.cc:599)
      [operator < matmul_v2 > error]

```

**我一共尝试的方案有：**
1：本机安装 cuda-11.2和cudnn=8.2.1，conda环境中运行paddle，同样的报错；
2：conda中安装cuda和cudnn, 运行paddle，同样的报错；安装参考了这个：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/conda/linux-conda.html
`conda install paddlepaddle-gpu==2.5.1 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`
3：本机安装cuda-11.6 ,以及对应的paddle-gpu版本，仍然同样的报错；
4：尝试安装develop版本的paddle，同样的报错。
5：。。。

我把我能想到的方法都试了，一直都是同样的报错：**ExternalError: CUBLAS error(7).** 

请问这个到底是啥情况啊。
另外，我不管更换啥cudnn版本，不管是再conda环境内安装，还是再本机安装cudnn，paddle识别到的永远都是“cuDNN Version: 7.6.”   这个是啥情况。我没有安装7.6这个cudnn版本啊。

**Comment by Tian14267** [comment]
该问题已解决。本人解决方案如下：
首先，报错提示 `device: 0, cuDNN Version: 7.6.`，但是本人的机器安装的cudnn是8.2.1，这个可以确定。说明paddle找的cudnn库是错的。
其次，查看export的相关信息：`more ~/.bashrc`。观察该文件最后export的**LD_LIBRARY_PATH**是什么。本人最后export的是anaconda3的lib库。由于anaconda3中存在多种环境和多个库文件，会导致出错。
然后：修改`~/.bashrc`文件：`vim ~/.bashrc`，将最后的anaconda3的lib库注释掉，或者转移到前面，保证最后export的是cuda的库。比如我的，就是直接注释了。
![image](https://github.com/PaddlePaddle/Paddle/assets/27938135/bfc0aa25-fbdb-4984-925a-37f236ebb80f)
最后：重启环境：**source ~/.bashrc**   这一步很重要。然后paddle就正常了

**Comment by chiliuliu** [comment]
谢谢，找到问题了
