### ISSUE TITLE
Build error: "ncclBfloat16 was not declared in this scope"

### ISSUE THREAD

**Issue by MarioLulab** [PaddlePaddle/Paddle#58407]
### bug描述 Describe the Bug

I met a build error when I buid Paddle from source. My environment infomation is ubuntu18.04, cuda 10.2, cudnn7. And my `NCCL_VERSION_CODE` is 21104 which I found in `/usr/include/nccl.h`. 

## To reproduce my build error
```bash
git clone https://github.com/PaddlePaddle/Paddle.git

cd Paddle && make build && cd build

cmake .. -DPY_VERSION=3.7 -DWITH_GPU=ON -DWITH_UNITY_BUILD=ON

make -j24

# wait a minute, build error occurs...
``` 

Error occured in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/core/distributed/nccl_tools.cc#L62C1-L64C7
```bash
... ncclBfloat16 was not declared in this scope ...
```

### 其他补充信息 Additional Supplementary Information

I found `ncclBfloat16` was defined in `/usr/include/nccl.h` but wrapped up in macros `__CUDA_BF16_TYPES_EXIST__`, as shown below:

![image](https://github.com/PaddlePaddle/Paddle/assets/61354321/9faa8d02-e535-4c16-b747-860e8213287a)

I guess my cuda version(cuda10.2) does not support BF16, so `__CUDA_BF16_TYPES_EXIST__` is not defined. And I found the version of nccl that corresponds to NCCL_VERSION_CODE=21104 : [Nvidia Nccl](https://docs.nvidia.com/deeplearning/nccl/release-notes/rel_2-11-4.html#rel_2-11-4). It indicates that version NCCL2.11.4 is compatible with CUDA10.2 . So Might we need more Macro to be compatible with CUDA10.2 in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/core/distributed/nccl_tools.cc#L62C1-L64C7 ?

**Comment by yangjianfengo1** [comment]
what are your versions of NCCL and CUDA？NCCL 2.10.3 is now released with bfloat16 support，see https://github.com/NVIDIA/nccl/issues/476

**Comment by MarioLulab** [comment]
> what are your versions of NCCL and CUDA？NCCL 2.10.3 is now released with bfloat16 support，see [NVIDIA/nccl#476](https://github.com/NVIDIA/nccl/issues/476)

My cuda version is 10.2, and nccl version is  2.11.4

**Comment by yangjianfengo1** [comment]
The issue you provided is already in internal scheduling. Please look forward to the release of new Paddle features in the future. Thank you.

**Comment by EmmonsCurse** [comment]
@MarioLulab Hi, this compile error has been fixed by #58408 , you can try again using the latest commit.

**Comment by hitywt** [comment]
> yangjianfengo1

The problem has been fixed. Thank you for your feedback，fix PR：https://github.com/PaddlePaddle/Paddle/pull/58408

**Comment by hitywt** [comment]
> ### bug描述 Describe the Bug
> I met a build error when I buid Paddle from source. My environment infomation is ubuntu18.04, cuda 10.2, cudnn7. And my `NCCL_VERSION_CODE` is 21104 which I found in `/usr/include/nccl.h`.
> 
> ## To reproduce my build error
> ```shell
> git clone https://github.com/PaddlePaddle/Paddle.git
> 
> cd Paddle && make build && cd build
> 
> cmake .. -DPY_VERSION=3.7 -DWITH_GPU=ON -DWITH_UNITY_BUILD=ON
> 
> make -j24
> 
> # wait a minute, build error occurs...
> ```
> 
> Error occured in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/core/distributed/nccl_tools.cc#L62C1-L64C7
> 
> ```shell
> ... ncclBfloat16 was not declared in this scope ...
> ```
> 
> ### 其他补充信息 Additional Supplementary Information
> I found `ncclBfloat16` was defined in `/usr/include/nccl.h` but wrapped up in macros `__CUDA_BF16_TYPES_EXIST__`, as shown below:
> 
> ![image](https://user-images.githubusercontent.com/61354321/278245713-9faa8d02-e535-4c16-b747-860e8213287a.png)
> 
> I guess my cuda version(cuda10.2) does not support BF16, so `__CUDA_BF16_TYPES_EXIST__` is not defined. And I found the version of nccl that corresponds to NCCL_VERSION_CODE=21104 : [Nvidia Nccl](https://docs.nvidia.com/deeplearning/nccl/release-notes/rel_2-11-4.html#rel_2-11-4). It indicates that version NCCL2.11.4 is compatible with CUDA10.2 . So Might we need more Macro to be compatible with CUDA10.2 in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/core/distributed/nccl_tools.cc#L62C1-L64C7 ?

The problem has been fixed. Thank you for your feedback，fix PR：https://github.com/PaddlePaddle/Paddle/pull/58408
