### ISSUE TITLE
paddlepaddle2.3.2.post116在cuda11.6，cudnn8.4的环境下报ExternalError: CUDA error(719), unspecified launch failure的问题

### ISSUE THREAD

**Issue by markzhl** [PaddlePaddle/Paddle#58454]
### bug描述 Describe the Bug

paddlepaddle2.3.2.post116在rtx4090，cuda11.6，cudnn8.4的环境下报错：ExternalError: CUDA error(719), unspecified launch failure. [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:251) 在paddle版本，cuda版本和cudnn版本都匹配的情况下，都报这个错。
```python
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
...
    en_result = self.en_model([{"doc": img}])[0]
  File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 850, in __call__
    results = self.task_instance(inputs)
  File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\taskflow\task.py", line 516, in __call__
    outputs = self._run_model(inputs)
  File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 1066, in _run_model
    results = self._multi_stage_predict(_inputs)
  File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 1164, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 977, in _single_stage_predict
    self.predictor.run()
OSError: In user code:

    File "D:\ProgramData\eclipse2021\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\pydevd.py", line 3293, in <module>
      main()
    File "D:\ProgramData\eclipse2021\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\pydevd.py", line 3286, in main
      globals = debugger.run(setup['file'], None, None, is_module)
    File "D:\ProgramData\eclipse2021\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\pydevd.py", line 2360, in run
      return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
    File "D:\ProgramData\eclipse2021\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\pydevd.py", line 2367, in _exec
      pydev_imports.execfile(file, globals, locals)  # execute the script
    File "D:\ProgramData\eclipse2021\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
      exec(compile(contents + "\n", file, 'exec'), glob, loc)
    ...
      self.en_model = Taskflow("information_extraction", model="uie-x-base", schema=self.schema_en,
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 837, in __init__
      self.task_instance = task_class(
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 536, in __init__
      self._get_inference_model()
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\taskflow\task.py", line 337, in _get_inference_model
      self._convert_dygraph_to_static()
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\taskflow\task.py", line 383, in _convert_dygraph_to_static
      paddle.jit.save(static_model, self.inference_model_path)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\jit.py", line 860, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 527, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 785, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\transformers\ernie_layout\modeling.py", line 1168, in forward
      sequence_output, _ = self.ernie_layout(
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddlenlp\transformers\ernie_layout\modeling.py", line 741, in forward
      final_bbox = paddle.concat([bbox, visual_bbox], axis=1)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\tensor\manipulation.py", line 331, in concat
      return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\layers\tensor.py", line 392, in concat
      helper.append_op(
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\framework.py", line 3615, in append_op
      op = Operator(
    File "D:\ProgramData\Anaconda3\envs\uie3\lib\site-packages\paddle\fluid\framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDA error(719), unspecified launch failure. 
      [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:251)
      [operator < concat > error]```

### 其他补充信息 Additional Supplementary Information

_No response_

**Comment by wangguan1995** [comment]
这边4090驱动版本是怎样的呢？另外可以搞一个最小复现吗？

**Comment by wangguan1995** [comment]
看起来，final_bbox = paddle.concat([bbox, visual_bbox], axis=1)这一块报错了，这边可以试下吧bbox, visual_bbox的值保存下来，然后复现一下

**Comment by wangguan1995** [comment]
另外这边建议使用最新版本paddle ： 2.5.2.post116 版本

**Comment by wangguan1995** [comment]
另外这边建议，如果不妨碍使用，建议更新到最新版本paddle ： 2.5.2.post116 版本
看报错信息里包括fluid相关算子，也可能导致问题：
<img width="702" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/39621324/f0cef75d-b7b8-40b5-9434-3f1a86fc3925">

**Comment by markzhl** [comment]
收到，升级到paddle-2.4.2.post116，问题解决
