### ISSUE TITLE
验证安装失败，疑似paddle没有调用conda安装的cudnn版本

### ISSUE THREAD

**Issue by xvrong** [PaddlePaddle/Paddle#58914]
### 问题描述 Issue Description

我在纯净的conda环境下安装了paddle，这是我的paddle，cudnn，cuda，nvidia驱动和python版本

``` bash

>>> paddle.version.show()
commit: 3a1b1659a405a044ce806fbe027cc146f1193e6d
cuda: 11.2
cudnn: 8.2.1
xpu: False
xpu_xccl: False
cinn: False

nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+

python --version
Python 3.11.6

```

运行paddle安装检查结果

```bash

>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
I1110 17:34:13.194970  3418 interpretercore.cc:237] New Executor is Running.
W1110 17:34:13.218151  3418 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 11.3
`W1110 17:34:13.224603  3418 gpu_resources.cc:149] device: 0, cuDNN Version: 5.1.`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/utils/install_check.py", line 249, in run_check
    _run_static_single(use_cuda, use_xpu)
  File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/utils/install_check.py", line 147, in _run_static_single
    exe.run(
  File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/fluid/executor.py", line 1392, in run
    res = self._run_impl(
          ^^^^^^^^^^^^^^^
  File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/fluid/executor.py", line 1618, in _run_impl
    ret = new_exe.run(
          ^^^^^^^^^^^^
  File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/fluid/executor.py", line 654, in run
    tensors = self._new_exe.run(
              ^^^^^^^^^^^^^^^^^^
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/utils/install_check.py", line 249, in run_check
      _run_static_single(use_cuda, use_xpu)
    File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/utils/install_check.py", line 133, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/utils/install_check.py", line 37, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/nn/functional/common.py", line 1860, in linear
      helper.append_op(
    File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/fluid/framework.py", line 4013, in append_op
      op = Operator(
    File "/home/qurongsheng_2023/anaconda3/envs/pa/lib/python3.11/site-packages/paddle/fluid/framework.py", line 2781, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUBLAS error(7). 
      [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at ../paddle/phi/backends/gpu/gpu_context.cc:599)
      [operator < matmul_v2 > error]

```

其中`W1110 17:34:13.224603  3418 gpu_resources.cc:149] device: 0, cuDNN Version: 5.1.`报告的cuDNN版本与paddle的显示并不一致，怀疑是此处出了问题。

### 版本&环境信息 Version & Environment Information

这是summary_env的输出。

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 18.04
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: N/A
CMake version: version 3.18.2
Libc version: glibc 2.27
Python version: 3.11.6

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: 470.82.01
Nvidia driver List: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti
GPU 4: NVIDIA GeForce RTX 2080 Ti
GPU 5: NVIDIA GeForce RTX 2080 Ti
GPU 6: NVIDIA GeForce RTX 2080 Ti
GPU 7: NVIDIA GeForce RTX 2080 Ti
GPU 8: NVIDIA GeForce RTX 2080 Ti
GPU 9: NVIDIA GeForce RTX 2080 Ti

****************************************

**Comment by xvrong** [comment]
请问有任何的帮助解决这个问题么，这是什么导致的呢?

**Comment by risemeup1** [comment]
export LD_LIBRARY_PATH=/usr/lib64/
ldconfig

试一下？

**Comment by xvrong** [comment]
已经解决。
运行`conda env config vars set LD_LIBRARY_PATH=\<conda-path\>/envs/<conda-enviroment-name\>/include:\<conda-path\>/envs/<enviroment-name\>/lib`
之后完全退出conda环境，再重新进入环境，cuDNN版本就变成了conda安装的版本。

**Comment by kingqiuol** [comment]
> Author

在coda中安装的cuda,你的方法有用

**Comment by kingqiuol** [comment]
> 已经解决。 运行`conda env config vars set LD_LIBRARY_PATH=\<conda-path\>/envs/<conda-enviroment-name\>/include:\<conda-path\>/envs/<enviroment-name\>/lib` 之后完全退出conda环境，再重新进入环境，cuDNN版本就变成了conda安装的版本。

我是在conda中安装的cuda，你这个方法有用
