### ISSUE TITLE
Cuda Error: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by zuowang** [PaddlePaddle/Paddle#598]
我在docker中运行paddle，出现如下错误：
F1124 21:28:06.288099   122 hl_cuda_device.cc:545] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version

运行命令是：
/usr/local/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.lstm.py --save_dir=./output --trainer_count=4 --log_period=100 --num_passes=15 --use_gpu=true --show_parameter_stats_period=100 --test_all_data_in_one_period=1 

docker version是
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64

nvidia driver版本：
$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.99  Mon Jul  4 23:52:14 PDT 2016
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 

cuda版本：
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

**Comment by zuowang** [comment]
请问必须用nvidia-docker运行吗?

**Comment by gangliao** [comment]
@zuowang 

可以参考文档里面的Docker教程： http://www.paddlepaddle.org/doc_cn/build_and_install/install/docker_install.html

Cuda Error: CUDA driver version is insufficient for CUDA runtime version
可以参考文档里面的FAQ, 看看是否解决问题:
https://github.com/PaddlePaddle/Paddle/blob/develop/doc_cn/build_and_install/install/ubuntu_install.rst#cuda-driver找不到

**Comment by backyes** [comment]
@gangliao @hedaoyuan 

```
F1124 21:28:06.288099 122 hl_cuda_device.cc:545] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version
```
这个问题FAQ 解决方案：
```
export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
```
比较粗鲁，没有解释原因。 

如果可以，能给出原因解释最好。

**Comment by hedaoyuan** [comment]
> CUDA driver version is insufficient for CUDA runtime version

这种属于环境的问题，FAQ里面只是给出了一种可能能够fix的方法（估计是遇到比较多的）。你说的解释原因指的是啥，这个fix的方法没啥好再解释的吧。

**Comment by backyes** [comment]
@hedaoyuan
 
是cuda版本不一致导致的么？如果是， 为什么加一个LD_LIBRARY_PATH能解决版本问题？

**Comment by hedaoyuan** [comment]
这个应该是LD_LIBRARY_PATH如果没有包含`/usr/lib64`会导致找不到driver library，所以需要LD_LIBRARY_PATH加上这个路径。

**Comment by zuowang** [comment]
http://www.paddlepaddle.org/doc_cn/build_and_install/install/docker_install.html
这里面应该是吧？
```
$ export CUDA_SO="$(\ls /usr/lib64/libcuda* | xargs -I{} echo '-v {}:{}') $(\ls /usr/lib64/libnvidia* | xargs -I{} echo '-v {}:{}')"
$ export DEVICES=$(\ls /dev/nvidia* | xargs -I{} echo '--device {}:{}')
$ docker run $CUDA_SO $DEVICES -it paddledev/paddlepaddle:latest-gpu
```

我的问题解决了。多谢各位
