### ISSUE TITLE
fused_conv2d_add_act 不支持

### ISSUE THREAD

**Issue by dz902** [PaddlePaddle/Paddle#60540]
### bug描述 Describe the Bug

```
    ExternalError: CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
      [Hint: 'CUDNN_STATUS_NOT_SUPPORTED'.  The functionality requested is not presently supported by cuDNN.  ] (at /paddle/paddle/phi/kernels/fusion/gpu/fused_conv2d_add_act_kernel.cu:610)
      [operator < fused_conv2d_add_act > error]
```

测试过 CUDA 12 和 CUDA 11.8 都不行。使用 ch_PP-OCRv4_server_det 和 ch_PP-OCRv4_server_rec。

```
paddleclas               2.5.1
paddleocr                2.7.0.3
paddlepaddle-gpu         2.6.0
```

使用 CPU 没问题。

**Comment by engineer1109** [comment]
cudnn似乎有不支持的 融合操作

**Comment by dz902** [comment]
已解决，降级到 libcudnn 8.5

**Comment by engineer1109** [comment]
高版本cudnn的问题 还是要反馈下。不然，以后还是躺尸

**Comment by YanhuiDua** [comment]
> 已解决，降级到 libcudnn 8.5

请问下你最终使用的环境是cuda的哪个版本+cudnn8.5

**Comment by yuanlehome** [comment]
之前报错使用的cudnn版本是多少呢？

**Comment by WangShengFeng1** [comment]
怎么解决的？
