### ISSUE TITLE
paddle_inference推理库(3.0.0-beta1 版本)GPU无法推理

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/Paddle#66124]
### bug描述 Describe the Bug

推理库版本CUDA12.3/cuDNN9.0/TensorRT8.6
在推理时报错

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;%PATH%`
  - Mac: set  DYLD_LIBRARY_PATH by `export DYLD_LIBRARY_PATH=...` [Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled.] (at C:\home\workspace\Paddle\paddle\phi\backends\dynload\dynamic_loader.cc:340)

--------------------------------------
cudnn64_8.dll是cuDNN8的库，该版本使用的应该是cuDNN9，调用的应该是cudnn64_9.dll

请问怎么样才能正常调用cudnn64_9.dl

**Comment by lijialin03** [comment]
感谢您的反馈，能否提供运行时的cuda/gcc等环境以及操作步骤，以便复现这个问题，谢谢～

**Comment by 534114658** [comment]
win10  CUDA12.3/cuDNN9.0/TensorRT8.6   全部按照说明安装的
任意目标检测和分割模型都可以复现

使用cudnn8的库就可以正常推理
请问怎么样才能正常调用cudnn64_9.dl

**Comment by vivienfanghuagood** [comment]
paddle默认使用系统中的cudnn，如果需要使用cudnn 9，需要修改系统配置，使其默认加载。
