### ISSUE TITLE
Check failed: stat == CUBLAS_STATUS_SUCCESS (13 vs. 0) 

### ISSUE THREAD

**Issue by demonstreet** [PaddlePaddle/Paddle#6643]
I have a script that can run normally on cpu-mode(--use_gpu=False), but the following error occurs when I use gpu-mode(--use_gpu=True)：
p.s:  paddle version is 0.11.0-gpu.

```
F1214 10:55:30.027999    10 hl_cuda_cublas.cc:386] Check failed: stat == CUBLAS_STATUS_SUCCESS (13 vs. 0) [cublas status]: execution failed
*** Check failure stack trace: ***
    @     0x7fd13040127d  google::LogMessage::Fail()
    @     0x7fd130404d2c  google::LogMessage::SendToLog()
    @     0x7fd130400da3  google::LogMessage::Flush()
    @     0x7fd13040623e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd1303b29ff  hl_matrix_mul_vector()
    @     0x7fd1303b2f61  hl_matrix_mul()
    @     0x7fd130221ab7  paddle::GpuMatrix::mul()
    @     0x7fd130222111  paddle::GpuMatrix::mul()
    @     0x7fd13008a8cf  paddle::FullyConnectedLayer::forward()
    @     0x7fd130106f6d  paddle::NeuralNetwork::forward()
    @     0x7fd12ff7e68d  _wrap_GradientMachine_forward
    @           0x4cb755  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4ddd6a  (unknown)
    @           0x4c4bdc  PyEval_EvalFrameEx
    @           0x4ddd6a  (unknown)
    @           0x4c4bdc  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca088  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca088  PyEval_EvalFrameEx
    @           0x4ddd6a  (unknown)
    @           0x4c4bdc  PyEval_EvalFrameEx
    @           0x4ddd6a  (unknown)
    @           0x4c4bdc  PyEval_EvalFrameEx
    @           0x4ddd6a  (unknown)
    @           0x50f41f  (unknown)
    @           0x4c4bdc  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
```

Does anybody know how to solve this problem? Thanks!

**Comment by peterzhang2029** [comment]
Please add the training config script.

**Comment by peterzhang2029** [comment]
Please add the training config script.

**Comment by demonstreet** [comment]
training config is as follows:    

    # network config
    x = paddle.layer.data(name='x', type=paddle.data_type.dense_vector(ROOM_NUM))
    
    hiden1 = paddle.layer.fc(input=x, size=512, act=paddle.activation.Relu())
    hiden2 = paddle.layer.fc(input=hiden1, size=256, act=paddle.activation.Relu())
    hiden3 = paddle.layer.fc(input=hiden2, size=128, act=paddle.activation.Relu())   
    
    global y_predict
    output = paddle.layer.fc(input=hiden3, size=ROOM_NUM)
    

    
    y = paddle.layer.data(name='y', type=paddle.data_type.dense_vector(1))
    x2 = paddle.layer.data(name='x2', type=paddle.data_type.dense_vector(ROOM_NUM))
    y_predict = paddle.layer.dot_prod(x2, output)
    
    cost = paddle.layer.regression_cost(input=y_predict, label=y)

**Comment by peterzhang2029** [comment]
And please provide the cuda and cudnn version.

**Comment by demonstreet** [comment]
@peterzhang2029 
thank you for your advice that trying to remove dot_prod layer. 
But the problem reminds. 
My cuda and cudnn versions are as follows:
   Driver Version: 375.39   cuda-7.5  cudnn_v5

Does that provide new clues? Thank you very much again!

**Comment by peterzhang2029** [comment]
This error has been fixed by use `nvidia-docker `
