### ISSUE TITLE
operator < conv2d_fusion > error

### ISSUE THREAD

**Issue by renoyuan** [PaddlePaddle/Paddle#67938]
### bug描述 Describe the Bug

paddle ocr运行错误
gpu NVIDIA L40S 
cuda 12.1
cudnn 8.9.7
paddle-bfloat                     0.1.7
paddle2onnx                       1.2.3
paddleocr                         2.7.3
paddlepaddle-gpu                  2.4.2.post117
x2paddle                          1.4.1
------------------------------
 outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/conv.py", line 678, in forward
      use_cudnn=self._use_cudnn)
    File "/usr/local/lib/python3.7/dist-packages/paddle/nn/functional/conv.py", line 169, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED. 
      [Hint: Please search for the error code(9) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:519)
      [operator < conv2d_fusion > error]
----------------------------------------------
报错显示cudnn 版本不支持错误 不过相同环境在其他显卡上运行过，paddle 对这个显卡请问是兼容的吗？

**Comment by zxcd** [comment]
尝试升级下paddle版本是否能够解决问题，paddlepaddle-gpu>=2.5.0

**Comment by renoyuan** [comment]
Error: Can not import paddle core while this file exists: /home/tlrobot/anaconda3/envs/tjb_nee_env/lib/python3.10/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/home/reno/gsly_tjb/visual-instruction/server/ocr_server.py", line 10, in <module>
    from PaddleOCR.tools.infer.predict_system import  TextSystem
  File "/home/reno/gsly_tjb/visual-instruction/PaddleOCR/tools/infer/predict_system.py", line 31, in <module>
    import tools.infer.utility as utility
  File "/home/reno/gsly_tjb/visual-instruction/PaddleOCR/tools/infer/utility.py", line 20, in <module>
    import paddle
  File "/home/tlrobot/anaconda3/envs/tjb_nee_env/lib/python3.10/site-packages/paddle/__init__.py", line 28, in <module>
    from .base import core  # noqa: F401
  File "/home/tlrobot/anaconda3/envs/tjb_nee_env/lib/python3.10/site-packages/paddle/base/__init__.py", line 36, in <module>
    from . import core
  File "/home/tlrobot/anaconda3/envs/tjb_nee_env/lib/python3.10/site-packages/paddle/base/core.py", line 380, in <module>
    raise e
  File "/home/tlrobot/anaconda3/envs/tjb_nee_env/lib/python3.10/site-packages/paddle/base/core.py", line 268, in <module>
    from . import libpaddle
ImportError: /home/tlrobot/anaconda3/envs/tjb_nee_env/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/tlrobot/anaconda3/envs/tjb_nee_env/lib/python3.10/site-packages/paddle/base/libpaddle.so)
--------------------------------------------------------
更新2.5 以上版本 之后会出现这个错误, 

1 需要升级g++ libstdc++6 等依赖吗？
我尝试升级 apt install --only-upgrade g++ libstdc++6  不过没有找到可以升级版本。我是用ubuntu18.0.4 作为验证环境操作。

2 我在 bin/../lib/libstdc++.so.6 | grep GLIBCXX 中找到 最高版本为 GLIBCXX_3.4.29 没有 GLIBCXX_3.4.30 目前python 版本为Python 3.10.14。

**Comment by zxcd** [comment]
这个问题与 https://github.com/PaddlePaddle/Paddle/issues/65013 类似，建议升级gcc版本或者使用官方镜像

**Comment by renoyuan** [comment]
感谢大佬，问题已解决 我的解决方法是添加 ~/conda/env/lib 到 LD_LIBRARY_PATH 环境变量中 ，Python环境中的lib目录有一个 符合版本要求的libstdc++.so.6，不过加载模型的时候没有用到。
