### ISSUE TITLE
天数BI-V150按照官方文档安装飞桨框架后run_check测试卡住

### ISSUE THREAD

**Issue by 404bro** [PaddlePaddle/Paddle#74961]
## 复现方法
严格按照[该文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/hardware_support/iluvatar_gpu/install_cn.html)的内容，通过飞桨官网发布的 wheel 包安装飞桨框架 iluvatar_gpu 版。

## 问题描述
1. 在 run_check 多卡测试时卡住（见第一条日志，最后一行即卡住的位置）。
2. 若导入了paddle包，在python退出时会发生段错误（见第二条日志）。

## 日志信息
```
root@42bc99a4bca4:/workspace# python3 -c "import paddle; print(paddle.device.get_all_custom_device_type())"
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
I0828 21:49:55.433998 19357 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 21:49:55.434020 19357 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:49:55.715545 19357 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 21:49:55.715565 19357 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 21:49:55.718708 19357 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 21:49:55.718827 19357 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:49:55.718848 19357 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
['iluvatar_gpu']
Segmentation fault (core dumped)
root@42bc99a4bca4:/workspace#
root@42bc99a4bca4:/workspace#
root@42bc99a4bca4:/workspace# export PADDLE_XCCL_BACKEND=iluvatar_gpu
root@42bc99a4bca4:/workspace# python3 -c "import paddle; paddle.utils.run_check()"
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
I0828 21:50:03.384534 20152 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 21:50:03.384557 20152 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:03.467613 20152 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 21:50:03.467633 20152 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 21:50:03.470606 20152 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 21:50:03.470726 20152 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:03.470749 20152 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
Running verify PaddlePaddle program ...
I0828 21:50:03.731207 20152 pir_interpreter.cc:1524] New Executor is Running ...
I0828 21:50:03.745586 20152 pir_interpreter.cc:1547] pir interpreter is running by multi-thread mode ...
PaddlePaddle works well on 1 iluvatar_gpu.
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
I0828 21:50:04.690412 20313 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 21:50:04.690438 20313 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.690600 20310 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 21:50:04.690622 20310 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.696025 20311 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 21:50:04.696044 20311 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.702071 20312 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 21:50:04.702090 20312 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.704253 20309 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 21:50:04.704278 20309 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.710304 20314 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 21:50:04.710323 20314 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.712798 20316 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 21:50:04.712817 20316 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.716763 20315 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 21:50:04.716779 20315 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.773319 20310 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 21:50:04.773319 20313 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 21:50:04.773330 20311 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 21:50:04.773340 20310 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 21:50:04.773344 20313 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 21:50:04.773348 20311 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 21:50:04.776489 20310 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 21:50:04.776504 20311 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 21:50:04.776515 20313 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 21:50:04.776618 20310 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.776630 20311 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.776636 20310 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
I0828 21:50:04.776647 20311 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
I0828 21:50:04.776648 20313 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.776665 20313 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
I0828 21:50:04.776690 20312 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 21:50:04.776710 20312 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 21:50:04.779330 20309 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 21:50:04.779350 20309 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 21:50:04.779853 20312 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 21:50:04.779979 20312 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.779997 20312 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
I0828 21:50:04.782476 20309 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 21:50:04.782601 20309 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.782619 20309 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
I0828 21:50:04.784888 20314 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 21:50:04.784909 20314 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 21:50:04.787698 20316 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 21:50:04.787717 20316 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 21:50:04.788024 20314 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 21:50:04.788154 20314 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.788173 20314 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
I0828 21:50:04.790855 20316 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 21:50:04.791000 20316 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.791020 20316 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
I0828 21:50:04.791626 20315 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 21:50:04.791646 20315 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 21:50:04.794696 20315 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 21:50:04.794813 20315 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 21:50:04.794831 20315 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
======================= Modified FLAGS detected =======================
======================= Modified FLAGS detected =======================
======================= Modified FLAGS detected =======================
======================= Modified FLAGS detected =======================
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_enable_pir_in_executor', current_value=True, default_value=False)
FLAGS(name='FLAGS_enable_pir_in_executor', current_value=True, default_value=False)
FLAGS(name='FLAGS_enable_pir_in_executor', current_value=True, default_value=False)
FLAGS(name='FLAGS_enable_pir_in_executor', current_value=True, default_value=False)
=======================================================================
=======================================================================
FLAGS(name='FLAGS_enable_pir_in_executor', current_value=True, default_value=False)
=======================================================================
=======================================================================
=======================================================================
I0828 21:50:05.044416 20311 tcp_utils.cc:111] Retry to connect to 127.0.0.1:38397 while the server is not yet listening.
I0828 21:50:05.044416 20312 tcp_utils.cc:111] Retry to connect to 127.0.0.1:38397 while the server is not yet listening.
I0828 21:50:05.044416 20313 tcp_utils.cc:111] Retry to connect to 127.0.0.1:38397 while the server is not yet listening.
I0828 21:50:05.044478 20309 tcp_utils.cc:185] The server starts to listen on IP_ANY:38397; setting synclog to 2048
I0828 21:50:05.044481 20310 tcp_utils.cc:111] Retry to connect to 127.0.0.1:38397 while the server is not yet listening.
I0828 21:50:05.044610 20309 tcp_utils.cc:134] Successfully connected to 127.0.0.1:38397
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_enable_pir_in_executor', current_value=True, default_value=False)
=======================================================================
I0828 21:50:05.047633 20314 tcp_utils.cc:134] Successfully connected to 127.0.0.1:38397
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_enable_pir_in_executor', current_value=True, default_value=False)
=======================================================================
I0828 21:50:05.051498 20316 tcp_utils.cc:134] Successfully connected to 127.0.0.1:38397
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_enable_pir_in_executor', current_value=True, default_value=False)
=======================================================================
I0828 21:50:05.052100 20315 tcp_utils.cc:134] Successfully connected to 127.0.0.1:38397
I0828 21:50:08.044600 20312 tcp_utils.cc:134] Successfully connected to 127.0.0.1:38397
I0828 21:50:08.044607 20311 tcp_utils.cc:134] Successfully connected to 127.0.0.1:38397
I0828 21:50:08.044621 20313 tcp_utils.cc:134] Successfully connected to 127.0.0.1:38397
I0828 21:50:08.044643 20310 tcp_utils.cc:134] Successfully connected to 127.0.0.1:38397
```
```
root@42bc99a4bca4:/workspace# python3
Python 3.10.18 (main, Jun 24 2025, 14:11:18) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
I0828 22:13:56.114938 31842 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 22:13:56.114959 31842 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 22:13:56.200495 31842 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 22:13:56.200513 31842 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 22:13:56.203491 31842 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 22:13:56.203604 31842 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 22:13:56.203621 31842 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
>>> exit()
Segmentation fault (core dumped)
```

### 版本&环境信息 Version & Environment Information

```
root@42bc99a4bca4:/workspace# python3 summary_env.py
/usr/local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
I0828 22:11:47.934979 31222 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/site-packages/paddle_custom_device
I0828 22:11:47.935006 31222 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 22:11:48.021052 31222 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so
I0828 22:11:48.021075 31222 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-iluvatar-gpu.so]: no custom engine Plugin symbol in this lib.
I0828 22:11:48.024302 31222 custom_kernel.cc:68] Succeed in loading 314 custom kernel(s) from loaded lib(s), will be used like native ones.
I0828 22:11:48.024423 31222 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/site-packages/paddle_custom_device]
I0828 22:11:48.024446 31222 init.cc:244] CustomDevice: iluvatar_gpu, visible devices count: 8
****************************************
Paddle version: 3.1.0-alpha0
Paddle With CUDA: False

OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 18.1.8 (4.3.0.rc.9 5a0fa423713e78abbc6f3fb221fc702b511b56c5)
CMake version: version 3.25.2-corex.4.3.0.rc.9
Libc version: glibc 2.31
Python version: 3.10.18

CUDA version: 10.2.89
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************
Segmentation fault (core dumped)
```
```
root@0569f80fcf41:~# ixsmi
Timestamp    Thu Aug 28 22:28:24 2025
+-----------------------------------------------------------------------------+
|  IX-ML: 4.3.0       Driver Version: 4.3.0       CUDA Version: 10.2          |
|-------------------------------+----------------------+----------------------|
| GPU  Name                     | Bus-Id               | Clock-SM  Clock-Mem  |
| Fan  Temp  Perf  Pwr:Usage/Cap|      Memory-Usage    | GPU-Util  Compute M. |
|===============================+======================+======================|
| 0    Iluvatar BI-V150         | 00000000:10:00.0     | 1500MHz   1600MHz    |
| N/A  40C   P0    N/A / N/A    | 64MiB / 32768MiB     | 0%        Default    |
+-------------------------------+----------------------+----------------------+
| 1    Iluvatar BI-V150         | 00000000:13:00.0     | 1500MHz   1600MHz    |
| N/A  39C   P0    101W / 350W  | 64MiB / 32768MiB     | 0%        Default    |
+-------------------------------+----------------------+----------------------+
| 2    Iluvatar BI-V150         | 00000000:49:00.0     | 1500MHz   1600MHz    |
| N/A  41C   P0    N/A / N/A    | 64MiB / 32768MiB     | 0%        Default    |
+-------------------------------+----------------------+----------------------+
| 3    Iluvatar BI-V150         | 00000000:4C:00.0     | 1500MHz   1600MHz    |
| N/A  44C   P0    104W / 350W  | 64MiB / 32768MiB     | 0%        Default    |
+-------------------------------+----------------------+----------------------+
| 4    Iluvatar BI-V150         | 00000000:88:00.0     | 1500MHz   1600MHz    |
| N/A  39C   P0    N/A / N/A    | 64MiB / 32768MiB     | 0%        Default    |
+-------------------------------+----------------------+----------------------+
| 5    Iluvatar BI-V150         | 00000000:8B:00.0     | 1500MHz   1600MHz    |
| N/A  40C   P0    104W / 350W  | 64MiB / 32768MiB     | 0%        Default    |
+-------------------------------+----------------------+----------------------+
| 6    Iluvatar BI-V150         | 00000000:C4:00.0     | 1500MHz   1600MHz    |
| N/A  40C   P0    N/A / N/A    | 64MiB / 32768MiB     | 0%        Default    |
+-------------------------------+----------------------+----------------------+
| 7    Iluvatar BI-V150         | 00000000:C7:00.0     | 1500MHz   1600MHz    |
| N/A  40C   P0    104W / 350W  | 64MiB / 32768MiB     | 0%        Default    |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU        PID      Process name                                Usage(MiB) |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by 404bro** [comment]
> 你好，关于问题一，可以试一下安装develop分支的paddle cpu包 + iluvatar_gpu包试一下： python -m pip install --pre paddlepaddle -i https://www.paddlepaddle.org.cn/packages/nightly/cpu/ python -m pip install --pre paddle-iluvatar-gpu -i https://www.paddlepaddle.org.cn/packages/nightly/ixuca/ 在执行健康性检查前可以先重启下gpu试下：ixsmi -r 关于问题二，这是一个已知问题，暂时可以通过环境变量绕过一下： export LD_PRELOAD="${LD_LIBRARY_PATH}/libcuda.so.1"

您好，我按照这个方法进行安装，问题一仍然存在，日志没有变化。
问题二已解决。

**Comment by 404bro** [comment]
> 好的，请问下您的镜像和kmd都是按照上述文档中的版本进行安装的吧。 我刚刚在我本地试了下，用develop的应该是可行的。 <img alt="Image" width="1115" height="288" src="https://private-user-images.githubusercontent.com/143938697/483499569-0411d0c0-a8e0-4b85-8615-d6eac4d2f17b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY0NTYyNzMsIm5iZiI6MTc1NjQ1NTk3MywicGF0aCI6Ii8xNDM5Mzg2OTcvNDgzNDk5NTY5LTA0MTFkMGMwLWE4ZTAtNGI4NS04NjE1LWQ2ZWFjNGQyZjE3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyOVQwODI2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDRjYTllOTcxYmQxYjQxOWU3ZWUzNGYzYzdmOWQxOGEzMWM2ODljMGJjZDQxMWVkYjlhZmI4YmExNGQ5YTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EdJUVVitoveAaq_ySLUmw_vYAQa0I551A2LVtwkIXNo">

是的，严格按照文档给的链接来安装的。在宿主机和容器中使用 `ixsmi` 查询，版本都是4.3.0。
```
IX-ML: 4.3.0       Driver Version: 4.3.0       CUDA Version: 10.2
```

**Comment by 404bro** [comment]
补充一些线索：
使用`NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALL`环境变量运行程序之后，建链成功之后的日志输出如下所示：
```
8ee36855bc0c:593132:593132 [6] NCCL INFO comm 0x564037f2c9f0 groupId f1895979173b3d66 rank 6 nranks 8 cudaDev 6 busId c4000 - Init COMPLETE
8ee36855bc0c:593131:593131 [5] NCCL INFO init.cc:450 Cuda Host Alloc Size 44040192 pointer 0x7eb261600000
8ee36855bc0c:593131:593131 [5] NCCL INFO init.cc:456 Cuda Host Alloc Size 128 pointer 0x7eb270541000
8ee36855bc0c:593131:593131 [5] NCCL INFO comm 0x55e4fcdd73c0 groupId f1895979173b3d66 rank 5 nranks 8 cudaDev 5 busId 8b000 - Init COMPLETE
8ee36855bc0c:593127:593127 [1] NCCL INFO init.cc:450 Cuda Host Alloc Size 44040192 pointer 0x7e98c1600000
8ee36855bc0c:593127:593127 [1] NCCL INFO init.cc:456 Cuda Host Alloc Size 128 pointer 0x7e98d075b000
8ee36855bc0c:593127:593127 [1] NCCL INFO comm 0x55dd936ead00 groupId f1895979173b3d66 rank 1 nranks 8 cudaDev 1 busId 13000 - Init COMPLETE
8ee36855bc0c:593132:593132 [6] NCCL INFO Broadcast: opCount 0 sendbuff 0x7ed448000000 recvbuff 0x7ed448000000 count 400 datatype 0 op 0 root 0 comm 0x564037f2c9f0 [nranks=8] stream 0x564038016c60
8ee36855bc0c:593132:593132 [6] NCCL INFO misc/utils.cc:248 memory stack hunk malloc(65536)
8ee36855bc0c:593127:593127 [1] NCCL INFO Broadcast: opCount 0 sendbuff 0x7ea908000000 recvbuff 0x7ea908000000 count 400 datatype 0 op 0 root 0 comm 0x55dd936ead00 [nranks=8] stream 0x55dd936d6dc0
8ee36855bc0c:593127:593127 [1] NCCL INFO misc/utils.cc:248 memory stack hunk malloc(65536)
8ee36855bc0c:593133:593133 [7] NCCL INFO init.cc:450 Cuda Host Alloc Size 44040192 pointer 0x7e275d600000
8ee36855bc0c:593133:593133 [7] NCCL INFO init.cc:456 Cuda Host Alloc Size 128 pointer 0x7e276c4f8000
8ee36855bc0c:593133:593133 [7] NCCL INFO comm 0x55b8f1263690 groupId f1895979173b3d66 rank 7 nranks 8 cudaDev 7 busId c7000 - Init COMPLETE
8ee36855bc0c:593130:593130 [4] NCCL INFO init.cc:450 Cuda Host Alloc Size 44040192 pointer 0x7eaa75600000
8ee36855bc0c:593130:593130 [4] NCCL INFO init.cc:456 Cuda Host Alloc Size 128 pointer 0x7eaa7dd8a000
8ee36855bc0c:593130:593130 [4] NCCL INFO comm 0x55e030007c00 groupId f1895979173b3d66 rank 4 nranks 8 cudaDev 4 busId 88000 - Init COMPLETE
8ee36855bc0c:593133:593133 [7] NCCL INFO Broadcast: opCount 0 sendbuff 0x7e9788000000 recvbuff 0x7e9788000000 count 400 datatype 0 op 0 root 0 comm 0x55b8f1263690 [nranks=8] stream 0x55b8f12c27c0
8ee36855bc0c:593133:593133 [7] NCCL INFO misc/utils.cc:248 memory stack hunk malloc(65536)
8ee36855bc0c:593131:593131 [5] NCCL INFO Broadcast: opCount 0 sendbuff 0x7f02c8000000 recvbuff 0x7f02c8000000 count 400 datatype 0 op 0 root 0 comm 0x55e4fcdd73c0 [nranks=8] stream 0x55e4fcdc3040
8ee36855bc0c:593131:593131 [5] NCCL INFO misc/utils.cc:248 memory stack hunk malloc(65536)
8ee36855bc0c:593130:593130 [4] NCCL INFO Broadcast: opCount 0 sendbuff 0x7eeac8000000 recvbuff 0x7eeac8000000 count 400 datatype 0 op 0 root 0 comm 0x55e030007c00 [nranks=8] stream 0x55e0300eee80
8ee36855bc0c:593130:593130 [4] NCCL INFO misc/utils.cc:248 memory stack hunk malloc(65536)
8ee36855bc0c:593129:593129 [3] NCCL INFO init.cc:450 Cuda Host Alloc Size 44040192 pointer 0x7e6989600000
8ee36855bc0c:593129:593129 [3] NCCL INFO init.cc:456 Cuda Host Alloc Size 128 pointer 0x7e6991ead000
8ee36855bc0c:593128:593128 [2] NCCL INFO init.cc:450 Cuda Host Alloc Size 44040192 pointer 0x7e2c94600000
8ee36855bc0c:593128:593128 [2] NCCL INFO init.cc:456 Cuda Host Alloc Size 128 pointer 0x7e2c9d5aa000
8ee36855bc0c:593129:593129 [3] NCCL INFO comm 0x55be82339260 groupId f1895979173b3d66 rank 3 nranks 8 cudaDev 3 busId 4c000 - Init COMPLETE
8ee36855bc0c:593128:593128 [2] NCCL INFO comm 0x55e37cf852b0 groupId f1895979173b3d66 rank 2 nranks 8 cudaDev 2 busId 49000 - Init COMPLETE
8ee36855bc0c:593129:593129 [3] NCCL INFO Broadcast: opCount 0 sendbuff 0x7e99c8000000 recvbuff 0x7e99c8000000 count 400 datatype 0 op 0 root 0 comm 0x55be82339260 [nranks=8] stream 0x55be8270e9f0
8ee36855bc0c:593129:593129 [3] NCCL INFO misc/utils.cc:248 memory stack hunk malloc(65536)
8ee36855bc0c:593128:593128 [2] NCCL INFO Broadcast: opCount 0 sendbuff 0x7e4cc8000000 recvbuff 0x7e4cc8000000 count 400 datatype 0 op 0 root 0 comm 0x55e37cf852b0 [nranks=8] stream 0x55e37cfc4a00
8ee36855bc0c:593128:593128 [2] NCCL INFO misc/utils.cc:248 memory stack hunk malloc(65536)
8ee36855bc0c:593126:593126 [0] NCCL INFO init.cc:450 Cuda Host Alloc Size 44040192 pointer 0x7eb839600000
8ee36855bc0c:593126:593126 [0] NCCL INFO init.cc:456 Cuda Host Alloc Size 128 pointer 0x7eb84804f000
8ee36855bc0c:593126:593126 [0] NCCL INFO comm 0x559eaebfc2d0 groupId f1895979173b3d66 rank 0 nranks 8 cudaDev 0 busId 10000 - Init COMPLETE
8ee36855bc0c:593126:593126 [0] NCCL INFO Broadcast: opCount 0 sendbuff 0x7eb888000000 recvbuff 0x7eb888000000 count 400 datatype 0 op 0 root 0 comm 0x559eaebfc2d0 [nranks=8] stream 0x559eaece6ed0
8ee36855bc0c:593126:593126 [0] NCCL INFO misc/utils.cc:248 memory stack hunk malloc(65536)
8ee36855bc0c:593126:593126 [0] NCCL INFO Broadcast: opCount 1 sendbuff 0x7eb888001000 recvbuff 0x7eb888001000 count 40 datatype 0 op 0 root 0 comm 0x559eaebfc2d0 [nranks=8] stream 0x559eaece6ed0
8ee36855bc0c:593126:593126 [0] NCCL INFO Broadcast: opCount 2 sendbuff 0x7eb888002000 recvbuff 0x7eb888002000 count 40 datatype 0 op 0 root 0 comm 0x559eaebfc2d0 [nranks=8] stream 0x559eaece6ed0
8ee36855bc0c:593126:593126 [0] NCCL INFO Broadcast: opCount 3 sendbuff 0x7eb888003000 recvbuff 0x7eb888003000 count 4 datatype 0 op 0 root 0 comm 0x559eaebfc2d0 [nranks=8] stream 0x559eaece6ed0
8ee36855bc0c:593126:593126 [0] NCCL INFO AllReduce: opCount 4 sendbuff 0x7eb88b537000 recvbuff 0x7eb88b537000 count 121 datatype 7 op 0 root 0 comm 0x559eaebfc2d0 [nranks=8] stream 0x559eaece6ed0
```
发送 `SIGINT` 信号（`Ctrl+C`）之后，各个进程所在的调用栈如下所示：
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1756456854 (unix time) try "date -d @1756456854" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x90cec) received by PID 593008 (TID 0x7fd15d4c4740) from PID 593132 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::distributed::ProcessGroupWithStream::Broadcast(phi::DenseTensor*, phi::DenseTensor const&, phi::distributed::BroadcastOptions const&, bool)
1   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, phi::DenseTensor const&, phi::distributed::CommType, bool, bool)
2   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, std::vector<phi::DenseTensor, std::allocator<phi::DenseTensor> > const&, phi::distributed::CommType, bool, bool)
3   paddle::memory::RecordStream(std::shared_ptr<phi::Allocation>, void*)
4   paddle::memory::allocation::AllocatorFacade::RecordStream(std::shared_ptr<phi::Allocation>, void*)
5   paddle::memory::allocation::StreamSafeCustomDeviceAllocation::RecordStream(void*)
6   phi::CustomDevice::RecordEvent(unsigned long, phi::event::Event const*, phi::stream::Stream const*)
7   RecordEvent(C_Device_st*, C_Stream_st*, C_Event_st*)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1756456854 (unix time) try "date -d @1756456854" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x90ced) received by PID 593133 (TID 0x7f287ff03740) from PID 593133 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::distributed::ProcessGroupWithStream::Broadcast(phi::DenseTensor*, phi::DenseTensor const&, phi::distributed::BroadcastOptions const&, bool)
1   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, phi::DenseTensor const&, phi::distributed::CommType, bool, bool)
2   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, std::vector<phi::DenseTensor, std::allocator<phi::DenseTensor> > const&, phi::distributed::CommType, bool, bool)
3   paddle::memory::RecordStream(std::shared_ptr<phi::Allocation>, void*)
4   paddle::memory::allocation::AllocatorFacade::RecordStream(std::shared_ptr<phi::Allocation>, void*)
5   paddle::memory::allocation::StreamSafeCustomDeviceAllocation::RecordStream(void*)
6   phi::CustomDevice::RecordEvent(unsigned long, phi::event::Event const*, phi::stream::Stream const*)
7   RecordEvent(C_Device_st*, C_Stream_st*, C_Event_st*)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1756456854 (unix time) try "date -d @1756456854" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x90ced) received by PID 593130 (TID 0x7fab91895740) from PID 593133 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::distributed::ProcessGroupWithStream::Broadcast(phi::DenseTensor*, phi::DenseTensor const&, phi::distributed::BroadcastOptions const&, bool)
1   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, phi::DenseTensor const&, phi::distributed::CommType, bool, bool)
2   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, std::vector<phi::DenseTensor, std::allocator<phi::DenseTensor> > const&, phi::distributed::CommType, bool, bool)
3   paddle::memory::RecordStream(std::shared_ptr<phi::Allocation>, void*)
4   paddle::memory::allocation::AllocatorFacade::RecordStream(std::shared_ptr<phi::Allocation>, void*)
5   paddle::memory::allocation::StreamSafeCustomDeviceAllocation::RecordStream(void*)
6   phi::CustomDevice::RecordEvent(unsigned long, phi::event::Event const*, phi::stream::Stream const*)
7   RecordEvent(C_Device_st*, C_Stream_st*, C_Event_st*)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1756456854 (unix time) try "date -d @1756456854" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x90ced) received by PID 593132 (TID 0x7f751874d740) from PID 593133 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::distributed::ProcessGroupWithStream::Broadcast(phi::DenseTensor*, phi::DenseTensor const&, phi::distributed::BroadcastOptions const&, bool)
1   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, phi::DenseTensor const&, phi::distributed::CommType, bool, bool)
2   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, std::vector<phi::DenseTensor, std::allocator<phi::DenseTensor> > const&, phi::distributed::CommType, bool, bool)
3   paddle::memory::RecordStream(std::shared_ptr<phi::Allocation>, void*)
4   paddle::memory::allocation::AllocatorFacade::RecordStream(std::shared_ptr<phi::Allocation>, void*)
5   paddle::memory::allocation::StreamSafeCustomDeviceAllocation::RecordStream(void*)
6   phi::CustomDevice::RecordEvent(unsigned long, phi::event::Event const*, phi::stream::Stream const*)


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::distributed::ProcessGroupWithStream::Broadcast(phi::DenseTensor*, phi::DenseTensor const&, phi::distributed::BroadcastOptions const&, bool)
1   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, phi::DenseTensor const&, phi::distributed::CommType, bool, bool)
2   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, std::vector<phi::DenseTensor, std::allocator<phi::DenseTensor> > const&, phi::distributed::CommType, bool, bool)
3   paddle::memory::RecordStream(std::shared_ptr<phi::Allocation>, void*)
4   paddle::memory::allocation::AllocatorFacade::RecordStream(std::shared_ptr<phi::Allocation>, void*)
5   paddle::memory::allocation::StreamSafeCustomDeviceAllocation::RecordStream(void*)
6   phi::CustomDevice::RecordEvent(unsigned long, phi::event::Event const*, phi::stream::Str7   RecordEvent(C_Device_st*, C_Stream_st*, C_Event_st*)
eam const*)

7   RecordEvent(C_Device_st*, C_Stream_st*, C_Event_st*)
----------------------

Error Message Summary:
----------------------
----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1756456854 (unix time) try "date -d @1756456854" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x90ced) received by PID 593128 (TID 0x7f2db10b5740) from PID 593133 ***]
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1756456854 (unix time) try "date -d @1756456854" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x90ced) received by PID 593129 (TID 0x7f6aa59b8740) from PID 593133 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::distributed::ProcessGroupWithStream::Broadcast(phi::DenseTensor*, phi::DenseTensor const&, phi::distributed::BroadcastOptions const&, bool)
1   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, phi::DenseTensor const&, phi::distributed::CommType, bool, bool)
2   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, std::vector<phi::DenseTensor, std::allocator<phi::DenseTensor> > const&, phi::distributed::CommType, bool, bool)
3   paddle::memory::RecordStream(std::shared_ptr<phi::Allocation>, void*)
4   paddle::memory::allocation::AllocatorFacade::RecordStream(std::shared_ptr<phi::Allocation>, void*)
5   paddle::memory::allocation::StreamSafeCustomDeviceAllocation::RecordStream(void*)
6   phi::CustomDevice::RecordEvent(unsigned long, phi::event::Event const*, phi::stream::Str
eam const*)
7   RecordEvent(C_Device_st*, C_Stream_st*, C_Event_st*)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1756456854 (unix time) try "date -d @1756456854" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x90ced) received by PID 593127 (TID 0x7f99e4266740) from PID 593133 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::distributed::ProcessGroupWithStream::Broadcast(phi::DenseTensor*, phi::DenseTensor const&, phi::distributed::BroadcastOptions const&, bool)
1   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, phi::DenseTensor const&, phi::distributed::CommType, bool, bool)
2   paddle::distributed::ProcessGroupCustom::RunFnInXCCLEnv(std::function<void (phi::stream::Stream const&)>, std::vector<phi::DenseTensor, std::allocator<phi::DenseTensor> > const&, phi::distributed::CommType, bool, bool)
3   paddle::memory::RecordStream(std::shared_ptr<phi::Allocation>, void*)
4   paddle::memory::allocation::AllocatorFacade::RecordStream(std::shared_ptr<phi::Allocation>, void*)
5   paddle::memory::allocation::StreamSafeCustomDeviceAllocation::RecordStream(void*)
6   phi::CustomDevice::RecordEvent(unsigned long, phi::event::Event const*, phi::stream::Stream const*)
7   RecordEvent(C_Device_st*, C_Stream_st*, C_Event_st*)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1756456854 (unix time) try "date -d @1756456854" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x90ced) received by PID 593131 (TID 0x7fb38404c740) from PID 593133 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   egr::Backward(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, bool)
1   egr::RunBackward(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, bool, bool, std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, bool, std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&)
2   egr::GradNodeAccumulation::operator()(paddle::small_vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, 15u>&, bool, bool)
3   egr::GradNodeAccumulation::ApplyReduceHooks()
4   paddle::distributed::EagerReducer::MarkVarReady(unsigned long, bool)
5   paddle::distributed::EagerReducer::MarkGroupReady(unsigned long)
6   paddle::distributed::EagerReducer::FusedAllReduceSchedule(paddle::distributed::EagerGroup*, int)
7   paddle::distributed::ProcessGroupCustom::AllReduce(std::vector<phi::DenseTensor, std::allocator<phi::DenseTensor> >&, std::vector<phi::DenseTensor, std::allocator<phi::DenseTensor> >&, phi::distributed::AllreduceOptions const&)
8   paddle::memory::RecordStream(std::shared_ptr<phi::Allocation>, void*)
9   paddle::memory::allocation::AllocatorFacade::RecordStream(std::shared_ptr<phi::Allocation>, void*)
10  paddle::memory::allocation::StreamSafeCustomDeviceAllocation::RecordStream(void*)
11  phi::CustomDevice::RecordEvent(unsigned long, phi::event::Event const*, phi::stream::Stream const*)
12  RecordEvent(C_Device_st*, C_Stream_st*, C_Event_st*)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1756456854 (unix time) try "date -d @1756456854" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x90cec) received by PID 593126 (TID 0x7fb95b556740) from PID 593132 ***]

Terminated
```
看起来程序卡在集合通信阶段。日志和调用栈显示，Rank 0 进程卡在 AllReduce 操作，而所有其他（Rank 1-7）进程均卡在 Broadcast 操作。

**Comment by tianyuzhou668** [comment]
好的，可以试着排查下机器环境是否存在问题：
可以在/usr/local/corex/corex-toolbox/bin下执行下simpleP2P程序，看下结果是否符合预期。

**Comment by 404bro** [comment]
问题解决了，感谢帮助排查。

toolbox 中的 `simpleP2P` 结果验证失败，但 `all_reduce_perf` 成功，猜测是这个机器上类似 GPU Direct P2P 的机制不支持导致集合通信挂起，设置 `export NCCL_P2P_DISABLE=1` 就解决问题了。
