### ISSUE TITLE
Error occured "no CUDA-capable device is detected at [/paddle/Paddle/paddle/platform/gpu_info.cc:32]" when using CPUPlace()  

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#7519]
When I use the Fluid API with CPUPlace, I meet this error:
```
Traceback (most recent call last):
  File "resnet50_cpu.py", line 15, in <module>
    import paddle.v2.fluid as fluid
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/__init__.py", line 68, in <module>
    __bootstrap__()
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/__init__.py", line 65, in __bootstrap__
    core.init_devices()
paddle.v2.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: no CUDA-capable device is detected at [/paddle/Paddle/paddle/platform/gpu_info.cc:32]
PaddlePaddle Call Stacks:
0       0x7ff94c7d89b7p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7ff94d0de960p paddle::platform::GetCUDADeviceCount() + 304
2       0x7ff94c890a5ep paddle::framework::InitDevices() + 78
3       0x7ff94c7d442fp void pybind11::cpp_function::initialize<void (*&)(), void, , pybind11::name, pybind11::scope, pybind11::sibling>(void (*&)(), void (*)(), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) + 15
4       0x7ff94c7eece4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
5             0x4c45fap PyEval_EvalFrameEx + 1674
6             0x4c2705p PyEval_EvalCodeEx + 597
7             0x4ca7dfp PyEval_EvalFrameEx + 26735
8             0x4c2705p PyEval_EvalCodeEx + 597
9             0x4c24a9p PyEval_EvalCode + 25
10            0x4c05bbp PyImport_ExecCodeModuleEx + 203
11            0x4bd68ep
12            0x4be987p
13            0x4afbddp
14            0x4af361p PyImport_ImportModuleLevel + 2193
15            0x4b0f58p
16            0x4b0c93p PyObject_Call + 67
17            0x4ce540p PyEval_CallObjectWithKeywords + 48
18            0x4c73a6p PyEval_EvalFrameEx + 13366
19            0x4c2705p PyEval_EvalCodeEx + 597
20            0x4c24a9p PyEval_EvalCode + 25
21            0x4f19efp
22            0x4ec372p PyRun_FileExFlags + 130
23            0x4eaaf1p PyRun_SimpleFileExFlags + 401
24            0x49e208p Py_Main + 1736
25      0x7ff969628830p __libc_start_main + 240
26            0x49da59p _start + 41
```

I installed paddlepaddle by compiling the source code with gpu, and the name of the whl package is:  paddlepaddle_gpu-0.11.0-cp27-cp27mu-linux_x86_64.whl

**Comment by wanghaox** [comment]
This is a known issue.
https://github.com/PaddlePaddle/Paddle/issues/7416

You can use CPU version first.

**Comment by chengduoZH** [comment]
This issue has been solved by https://github.com/PaddlePaddle/Paddle/pull/7528.
