### ISSUE TITLE
GPU训练 Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function

### ISSUE THREAD

**Issue by HljWafer** [PaddlePaddle/Paddle#7820]
![image](https://user-images.githubusercontent.com/14160435/35321063-f24d59ba-0120-11e8-847d-c52e4a2e00cd.png)

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

安装是用的pip install paddlepaddle-gpu， 运行的 首页的例子，只是把gpu使用改成了true

**Comment by Yancey1989** [comment]
可以尝试更新驱动到最新版本，使用cuda8，并使用对应cuda8编译的paddle。
参考：https://github.com/PaddlePaddle/Paddle/issues/7804#issuecomment-360058030

**Comment by HljWafer** [comment]
问题已经解决

**Comment by SunlerZRY** [comment]
How do you fix the problem?
