### ISSUE TITLE
WSL2Ubuntu报警告The third-party dynamic library (libcuda.so) that Paddle depends on is not configured correctly.

### ISSUE THREAD

**Issue by TonyEinstein** [PaddlePaddle/Paddle#78917]
### bug描述 Describe the Bug

出现下述的警告：
`
============================================================
PaddlePaddle GPU vs CPU 性能对比
矩阵大小: 4096 x 4096
预热次数: 5, 测试迭代次数: 20
============================================================

--- 正在测试 GPU ---
W0508 21:40:15.979074  1551 dynamic_loader.cc:412] The third-party dynamic library (libcuda.so) that Paddle depends on is not configured correctly. (error code is libcuda.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;%PATH%`
  - Mac: set  DYLD_LIBRARY_PATH by `export DYLD_LIBRARY_PATH=...` [Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled.]
W0508 21:40:15.993314  1551 gpu_resources.cc:116] Please NOTE: device: 0, GPU Compute Capability: 12.0, Driver API Version: 13.2, Runtime API Version: 13.0
GPU 平均耗时: 6.378 ms

--- 正在测试 CPU ---
CPU 平均耗时: 1010.426 ms

🚀 GPU 加速比: 158.43x
`
代码是：

`
import paddle
import time
import numpy as np

def run_paddle_benchmark(matrix_size: int = 4096, warmup: int = 5, iterations: int = 20):
    print("="*60)
    print("PaddlePaddle GPU vs CPU 性能对比")
    print(f"矩阵大小: {matrix_size} x {matrix_size}")
    print(f"预热次数: {warmup}, 测试迭代次数: {iterations}")
    print("="*60)

    gpu_available = paddle.device.is_compiled_with_cuda() and paddle.device.cuda.device_count() > 0
    if not gpu_available:
        print("⚠️ GPU 不可用，将只测试 CPU")

    np.random.seed(42)
    a_np = np.random.randn(matrix_size, matrix_size).astype('float32')
    b_np = np.random.randn(matrix_size, matrix_size).astype('float32')

    def benchmark(device: str):
        paddle.set_device(device)
        a = paddle.to_tensor(a_np, stop_gradient=False)
        b = paddle.to_tensor(b_np, stop_gradient=False)

        # 预热
        for _ in range(warmup):
            _ = paddle.matmul(a, b)
        # 仅GPU做同步，CPU跳过
        if device == "gpu":
            paddle.device.synchronize("gpu")

        # 正式计时
        start = time.perf_counter()
        for _ in range(iterations):
            _ = paddle.matmul(a, b)
        if device == "gpu":
            paddle.device.synchronize("gpu")
        end = time.perf_counter()

        avg_time = (end - start) * 1000 / iterations
        return avg_time

    # 先测试 GPU（如果可用），再测试 CPU
    if gpu_available:
        print("\n--- 正在测试 GPU ---")
        gpu_time = benchmark('gpu')
        print(f"GPU 平均耗时: {gpu_time:.3f} ms")

    print("\n--- 正在测试 CPU ---")
    cpu_time = benchmark('cpu')
    print(f"CPU 平均耗时: {cpu_time:.3f} ms")

    if gpu_available:
        speedup = cpu_time / gpu_time
        print(f"\n🚀 GPU 加速比: {speedup:.2f}x")
    else:
        print("\n无法对比 GPU，当前环境不可用")

if __name__ == "__main__":
    run_paddle_benchmark(matrix_size=4096)
`

**Comment by hoobnn** [comment]
```
nvidia-smi
nvcc -V
```
能看下这两条的输出吗？

**Comment by TonyEinstein** [comment]
> ```
> nvidia-smi
> nvcc -V
> ```
> 
> 能看下这两条的输出吗？

谢谢回复，之前已经解决了。是因为我同一个虚拟环境里面装了PaddlePaddle、TensorFlow、torch，安装先后顺序被互相覆盖了CUDA、CUDNN（用cuda安装的），所以没有加载正确的兼容版本，调整了安装顺序、就没出现警告了。
