### ISSUE TITLE
场景文字识别运行时报错：Cuda Error: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8081]
* 我使用的是百度深度学习的GPU服务器，更新到最新的PaddlePaddle的版本了
* 我查看了CUDA的版本，为`CUDA Version 8.0.61`，CDNN的版本是`5.1.10`
* 我还要安装什么吗？
* 报错如下：
```text
I0202 13:29:53.189960 28490 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
F0202 13:29:53.192677 28490 hl_cuda_device.cc:453] Check failed: cudaSuccess == cudaStat (0 vs. 38) Cuda Error: no CUDA-capable device is detected
*** Check failure stack trace: ***
    @     0x7f9db2b88bcd  google::LogMessage::Fail()
    @     0x7f9db2b8c67c  google::LogMessage::SendToLog()
    @     0x7f9db2b886f3  google::LogMessage::Flush()
    @     0x7f9db2b8db8e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f9db2b4455f  hl_specify_devices_start()
    @     0x7f9db2b4485d  hl_start()
    @     0x7f9db2ace55a  paddle::initMain()
    @     0x7f9db2b705d1  initPaddle()
    @     0x7f9db2717c29  _wrap_initPaddle
    @           0x4cb755  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4de69e  (unknown)
    @           0x4b0c93  PyObject_Call
    @           0x4c6ef6  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4de858  (unknown)
    @           0x4b0c93  PyObject_Call
    @           0x4c6ef6  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4de858  (unknown)
    @           0x4b0c93  PyObject_Call
    @           0x4c6ef6  PyEval_EvalFrameEx
    @           0x4c9d7f  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4de858  (unknown)
    @           0x4b0c93  PyObject_Call
    @           0x4c6ef6  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
Aborted (core dumped)
```

**Comment by wanghaoshuang** [comment]
请参考这里：https://devtalk.nvidia.com/default/topic/876432/cuda-setup-and-installation/no-cuda-capable-device-is-detected/

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 
问题又成了另一个了
```
F0202 20:54:45.935290 19394 DynamicLoader.cpp:104] Check failed: nullptr != *dso_handle Failed to find dynamic library: libwarpctc.so (libwarpctc.so: cannot open shared object file: No such file or directory) 
Please specify its path correctly using following ways: 
Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
For instance, issue command: export LD_LIBRARY_PATH=... 
Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled.
*** Check failure stack trace: ***
    @     0x7f00c1f1818d  google::LogMessage::Fail()
    @     0x7f00c1f1a4d8  google::LogMessage::SendToLog()
    @     0x7f00c1f17c9b  google::LogMessage::Flush()
    @     0x7f00c1f1b3ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f00c1e472d6  GetDsoHandleFromSearchPath()
    @     0x7f00c1e47710  GetWarpCTCDsoHandle()
    @     0x7f00c58b2a99  __pthread_once_slow
    @     0x7f00c1eb740d  hl_warpctc_init()
    @     0x7f00c1b04a50  paddle::WarpCTCLayer::forward()
    @     0x7f00c1c3b203  paddle::NeuralNetwork::forward()
    @     0x7f00c1ee7bb0  GradientMachine::forwardBackward()
    @     0x7f00c1a78364  _wrap_GradientMachine_forwardBackward
    @           0x4cb755  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca088  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca088  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4de858  (unknown)
    @           0x4b0c93  PyObject_Call
    @           0x4c6ef6  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4de858  (unknown)
    @           0x4b0c93  PyObject_Call
    @           0x4c6ef6  PyEval_EvalFrameEx
    @           0x4c9d7f  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4de858  (unknown)
    @           0x4b0c93  PyObject_Call
    @           0x4c6ef6  PyEval_EvalFrameEx
Aborted (core dumped)
```

**Comment by luotao1** [comment]
可以参考 https://github.com/PaddlePaddle/Paddle/issues/7718#issuecomment-359316112

**Comment by yeyupiaoling** [comment]
@luotao1 
感谢回答，问题已解决。我在https://github.com/baidu-research/warp-ctc/blob/master/README.zh_cn.md 找到了安装libwarpctc.so的方法。
